### ISSUE TITLE
Configuration through a CLI and a configuration file

### ISSUE THREAD

**Issue by vincentbernat** [vincentbernat/lldpd#1]
Currently, lldpd can be configured with some command line parameter. There is the beginning of configuration support in lldpctl (for LLDP-MED location). To be a complete LLDP implementation, we need more complete configuration. The administrator should be able to enable/disable each port independantly, like this is done on a switch.

To avoid to add a parser, the configuration will be done by lldpctl. When lldpd is started, it will wait to be configured by lldpctl. lldpctl will read and write the configuration from/to a file. A CLI could also be added.

This way, the memory footprint and the number of lines in lldpd will stay pretty low.

**Comment by jerhone** [comment]
Hi Vincent,

First of all. Thanks for this lldp... cool stuff. However, I have been digging my brain on how to let it work with CDP v2. I followed the -c option but it seem to only receive cdp packets and does not advertise it. I have seen this by debugging in a cisco switch and doin tcpdump. Can you please enlighten me on how to properly advertise CDP v2?

Cheers!

**Comment by vincentbernat** [comment]
❦ 13 mai 2015 03:42 -0700, jerhone <notifications@github.com> :

> First of all. Thanks for this lldp... cool stuff. However, I have been
> digging my brain on how to let it work with CDP v2. I followed the -c
> option but it seem to only receive cdp packets and does not advertise
> it. I have seen this by debugging in a cisco switch and doin tcpdump.
> Can you please enlighten me on how to properly advertise CDP v2?

With just `-c`, CDP packets are only sent on ports where CDP packets are
received.Either:

 - use `-cc` to force use of CDP
 - run with `-dd` to understand why CDP is not used for sending.

In both cases, if there is still an issue, open a new issue.
-- 
Don't stop with your first draft.
            - The Elements of Programming Style (Kernighan & Plauger)

**Comment by jerhone** [comment]
Apologies for the noob question in previous post. I kinda foundout what happened, I used option -cc and -cccc to make sure it only sends cdpv2 and it worked smoothly. However, when I reboot system or restart lldp, the options -cc or -cccc are gone and stops workin again. 

Another noob question, how do I start lldp with the -cc or -cccc automatically upon boot?

**Comment by vincentbernat** [comment]
It depends on your distribution. On Debian/Ubuntu, you can put the option in `/etc/default/lldpd`.

**Comment by jerhone** [comment]
I am using CentOS 6. I edited the /etc/init.d/lldpd and tried LLDPD_OPTIONS

LLDPD_OPTIONS="-cccc"

It did not work. So what I did was comment out the daemon like below and put  /usr/sbin/lldpd -cccc:

else
     48                 #daemon $daemonopts $binary $LLDPD_OPTIONS
     49                 /usr/sbin/lldpd -cccc
     50                 RETVAL=$?
     51                 [ $RETVAL -eq 0 ] && touch $lockfile

Is there a better or best way to do this -cccc option upon bootup?

**Comment by vincentbernat** [comment]
Have a look at `/etc/sysconfig/lldpd`.

**Comment by jerhone** [comment]
Now that really helped alot! Thanks again!

**Comment by vincentbernat** [comment]
Not everything is converted, but many stuff can now be configured in configuration file. It seems useless to leave this issue open.

**Comment by mudduprasad** [comment]
Can you please help in clarifying below query?
Is it possible for LLDP application to send LLDP advertisement with TTL of "0".
If so what is command or configuration that needs to be done?

**Comment by vincentbernat** [comment]
lldpd will only send such an advertisement on shutdown. Otherwise, it won't.

**Comment by mudduprasad** [comment]
Hi vincent, is there any command to perform shutdown?

**Comment by vincentbernat** [comment]
It will be sent when lldpd exits.

**Comment by ming-lee** [comment]
Hi Vincent,
I use lldpd-0.7.9, and I use the command "configuresystem hostname".
But it show "[WARN/lldpctl] unknown command from argument 1: `configuresystem`"
Is the lldp version too old?

**Comment by aimdev** [comment]
I noticed this message when I did a service lldpd status command.
I moved the README.conf away from the /etc/lldpd.d directory, and the message disappears
when lldpd is restarted. Suggest parsing of config files is incorrect
Aimee
