### ISSUE TITLE
Can I use lldp together with Quagga on Centos7

### ISSUE THREAD

**Issue by hughesr9** [vincentbernat/lldpd#100]
Hi,

I have installed lldp-0.7.13-1.1.x86_64.rpm on Centos 7.0.1406. I am running Boeing CORE Network emulation which uses the Quagga routing engine. I am trying to setup lldp and also grab link information via SNMP.

Currently I startup lldpd on the virtual routers but when I run lldpctl no Neighbors are being shown. 
Also I cannot seem to snmpwalk to the lldp OID values.

snmpwalk -v 2c -c public xx.xx.xx.xx 1.0.8802.1.1.2.1.4.1.1

I guess my first question is, is it possible to achieve what I am trying to do with lldp and Quagga?

Regards
Rob

**Comment by vincentbernat** [comment]
I don't know exactly how CORE works, but I suppose it is using bridges on the host. Therefore, you also need to run lldpd on the host. Each virtual router would then see the host as its neighbor.

**Comment by hughesr9** [comment]
Hi Vincent,

Yes, when I started lldp on the host I could then see neighbors being shown.

I am trying to get snmp to be able to give me information on the links, I believe that snmp support is available but not compiled into lldpd by default. On Vyos which runs on Debian 6, I am having problems with the autoconf, I wonder if you have seen this issue before? Perhaps there is configure file available somewhere, but I haven’t been able to find one.

# autoconf configure.ac > configure
Configure.ac:23: error: possibly undefined macro: AM_INIT_AUTOMAKE
    If this token and others are legitimate, please use m4_pattern_allow.
    See the Autoconf documentation.
configure.ac:24: error: possibly undefined macro: AM_MAINTAINER_MODE
configure.ac:42: error: possibly undefined macro: AM_PROG_CC_C_O
configure.ac:43: error: possibly undefined macro: AC_PROG_LIBTOOL
configure.ac:240: error: possibly undefined macro: AM_CONDITIONAL

Regards
Rob

**Comment by vincentbernat** [comment]
❦ 23 mars 2015 03:01 -0700, hughesr9 <notifications@github.com> :

> I am trying to get snmp to be able to give me information on the
> links, I believe that snmp support is available but not compiled into
> lldpd by default.

You can check with "lldpd -dx". It will complain if SNMP support is not
builtin.

> On Vyos which runs on Debian 6, I am having problems with the
> autoconf, I wonder if you have seen this issue before?  Perhaps there
> is configure file available somewhere, but I haven’t been able to find
> one.
>
> # autoconf configure.ac > configure 
> Configure.ac:23: error: possibly undefined macro: AM_INIT_AUTOMAKE 
> If this token and others are legitimate, please use m4_pattern_allow. 
> See the Autoconf documentation. 
> configure.ac:24: error: possibly undefined macro: AM_MAINTAINER_MODE 
> configure.ac:42: error: possibly undefined macro: AM_PROG_CC_C_O 
> configure.ac:43: error: possibly undefined macro: AC_PROG_LIBTOOL 
> configure.ac:240: error: possibly undefined macro: AM_CONDITIONAL 

It seems that neither automake, nor libtool are installed. If you
download the released tarball, you don't need to run autoconf:
 http://media.luffy.cx/files/lldpd/lldpd-0.7.13.tar.gz
-- 
In a museum in Havana, there are two skulls of Christopher Columbus,
"one when he was a boy and one when he was a man."
		-- Mark Twain

**Comment by hughesr9** [comment]
Hi Vincent,

That works much better, a ./configure runs through with no issues now fine.
When I try and add SNMP support it is giving an error:

./configure –with-snmp

Configure: error: *** incorrect CFLAGS from net-snmp-config

I did see some references to this error from back in April, but it seems like it was fixed. Or could I be missing a net-snmp .h file?

Regards
Rob

**Comment by vincentbernat** [comment]
❦ 23 mars 2015 07:08 -0700, hughesr9 <notifications@github.com> :

> ./configure –with-snmp 
>
> Configure: error: *** incorrect CFLAGS from net-snmp-config 
>
> I did see some references to this error from back in April, but it
> seems like it was fixed. Or could I be missing a net-snmp .h file? 

Have a look at config.log, it should tell what error the C compiler did
get. Search for "net-snmp-config".
-- 
Make sure special cases are truly special.
            - The Elements of Programming Style (Kernighan & Plauger)

**Comment by hughesr9** [comment]
Hi Vincent,

I can see this error:

/usr/bin/ld: cannot find –lnetsnmpmibs
Collect2: id returned 1 exit status

Regards
Rob

**Comment by vincentbernat** [comment]
❦ 23 mars 2015 08:15 -0700, hughesr9 <notifications@github.com> :

> I can see this error: 
>
> /usr/bin/ld: cannot find –lnetsnmpmibs 
> Collect2: id returned 1 exit status 

What does "net-snmp-config --libs" says?
-- 
The Public is merely a multiplied "me."
		-- Mark Twain

**Comment by hughesr9** [comment]
-L/usr/lib –lnetsnmp –lrt –lssl –lssl –lcrypto –lm

**Comment by vincentbernat** [comment]
❦ 23 mars 2015 08:47 -0700, hughesr9 <notifications@github.com> :

> -L/usr/lib –lnetsnmp –lrt –lssl –lssl –lcrypto –lm 

Oh, sorry, that's "net-snmp-config --agent-libs". I suppose that the
"-lnetsnmpmibs" come from here. Do you have development headers for
NetSNMP installed? Something in /usr/include/net-snmp?
-- 
What good is an obscenity trial except to popularize literature?
		-- Nero Wolfe, "The League of Frightened Men"

**Comment by hughesr9** [comment]
Ah yes,

net-snmp-config –agent-libs

-L/usr/lib –lnetsnmpmibs –lsensors –lpci –ldl –lnetsnmpagent –Wl, -E –lnetsnmp –lrt –lssl –lssl –lcrypto –lm

No, there is no /etc/include/net-snmp directory.

When I am in /usr/lib and run ld –lnetsnmpmibs –verbose

It finds a load of libraries ok but then fails with this error:

Found libresolv.so.2 at /lib64/libresolv.so.2
Ld: warning: cannot find entry symbol _start; not setting start address

Not sure if this is an issue.

Regards
Rob

**Comment by vincentbernat** [comment]
❦ 23 mars 2015 09:02 -0700, hughesr9 <notifications@github.com> :

> net-snmp-config –agent-libs 
>
> -L/usr/lib –lnetsnmpmibs –lsensors –lpci –ldl –lnetsnmpagent –Wl, -E –
> lnetsnmp –lrt –lssl –lssl –lcrypto –lm 
>
> No, there is no /etc/include/net-snmp directory. 

Try "ldconfig -p | grep netsnmpmibs". If you only have something like
"libnetsnmpmibs.so.30" but not "libnetsnmpmibs.so", this means that you
need to install NetSNMP development packages. If this is Debian based,
install libsnmp-dev.
-- 
Keep it simple to make it faster.
            - The Elements of Programming Style (Kernighan & Plauger)

**Comment by hughesr9** [comment]
Hi Vincent,

Yes that was the problem, it now configures and makes with no issues.

Thank you very much for your help and patience.

Regards
Rob

**Comment by vincentbernat** [comment]
Great! Closing.
