### ISSUE TITLE
Frame type unknown in wireshark

### ISSUE THREAD

**Issue by eduble** [vincentbernat/lldpd#102]
Hello Vincent,
Thanks for you work, also on snimpy which works very well. 
I have a question regarding lldpd. 
I installed it on debian jessie, and, without anymore configuration, when I type "lldpcli update" wireshark detects an ethernet frame but cannot decode it. Its ethertype is 0xc03f (not the one of LLDP).
Is it expected?
Thanks
Etienne

**Comment by vincentbernat** [comment]
❦ 26 mars 2015 07:26 -0700, Etienne Dublé <notifications@github.com> :

> Thanks for you work, also on snimpy which works very well. 
> I have a question regarding lldpd. 
> I installed it on debian jessie, and, without anymore configuration,
> when I type "lldpcli update" wireshark detects an ethernet frame but
> cannot decode it. Its ethertype is 0xc03f (not the one of LLDP).

Could you provide a pcap of this frame? It is not expected.
-- 
Treat end of file conditions in a uniform manner.
            - The Elements of Programming Style (Kernighan & Plauger)

**Comment by eduble** [comment]
Strangely I do not manage to reproduce the issue this morning. I get appropriate LLDP mulitcast messages now. I think you can close the issue.

**Comment by eduble** [comment]
Ah. This is when I select  'any', in wireshark, for the capture interface. I guess the kernel mess with it and I get a modified frame.
When I select a proper interface 'eth0' the frame is ok.

**Comment by vincentbernat** [comment]
Fine! Closing.
