### ISSUE TITLE
customize port descr

### ISSUE THREAD

**Issue by cpalmer9** [vincentbernat/lldpd#107]
Hi there,

I am trying to find out if we can modify the PortDescr sent by a host.
Currently, we are using:
configure lldp portidsubtype ifname
... and a sample PortDescr looks like this: fpti1_0_2
I would like have it show: port_2   (basically strip the leading fpti1_0 text).

However, on other devices, we would want to strip a different leading string, and again end up with "port_X" where X is the port identification number.

Is this possible with lldpd?
If so, can you help explain how to set this up?
thanks!
Christopher

**Comment by kanrajag** [comment]
Chris
port description is picked up from the alias on the interface (ip link set dev <swp1> alias <name>) this will cause lldpd to pick the alias and stick it in the port descr TLV.

there is another way of setting portidsubtype = local, with an optional port description (configurable via the lldpcli command). this change is new and you can look for it in the latest lldpcli

-kanna

**Comment by vincentbernat** [comment]
Already implemented.
