### ISSUE TITLE
json and xml format does not work

### ISSUE THREAD

**Issue by brylor** [vincentbernat/lldpd#108]
Hi,

I am using lldpd -v 0.7.14 compiled from source on Scientific Linux.

lldpcli -d -f json show neighbor only shows as plain.

lldpcli -d -f xml show neighbor only shows as plain.

Although, lldpcli -f keyvalue show neighbor does work properly.

I really would like the json, since parsing it would be easier.

Thanks!

**Comment by kanrajag** [comment]
you have to enable these features during compile time.. 
on Debian we do this using the rules file. not sure about scientific linux..

DEB_CONFIGURE_EXTRA_FLAGS = --with-xml --with-json=json-c

**Comment by brylor** [comment]
Excellent that was it!

I had to yum install libxml2-devel and... 

Download jansson source, configure, make, make install..

I guess there are many locations for pkgconfig... but this is what worked
 
mv /usr/lib/pkgconfig/jansson.pc /usr/share/pkgconfig/

Thanks again!
