### ISSUE TITLE
no JSON format?

### ISSUE THREAD

**Issue by cpalmer9** [vincentbernat/lldpd#110]
Hi there.  I have lldpd version 0.7.14 and I am unable to get the "lldpcli show neighbors" output to format in JSON.
Using the -f option I can do: plain, xml, keyvalue however.  .... when I specify "json", it outputs as "plain".

**Comment by vincentbernat** [comment]
❦  8 mai 2015 17:29 -0700, Christopher Palmer <notifications@github.com> :

> Hi there. I have lldpd version 0.7.14 and I am unable to get the
> "lldpcli show neighbors" output to format in JSON.
> Using the -f option I can do: plain, xml, keyvalue however. .... when
> I specify "json", it outputs as "plain".

Your version of lldpd is likely to be not compiled with JSON support. If
you compiled it yourself, you need to use --with-json. Maybe I should
change JSON support to be autodetected.
-- 
Must I hold a candle to my shames?
		-- William Shakespeare, "The Merchant of Venice"

**Comment by cpalmer9** [comment]
Thank you Vincent.  I have recompiled it using --with-json (and had jansson-devel and jansson packages installed beforehand).  I can now use that format.

**Comment by vincentbernat** [comment]
Meanwhile, I have added ability to specify auto parameters (`--with-json=auto`). Wouldn't change much but it could become a default.
