### ISSUE TITLE
lldpd can't accept -u command-line argument

### ISSUE THREAD

**Issue by dfberger** [vincentbernat/lldpd#116]
ctlname is unconditionally assigned on src/daemon/lddpd.c:1289
         const char *ctlname = LLDPD_CTL_SOCKET;
and tested in the argument handling around src/daemon/lddpd.c:1358
                case 'u':
                        if (ctlname) {
                                fprintf(stderr, "-u can only be used once\n");
                                usage();
                        }
                        ctlname = optarg;
                        break;

**Comment by vincentbernat** [comment]
This should have been fixed in #84 (released in 0.7.13).

**Comment by dfberger** [comment]
Thanks, and sorry for the spurious report - I should have double checked the current HEAD before opening.
