### ISSUE TITLE
FreeBSD: IPv4 address in CDP packets is wrong

### ISSUE THREAD

**Issue by kostikbel** [vincentbernat/lldpd#117]
I have lldpd 0.7.14 installed on the FreeBSD/amd64 stable/9.  This is the version from ports.
```
$ ifconfig vlan1
vlan1: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=103<RXCSUM,TXCSUM,TSO4>
        ether 00:22:4d:7a:47:f6
        inet 192.168.102.80 netmask 0xffffff00 broadcast 192.168.102.255
        inet6 fe80::222:4dff:fe7a:47f6%vlan1 prefixlen 64 scopeid 0xa
        nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
        media: Ethernet autoselect (1000baseT <full-duplex>)
        status: active
        vlan: 1 parent interface: em0
```

I noted the strangeness in the IP address displayed on other network elements for the FreeBSD box:
```
[kostik@switch1] > ip neighbor print detail 
 0 interface=ether1 address=192.168.80.80 address4=192.168.80.80 
   mac-address=00:22:4D:7A:47:F6 identity="tom.home" platform="FreeBSD" 
   version=" FreeBSD 9.3-STABLE FreeBSD 9.3-STABLE #5 r284286: Fri Jun 12 
        04:24:17 EEST 2015     root@tom.home:/usr/obj/usr/home/bsd/src/sys/TOM 
        amd64" 
   unpack=none age=26s interface-name="vlan1" 
```
Note the 192.168._80_.80, while the correct address is 192.168._102_.80.

And indeed, from the tcpdump:
```
tom% sudo tcpdump -i vlan1 -n -p -s 0 -vvv -e not ip and not ip6 and not arp  ~
zsh: correct 'ip' to 'kp' [nyae]? n
tcpdump: listening on vlan1, link-type EN10MB (Ethernet), capture size 65535 bytes
07:21:21.477522 00:22:4d:7a:47:f6 > 01:00:0c:cc:cc:cc, 802.3, length 225: LLC, dsap SNAP (0xaa) Individual, ssap SNAP (0xaa) Command, ctrl 0x03: oui Cisco (0x00000c), pid CDP (0x2000): CDPv1, ttl: 120s, checksum: 376 (unverified), length 203
        Device-ID (0x01), length: 8 bytes: 'tom.home'
        Address (0x02), length: 13 bytes: IPv4 (1) 192.168.80.80
        Port-ID (0x03), length: 5 bytes: 'vlan1'
        Capability (0x04), length: 4 bytes: (0x00000011): Router, L3 capable
        Version String (0x05), length: 138 bytes:
           FreeBSD 9.3-STABLE FreeBSD 9.3-STABLE #5 r284286: Fri Jun 12 04:24:17 EEST 2015     root@tom.home:/usr/obj/usr/home/bsd/src/sys/TOM amd64
        Platform (0x06), length: 7 bytes: 'FreeBSD'
07:21:21.477554 00:22:4d:7a:47:f6 > 01:00:0c:cc:cc:cc, 802.3, length 225: LLC, dsap SNAP (0xaa) Individual, ssap SNAP (0xaa) Command, ctrl 0x03: oui Cisco (0x00000c), pid CDP (0x2000): CDPv2, ttl: 120s, checksum: 632 (unverified), length 203
        Device-ID (0x01), length: 8 bytes: 'tom.home'
        Address (0x02), length: 13 bytes: IPv4 (1) 192.168.80.80
        Port-ID (0x03), length: 5 bytes: 'vlan1'
        Capability (0x04), length: 4 bytes: (0x00000011): Router, L3 capable
        Version String (0x05), length: 138 bytes:
           FreeBSD 9.3-STABLE FreeBSD 9.3-STABLE #5 r284286: Fri Jun 12 04:24:17 EEST 2015     root@tom.home:/usr/obj/usr/home/bsd/src/sys/TOM amd64
        Platform (0x06), length: 7 bytes: 'FreeBSD'
```

Another thing I noted is that two PDUs are sent in rapid succession by the daemon, but this is definitely not critical.

**Comment by vincentbernat** [comment]
Could you run `lldpd -ddd` and spot log lines `add management address` to check if the address here is correct or not?

For the two PDU sent in rapid succession, one is CDPv1, the other is CDPv2. I suppose that you run `lldpd` with `-cc` or something like that.

**Comment by kostikbel** [comment]
Indeed, there are:
```
2015-06-12T08:40:35 [ DBG/interfaces] add management address 192.168.80.80
```
The address is incorrect.

I put the full output of the lldpd -ddd at https://kib.kiev.ua/kib/lldpd-ddd.txt in case you want to see it.

**Comment by vincentbernat** [comment]
Is `192.168.80.80` present on any other interface than `vlan1`?

**Comment by kostikbel** [comment]
Yes, it is the address on the loopback.

**Comment by vincentbernat** [comment]
For LLDP, the address advertised is a management address of the device, not the address on the interface. So, we take the first address matching some pattern (by default, any address). In your case, that's the one on the loopback. You can use `-m` to specify another pattern. But, you can't have one address per interface.

For CDP, we use the same address as for LLDP. The description of CDP from Cisco is not quite clear if the address that should be advertised is the address of the interface or the address of the device.

**Comment by kostikbel** [comment]
Thank you for the diagnostic.  I do not have cisco hw to test, my impression was that it should use a ll address for CDP.  Anyway, I see why it is done this way.

**Comment by vincentbernat** [comment]
Unfortunately, even if we agree that for CDP, we should use a LL address, the change is a bit invasive (but possible).
