### ISSUE TITLE
Nit: configure parameter --enable-hardening ... default=yes

### ISSUE THREAD

**Issue by matsimon** [vincentbernat/lldpd#118]
Hi

I just found in 0.7.15 the --enable-hardening switch. Almost all switches in the help output use the format  `--switch <description> [default=<value>]` whereas this switch is declared as `--enable-hardening <description> [yes]`. I know this is just a tiny nit in terms of consistency. :-)

Thanks for your work on lldpd

-- Mathieu

**Comment by vincentbernat** [comment]
Thanks for the notice, just fixed!
