### ISSUE TITLE
Regarding the dependency files for the lldpd project in Unix

### ISSUE THREAD

**Issue by kaustav1992** [vincentbernat/lldpd#121]
It was great going through your lldpd code and I'm using your open source lldp implementation in one of my projects.
I had a question which I'm pondering upon since quite sometime. I was having a look at the lldpcli process and had a look at its dependencies. I was curious about the following dependencies- liblldpctl.so.4-->/usr/lib/
and libbsd.so.0-->/lib/x86_64-linux-gnu/
I was really curious to understand where does the linking takes place for these shared libraries since I couldn't find any reference to them in the Makefiles in any of the folders.

It would be great if you could get back to me regarding this.

Thanks,
Kaustav Ghosh
Graduate Student Santa Clara University,California

**Comment by vincentbernat** [comment]
In `src/client/Makefile.am`, search for `liblldpctl.la`. In `configure.ac`, search for `setproctitle`.

**Comment by kaustav1992** [comment]
Thanks for the response. I was wondering if there is a workaround wherein I can remove the dependencies i.e convert the above mentioned shared libraries to a static library?

**Comment by vincentbernat** [comment]
Maybe `./configure --disable-shared --enable-static` for liblldpctl. For libbsd, just remove the dev package from your system.

**Comment by kaustav1992** [comment]
I tried the --disable option but that disabled the libc library sharing too because of which I'm getting errors while making. Is there a way by which I can specifically change the liblldpctl config from dynamic to static library?

**Comment by vincentbernat** [comment]
Well, that's a bit difficult. Once compiled one time, you can modify `liblldpctl.la` and empty `library_names` and `dlname` and maybe set `installed` to `yes`. Then, delete `lldpcli` and run `make` again.

**Comment by kaustav1992** [comment]
Ok got your point. So suppose I build a static library for lldpctl which would be of the form liblldpctl.a at some local location. Where should I mention the information to link to that static library? Do I have to feed in some linking information in the liblldpctl.la file ?

**Comment by vincentbernat** [comment]
❦  1 juillet 2015 13:29 -0700, Kaustav Ghosh <notifications@github.com> :

> Ok got your point. So suppose I build a static library for lldpctl
> which would be of the form liblldpctl.a at some local location. Where
> should I mention the information to link to that static library? Do I
> have to feed in some linking information in the liblldpctl.la file ?

The static version of liblldpctl is already built. You just need to do
as I described to avoid its linking to a shared library and link it as a
static library instead.
-- 
"... all the modern inconveniences ..."
		-- Mark Twain

**Comment by kaustav1992** [comment]
Got you. I had one more question. After I execute the ./configure and make commands( not the make install), I get a binary for lldpd in the /build/src/daemon folder but I do not get a binary for the lldpcli in the /build/src/client folder. Instead I get a script for llpdcli. Where is the binary stored for lldpcli?

**Comment by vincentbernat** [comment]
It's in `/build/src/client/.libs`.

**Comment by kaustav1992** [comment]
Thanks a lot for answering that. One more question I had about the _lldpd user privilege. Is there a way by which I could turn that off and use lldpd as any other user?

**Comment by vincentbernat** [comment]
What do you mean? You can use `./configure --disable-privsep`, but you will have to run lldpd as root.

**Comment by kaustav1992** [comment]
Thank you. Got all what I needed. I was curious to know where have you implemented the code for the reception of CDP packets and processing it?

**Comment by vincentbernat** [comment]
❦  7 juillet 2015 09:44 -0700, Kaustav Ghosh <notifications@github.com> :

> Thank you. Got all what I needed. I was curious to know where have you
> implemented the code for the reception of CDP packets and processing
> it?

In src/daemon/protocols/cdp.c.
-- 
Keep it simple to make it faster.
            - The Elements of Programming Style (Kernighan & Plauger)

**Comment by kaustav1992** [comment]
Yes I was able to figure that out, but I wasn't clear as to from where do you call the CDP decode function, I'm assuming there's a generalized function for decoding the received frames which in turn calls the functions of CDP.

**Comment by vincentbernat** [comment]
❦  7 juillet 2015 10:07 -0700, Kaustav Ghosh <notifications@github.com> :

> Yes I was able to figure that out, but I wasn't clear as to from where
> do you call the CDP decode function, I'm assuming there's a
> generalized function for decoding the received frames which in turn
> calls the functions of CDP.

It's in src/daemon/lldpd.c
-- 
I dote on his very absence.
		-- William Shakespeare, "The Merchant of Venice"

**Comment by kaustav1992** [comment]
Hi Vincent, as mentioned in one of your above comments you had asked me to use 
./configure --disable-privsep
I did that but got the below mentioned error. Is this error because of the above mentioned configuration command or due to some other reason?

 [CRIT/privsep] unable to create chroot directory: No such file or directory

**Comment by vincentbernat** [comment]
This code is not reachable when compiled with `--disable-privsep`. Ensure you did run `make clean` before building again and check that `ENABLE_PRIVSEP` is commented out in `config.h`.

Also note that all what you are trying to accomplish is very bad from a security point of view. Static compilation diminishes greatly ability to resist to an escalation and removing privilege separation (and running the whole thing as root) is a risky for a daemon parsing network frames. You'll be vulnerable to any bug in lldpd.

**Comment by vincentbernat** [comment]
Not really a bug. Closing.
