### ISSUE TITLE
request: check /etc/redhat_release

### ISSUE THREAD

**Issue by djzort** [vincentbernat/lldpd#122]
Im seeing this error message in syslog

\# could not open either /etc/os-release or /usr/lib/os-release

on rhel/centos the /etc/redhat_release should be inspected.

\# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 6.6 (Santiago)

perhaps this should just be a compile time option, which the .spec file would set ?

**Comment by JohanElmis** [comment]
That is not really the same file.
In newer version - it does exist: This is from CentOS 7.
more /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

While Debian gives us:
more /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support/"
BUG_REPORT_URL="https://bugs.debian.org/"

The solution to older systems that doesn't have this file - would probably be to create one with the info like above. (Outside of LLDP).

**Comment by vincentbernat** [comment]
You can also get the same information with `lsb_release` when installed. I suppose that there is some RPM package that could provide such a command.

However, I could also add a fallback to read `/etc/redhat_release` or any similar file for other distributions.

**Comment by djzort** [comment]
.spec could depend upon lsb_release?

**Comment by vincentbernat** [comment]
Yes, it could. Is there a downside on that (for example, it may pull a lot of unwanted dependencies)?

**Comment by vincentbernat** [comment]
Well, the workaround seems to have a distribution with `/etc/os-release` or to install `lsb-release` package. I don't require it as it will become useless with time and `.spec` is already quite convoluted. Feel free to reopen if you disagree.
