### ISSUE TITLE
lldpd blocks for a while (20-30 seconds) at init (maybe some DNS resolver ?)

### ISSUE THREAD

**Issue by commodo** [vincentbernat/lldpd#125]
Hello,

I'm seeing some issues with lldpd.
When I restart it, it seems to hang for a few seconds (20-30 approx ; not sure, did not do a timing).

strace-ing lldpd seems like it's trying to do some DNS resolution.
Is this correct ?
If so, is there a nice way (maybe via configure args to disable this ?)
If not, I can add a local patch in our tree to disable it, until I get a chance to understand this better ; atm I am a bit low on time, hence this question/issue here.

Version is 0.7.15.

Thanks :)
Alex

**Comment by vincentbernat** [comment]
❦ 30 juillet 2015 09:08 -0700, Alexandru Ardelean <notifications@github.com> :

> I'm seeing some issues with lldpd.
> When I restart it, it seems to hang for a few seconds (20-30 approx ;
> not sure, did not do a timing).
>
> strace-ing lldpd seems like it's trying to do some DNS resolution.
> Is this correct ?
> If so, is there a nice way (maybe via configure args to disable this ?
> )
> If not, I can add a local patch in our tree to disable it, until I get
> a chance to understand this better ; atm I am a bit low on time, hence
> this question/issue here.
>
> Version is 0.7.15.

It may be when it is trying to get its name.

Try:

    getent hosts $(uname -n)

If this blocks too, you need to configure the machine such that getting
its name doesn't require a DNS request. Usually, `uname -n` should
appear somewhere in `/etc/hosts`
-- 
Keep it right when you make it faster.
            - The Elements of Programming Style (Kernighan & Plauger)

**Comment by commodo** [comment]
Seems to do it.
We'll have to see how to work this out (in our setup)

Thanks again for the help
