### ISSUE TITLE
configuration problems in lldpcli (med location {address language, coordinate datum})

### ISSUE THREAD

**Issue by bbidulock** [vincentbernat/lldpd#127]
Can't set a <code>med location address language</code>.  I think it is because the index of the "Language" is zero and the parsing logic thinks that 0 is invalid.  The line that is failing is:

    configure med location address country CA language "en_CA" counter-subdivision "Alberta" city "Edmonton" city-division "Millwoods" street "Jefferys Crescent" direction "NW" number "1469" zip "T6L 6T1"

Also, can't set a <code>med location coordinate datum</code>.  I have no idea why.  The line that is failing is:

    configure med location coordinate latitude 53.533N longitude 113.500W altitude "668.0 m" datum WSG84

**Comment by vincentbernat** [comment]
For datum, you should not put `"668.0 m"` in quotes. It's `668.0 m`. I'll have a look for the language stuff.

**Comment by vincentbernat** [comment]
Feel free to reopen if you still have an issue with the altitude.

**Comment by bbidulock** [comment]
Thanks for the fix on language.  And thank you for all the work that you put into this fine package.

For datum, yes, I tried no quotes too.  When I tried no quotes I got an error message saying the WSG84 was not a recognized command.  Sorry that I could not do better at identifying the section of code.

**Comment by vincentbernat** [comment]
It's WGS84 (World Geodetic System).

**Comment by bbidulock** [comment]
Doh!
