### ISSUE TITLE
Request to suppress log like...

### ISSUE THREAD

**Issue by jerhone** [vincentbernat/lldpd#132]
/var/log/messages show the below every minute:

lldpd[18714]: cannot connect to /var/agentx/master: No such file or directory
lldpd[18720]: Warning: Failed to connect to the agentx master agent ([NIL]):

I am not sure how to suppress these messages as I don't need them for now. Is there a way to suppress this?

Hoping for your kind response :-)

**Comment by vincentbernat** [comment]
Just disable AgentX support (remove `-x` from command-line arguments).

**Comment by jerhone** [comment]
Hi Vince,

Yep. I figured.

Thanks a lot!
