### ISSUE TITLE
[Question] Is there a lldpd service and how do you start it after building from source

### ISSUE THREAD

**Issue by pl1m** [vincentbernat/lldpd#136]
I tried to build the install from source. lldpd-0.7.17.tar.gz.  After the make install I looked for the lldpd service but when I tried to start it centos returned an unrecognized service message.  I followed the instructions on "http://vincentbernat.github.io/lldpd/installation.html#install-from-source".  I must be missing something.  

I'm trying to install Cumulus PTM but PTM  won't build unless I use the lldpd source package.  If I try to install lldpd from opensuse; PTM fails to build with problems with finding lldpctl.h but lldpd works.  I've tried to point the PTM configure file to the lldpctl.h file from your untared file lldp-0.7.17.tar.gz but it fails with the error:

checking for lldpctl_atom_dec_ref in -llldpctl... no
checking for lldpctl_process_conn_buffer in -llldpctl... no
configure: error: Need LLDPD > 0.7.10

**Comment by vincentbernat** [comment]
Which version of CentOS are you using?

**Comment by pl1m** [comment]
CentOS release 6.5 (Final)
[root@tor04 src]# uname -a
Linux tor04.st.lab 3.5.7 #3 SMP Wed Jul 8 06:44:06 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

Thanks,
Paul Lewis

**Comment by vincentbernat** [comment]
When compiling from source, you don't get an init script with this version of CentOS. You can use the one in `debian/lldpd.upstart` (to be put in `/etc/init/lldpd.conf`) or the one in `redhat/lldpd.init` (to be put in `/etc/init.d/lldpd`). They may not work out of the box depending on how you configured lldpd.

You can also use the RPM from opensuse. You need to install `lldpd-devel` package to get the missing `.h`.

**Comment by pl1m** [comment]
Thanks, I'll give the lldpd-dev package install a try and then try to build PTM again.

Thanks,
Paul

Sent from my iPhone

On Sep 19, 2015, at 9:17 AM, Vincent Bernat <notifications@github.com<mailto:notifications@github.com>> wrote:


When compiling from source, you don't get an init script with this version of CentOS. You can use the one in debian/lldpd.upstart (to be put in /etc/init/lldpd.conf) or the one in redhat/lldpd.init (to be put in /etc/init.d/lldpd). They may not work out of the box depending on how you configured lldpd.

You can also use the RPM from opensuse. You need to install lldpd-devel package to get the missing .h.

**Comment by pl1m** [comment]
Thank you, that was what I needed to build PTM.

Thanks,
Paul Lewis
