### ISSUE TITLE
Website: Update / reword the install section about the BSDs

### ISSUE THREAD

**Issue by matsimon** [vincentbernat/lldpd#140]
Hi Vincent

Now that NetBSD/pkgsrc, OpenBSD, DragonFly BSD (via FreeBSD) have the (most of the time) updated versions in their respective ports tree, it may be worth updating the section. Actually for a couple of BSD and architectures binary packages do exist.

Would you prefer to keep it as short as possible, or have a section per BSD?

I could provide a diff on that. Let me know what you'd prefer.

**Comment by vincentbernat** [comment]
Yes, the BSD section is quite out of date. I gladly take a diff (this the "website" branch). I don't mind having one section per BSD (althought saying "it's in the ports" should be OK for most users). Feel free to expand (like this is done for the Linux distros) if you can.

**Comment by matsimon** [comment]
Et voilà, I don't know if that's temporary, but when I force-updated the commit message it got referenced twice, hmm. Thanks in advance

**Comment by vincentbernat** [comment]
Thanks! I'll update the website shortly.
