### ISSUE TITLE
How can I see hostname in physical switch when I run lldpad on CentOS6.5?

### ISSUE THREAD

**Issue by changzhi1990** [vincentbernat/lldpd#144]
My machine runs "lldpad -d" service, and my machine is CentOS 6.5. But there is no hostname displays in physical switch. I want to get hostname by LLDP in switch so that I distinguish between many Linux machines.

**Comment by vincentbernat** [comment]
lldpad is another implementation of LLDP, distinct from lldpd. See http://open-lldp.org/
