### ISSUE TITLE
lldp-med

### ISSUE THREAD

**Issue by volga629** [vincentbernat/lldpd#145]
Hello Everyone,
Is possible configure lldp-med to have network profiles similar as cisco.
With network profile possible specify voice vlan information which can be pushed to the voip phone.

example
Switch(config-network-policy)# {voice | 
voice-signaling} vlan [vlan-id 
{cos cvalue | dscp dvalue}] | [[dot1p 
{cos cva lue | dscp dvalue}] | none | 
untagged]

**Comment by vincentbernat** [comment]
Yes. Look at the manual page of lldpcli and search for "network policy".

**Comment by volga629** [comment]
Thanks closing.
