### ISSUE TITLE
[Question] Printing to syslog while running in foreground

### ISSUE THREAD

**Issue by commodo** [vincentbernat/lldpd#146]
Hello,

I know this is not possible at the moment.

Reason we want this: `procd` (which is OpenWRT's process handler) spawns forks as a method of daemon-ization.
And it can open some pipes to the stdout and stderr of the fork.

However to print to syslog we've added a local patch in our OpenWRT tree to force print to syslog from lldpd, while it's running in the foreground.

With out patch we get something like
```
Thu Nov 26 17:55:11 2015 daemon.info lldpcli[5802]: iface-pattern set to new value (none)
Thu Nov 26 17:55:11 2015 daemon.info lldpcli[5802]: description set to new value (none)
Thu Nov 26 17:55:11 2015 daemon.info lldpcli[5809]: iface-pattern set to new value eth1
Thu Nov 26 17:55:11 2015 daemon.info lldpcli[5809]: chassis capabilities advertisement disabled
Thu Nov 26 17:55:11 2015 daemon.info lldpcli[5809]: management addresses advertisement disabled
Thu Nov 26 17:55:12 2015 daemon.info lldpcli[5810]: ask for global update
Thu Nov 26 17:55:12 2015 daemon.info lldpcli[5810]: immediate retransmission requested successfuly
```

With stderr/stdout redirection + procd we get:
```
Thu Nov 26 17:56:24 2015 daemon.err lldpd[9858]: 2015-11-26T15:56:24 [INFO/main] protocol LLDP enabled                                                                                        
Thu Nov 26 17:56:24 2015 daemon.err lldpd[9858]: 2015-11-26T15:56:24 [INFO/event] libevent 2.0.22-stable initialized with epoll method                                                        
Thu Nov 26 17:56:24 2015 daemon.err lldpd[9858]: 2015-11-26T15:56:24 [WARN/interfaces] error while receiving frame on eth2: Network is down                                                   
Thu Nov 26 17:56:24 2015 daemon.err lldpd[9858]: 2015-11-26T15:56:24 [WARN/interfaces] error while receiving frame on ifb0: Network is down                                                   
Thu Nov 26 17:56:24 2015 daemon.err lldpd[9858]: 2015-11-26T15:56:24 [WARN/interfaces] error while receiving frame on ifb1: Network is down                                                   
Thu Nov 26 17:56:24 2015 daemon.err lldpd[9858]: 2015-11-26T15:56:24 [WARN/interfaces] error while receiving frame on gretap0: Network is down                                                
Thu Nov 26 17:56:24 2015 daemon.err lldpd[9858]: 2015-11-26T17:56:24 [INFO/lldpctl] iface-pattern set to new value lan1,lan5,lan4,lan3,lan6,eth1,lan0,lan2,lan7                               
Thu Nov 26 17:56:24 2015 daemon.err lldpd[9858]: 2015-11-26T17:56:24 [INFO/lldpctl] chassis capabilities advertisement disabled                                                               
Thu Nov 26 17:56:24 2015 daemon.err lldpd[9858]: 2015-11-26T17:56:24 [INFO/lldpctl] management addresses advertisement disabled                                                               
Thu Nov 26 17:56:24 2015 daemon.err lldpd[9858]: 2015-11-26T17:56:24 [INFO/lldpctl] lldpd should resume operations
```

2 things are wrong with the procd stder/stdout redirection:
* all messages seem to have LOG_ERR log level message (I guess that may be procd's fault)
* `2015-11-26T17:56:24 [INFO/lldpctl] ` which is extra info from the console (that's lldpd)

Would it be an idea to run lldpd with -dddd (so 4 d) and make that redirect to syslog ?
Or do something like  (debug % 4)  and if debug > 3  redirect to syslog ?
I'm open to other proposals.
However I am not insisting upon this.
I can live with just keeping a custom patch to redirect lldpd messages to syslog.
I thought I'd ask for ideas/suggestions, since it's been on my todo-list for a while.

Thanks
Alex

**Comment by commodo** [comment]
Or maybe a [[force-]print-to-]syslog command line argument for lldpd ?
like  `lldpd -d -s` ?

**Comment by vincentbernat** [comment]
❦ 26 novembre 2015 08:54 -0800, Alexandru Ardelean <notifications@github.com> :

> Or maybe a [[force-]print-to-]syslog command line argument for lldpd ?
> like lldpd -d -s ?

Yes, this is unfortunate that debugging level is tied to being in
foreground while this is two different things. Would an additional argument to
not fork (-F?) solve the problem?
-- 
A is for Apple.
		-- Hester Pryne

**Comment by commodo** [comment]
Well, there is already `-d  Do not daemonize` that seems to do that
Would -F be any different ?

btw, I checked in 
* fprintf(sterr) will be pushed (to syslog) as LOG_ERR level
* fprintf(stout) will be pushed (to syslog) as LOG_INFO level

**Comment by vincentbernat** [comment]
Well, `-d` is both "don't daemonize" and "log to console + increase log level to console". A new flag could be introduced to just do "don't daemonize" but keep logging to syslog. Or a single `-d` could be used to not daemonize but still logging to syslog. Or your proposition to force log to syslog would work too (didn't see this when I first answered).

My current mood would say `-d` should stay in foreground but keep logging to syslog. This is a change for some people, but it's not like logs are lost. They'll just add an additional `-d` to recover the previous behaviour. And this can be introduced for the upcoming 0.8. This avoids addition of more and more flags.

The lldpcli stuff is a bit more work to ensure a coherent behaviour when run from lldpd. I could use an environment variable to let lldpcli knows he is run by lldpd and acts a bit differently (or an hidden flag).

**Comment by commodo** [comment]
That all sounds fine to me :)
As long as it's ok with you.

[Curious] When is 0.8 planned ?

**Comment by vincentbernat** [comment]
Really really soon. After fixing this issue I think.

**Comment by commodo** [comment]
Thanks :)

**Comment by vincentbernat** [comment]
BTW, has procd some notification mechanism to let it know when the spawned daemon is ready?

**Comment by commodo** [comment]
nope; don't think so;
procd seems to work as a simple shell (/bin/sh, /bin/bash ; that kind of shell ) ; 
it spawns a fork() for the process you want to run/daemonize, and then runs execvp() ; much like you're calling lldpcli from lldpd.
it can open a socket to read the stderr/stdout from the spawned process and redirect it to syslog
and it terminates the process via normal process interrupt/signal (like a shell) 
could be SIGTERM (or SIGCHLD) or something ; not sure here ; I did not dig too deep into it's code yet

the code is here:

**Comment by vincentbernat** [comment]
Thanks, I was just curious.
