### ISSUE TITLE
CIS-CAT gave warn message when user _lldpd uses /bin/false as shell 

### ISSUE THREAD

**Issue by luhuawang** [vincentbernat/lldpd#147]
This issue report is related with the file lldpd/redhat/lldpd.spec. 

The proposal is repace '/bin/false' with '/sbin/nologin' on lldpd.spec

Details:
CIS-CAT V3.0.04 gave following report for the host which installed lldpd
```
@ 7.2 Disable System Accounts
@ .
@ There are a number of accounts provided with the Red Hat that are used to
@ manage applications and are not intended to provide an interactive shell.
@ .
@ It is important to make sure that accounts that are not being used by regular
@ users are locked to prevent them from being used to provide an interactive
@ shell. By default, Red Hat sets the password field for these accounts to an
@ invalid string, but it is also recommended that the shell field in the
@ password file be set to /sbin/nologin. This prevents the account from
@ potentially being used to run any commands.
```

Default setting:
```
# cat /etc/passwd |grep -i lldp
_lldpd:x:102:103:LLDP daemon:/var/run/lldpd:/bin/false
```

Expected setting:
```
# cat /etc/passwd |grep -i lldp
_lldpd:x:102:103:LLDP daemon:/var/run/lldpd:/sbin/nologin
```

**Comment by vincentbernat** [comment]
I don't think there is much difference between /bin/false and /sbin/nologin (except the latest displays an informative message). But I agree that if `/sbin/nologin` is usually expected for disabled account, we should use it instead.

Please note that the change won't happen automatically on package upgrade. This would need some additional code and I don't think this is worth it (the additional code is more likely to trigger another bug).
