### ISSUE TITLE
groupadd failed to add lldpd_group as system group on redhat el 6.5 when ldap enabled

### ISSUE THREAD

**Issue by luhuawang** [vincentbernat/lldpd#149]
ISSUE:
When ldap enabled, groupadd failed to add lldpd_group as system group on redhat/oracle el6.5 

Proposal: 
Modify redhat/lldpd.spec with following logic for lldpd_group:
```
/usr/sbin/groupadd -r _lldpd || /usr/sbin/groupadd -r -K SYS_GID_MIN=101 _lldpd
```
For example,
```
# Create lldpd user/group
if getent group %lldpd_group >/dev/null 2>&1 ; then : ; else \
 ( %{_sbindir}/groupadd -r %lldpd_group > /dev/null 2>&1 || \
   %{_sbindir}/groupadd -r -K SYS_GID_MIN=101 %lldpd_group > /dev/null 2>&1 ) ||  exit 1 ; fi
if getent passwd %lldpd_user >/dev/null 2>&1 ; then : ; else \
 %{_sbindir}/useradd -g %lldpd_group -M -r -s /bin/false \
 -c "LLDP daemon" -d %lldpd_chroot %lldpd_user 2> /dev/null \
 || exit 1 ; fi
```

Details:
```
@ Steps to reproduce the bug:
@ ===========================
@ .
@ 1. Reimage a compute to redhat/oracle EL6.x, e.g. 6.5
@ .
@ [root@bejsblas01s06 ~]# cat /etc/oracle-release
@ Oracle Linux Server release 6.5
@ .
@ 2. Config the Oracle DSEE LDAP on the OL6.x
@ .
@ [root@bejsblas01s06 ~]# cat /etc/nsswitch.conf |grep ldap
@ passwd:     files ldap
@ shadow:     files ldap
@ group:      files ldap
@ netgroup:   files ldap
@ automount:  files ldap
@ .
@ 3. Test groupadd with "-r" option
@ .
@ [root@bejsblas01s06 ~]# /usr/sbin/groupadd -r  _lldpd
@ groupadd: Can't get unique system GID (no more available GIDs)
```
Analysis:
```
@ # rpm -qf /usr/sbin/groupadd      
@ shadow-utils-4.1.4.2-13.el6.x86_64
@ # rpm -qV shadow-utils-4.1.4.2-13.el6.x86_64
@ S.5....T.  c /etc/login.defs
@
@ I have gone through source code found routine find_new_gid.c searches the
@ available GID against local group file(/etc/group) and LDAP:
@ For system account, the search range is 101-499(default setting) in reverse
@ order, returns the highest unused GID.
@ .
@ I used command "getent group <id>" can find there is available
@ unused GID hence it does not make sense groupadd telling "no more available
@ GIDs".
@
@ One one test cause, the LDAP has id [201,300],[302,499] (don't contain 301). 
@ And the test failed.
@
@ Workaround
@ ===========================
@ /usr/sbin/groupadd -r _lldpd || /usr/sbin/groupadd -r -K SYS_GID_MIN=101
@ _lldpd
```

**Comment by vincentbernat** [comment]
Thanks for the detailed bug report!

I have looked a bit at existing RPM and didn't found any that is using this workaround. Notably, the Fedora page about how to handle groups and users don't tell anything about that:
 https://fedoraproject.org/wiki/Packaging:UsersAndGroups

Isn't the bug related to shadow-utils?

I am just worried to introduce some other bug when using `-K`.

**Comment by luhuawang** [comment]
Update:

Yes. it is related with shadow-utils. Reviewed the source package on redhat Enterprise Linux 6, shadow-utils-4.1.4.2-13.el6.src.rpm. The SYS_GID in EL 6 is from 201 to 500. (While on EL 5, the SYS_GID_MIN is 101)

'''
# head -17 SOURCES/shadow-4.1.4.2-redhat.patch
diff -up shadow-4.1.4.2/libmisc/find_new_gid.c.redhat shadow-4.1.4.2/libmisc/find_new_gid.c
--- shadow-4.1.4.2/libmisc/find_new_gid.c.redhat        2009-07-18 01:53:42.000000000 +0200
+++ shadow-4.1.4.2/libmisc/find_new_gid.c       2009-09-07 16:34:26.640814090 +0200
@@ -58,11 +58,11 @@ int find_new_gid (bool sys_group,
        assert (gid != NULL);

        if (!sys_group) {
-               gid_min = (gid_t) getdef_ulong ("GID_MIN", 1000UL);
+               gid_min = (gid_t) getdef_ulong ("GID_MIN", 500UL);
                gid_max = (gid_t) getdef_ulong ("GID_MAX", 60000UL);
        } else {
-               gid_min = (gid_t) getdef_ulong ("SYS_GID_MIN", 101UL);
-               gid_max = (gid_t) getdef_ulong ("GID_MIN", 1000UL) - 1;
+               gid_min = (gid_t) getdef_ulong ("SYS_GID_MIN", 201UL);
+               gid_max = (gid_t) getdef_ulong ("GID_MIN", 500UL) - 1;
                gid_max = (gid_t) getdef_ulong ("SYS_GID_MAX", (unsigned long) gid_max);
        }
'''

On my enterprise environment, all the uid from 199 to 500 has been used by LDAP. That is why lldpd failed on Enterprise Linux 6.x with following error message
'''
groupadd: Can't get unique system GID (no more available GIDs)
'''

The lldpd is able to be installed on Enterprise Linux 5.x that is because SYS_GID_MIN on EL 5 is 101.

Comparing with exiting coding on redhat/lldpd.spec, the proposal may be harmless.

Exiting coding:
'''
 %{_sbindir}/groupadd -r %lldpd_group > /dev/null 2>&1 || exit 1 
'''

Proposal:
'''
( %{_sbindir}/groupadd -r %lldpd_group > /dev/null 2>&1 || \
   %{_sbindir}/groupadd -r -K SYS_GID_MIN=101 %lldpd_group > /dev/null 2>&1 ) ||  exit 1
'''

**Comment by vincentbernat** [comment]
Your proposal means overriding a system policy or even a custom policy. If a user did set `SYS_GID_MIN` to 65501 for example, they may prefer an error than overriding their policy to 101 instead.

From what I understand, you should just override SYS_GID_MIN on your systems to 101 (by editing `/etc/login.defs`) since you will run into the same problem with every daemon that want to create a user.

**Comment by luhuawang** [comment]
Agree with you. Please close this issue.
