### ISSUE TITLE
[Discussion] lldpd reload

### ISSUE THREAD

**Issue by commodo** [vincentbernat/lldpd#153]
Firstly : Happy New Year !

This is not so much as a request, but rather just probing for ideas.

At the moment, on OpenWRT we're doing some simple reload (/etc/init.d/lldpd reload) ; something like :
* lldpcli pause
* lldpcli -c lldpd.unconf
* lldpcli -c /etc/lldpd.conf -c /etc/lldpd.d
* lldpcli resume
* lldpcli update

Note: lldpd.unconf is all of lldpcli's unconfigure commands listed in there.

I am pretty confident this works fine, since we've been using it for some time (couple of months now).
The only recent issue we've found, is that we need to pause and resume between unconfigure and configure.
Otherwise it can be racy and we send TLVs (or no TLVs) causing the other side to be confused or have duplicate info.

As I see it, going forward there are 2 ways to do it (more ideas are welcome):
1. implement a SIGUSR1/2 handler to lldpd which would cause it to re-read the config files
2. continue with the method we're using ; in that case, maybe lldpd could ship the lldpd.unconf file

I'm not insisting on anything.
Just: what are your thoughts on this ?
Maybe [i.e. not very soon] I'll take some time to implement whichever option is agreed upon.
reload (vs restart) is more of a sugar-feature for us right now.

Thanks
Alex

**Comment by vincentbernat** [comment]
❦  5 janvier 2016 04:46 -0800, Alexandru Ardelean <notifications@github.com> :

> This is not so much as a request, but rather just probing for ideas.
>
> At the moment, on OpenWRT we're doing some simple reload
> (/etc/init.d/lldpd reload) ; something like :
>
> * lldpcli pause 
> * lldpcli -c lldpd.unconf 
> * lldpcli -c /etc/lldpd.conf -c /etc/lldpd.d 
> * lldpcli resume 
> * lldpcli update 
>
> Note: lldpd.unconf is all of lldpcli's unconfigure commands listed in
> there.
>
> I am pretty confident this works fine, since we've been using it for
> some time (couple of months now).
> The only recent issue we've found, is that we need to pause and resume
> between unconfigure and configure.
> Otherwise it can be racy and we send TLVs (or no TLVs) causing the
> other side to be confused or have duplicate info.
>
> As I see it, going forward there are 2 ways to do it (more ideas are
> welcome):
> 1. implement a SIGUSR1/2 handler to lldpd which would cause it to
> re-read the config files
> 2. continue with the method we're using ; in that case, maybe lldpd
> could ship the lldpd.unconf file

Maybe a "reset factory" command would replace the .unconf
file. Otherwise, doing everything from lldpcli seems better than
shipping an unconfigure file (which may go out-of-date).
-- 
Indent to show the logical structure of a program.
            - The Elements of Programming Style (Kernighan & Plauger)

**Comment by commodo** [comment]
The "reset factory" command sounds interesting.
So, something like
```
lldpcli reset
```
?

**Comment by vincentbernat** [comment]
Yes, that would be fine. And it should be "easy" to implement.

**Comment by commodo** [comment]
Will close issue.
Will come back with a PR when ready.

**Comment by commodo** [comment]
a design question on this:

which method would you prefer on this ?
# add a `reset` bool/int flag on the SET_CONFIG call and then lldpd daemon handles reset internally ?
# The `lldpcli reset` command conjures up all the unconfigure commands into one and sends them to lldpd ?

**Comment by commodo** [comment]
i goof'ed the formatting on the first message ; i am getting confused between mark-ups and mark-downs

**Comment by vincentbernat** [comment]
A `reset` flag. While I try to push many things to the client, I think that resetting is easier to do in the daemon, all the more than some commands may not have a way to unconfigure.

**Comment by dbugnar** [comment]
The daemon looks a bit big. Where the reset command should be placed in daemon? In lldpd.c?

**Comment by vincentbernat** [comment]
Yes, this file has grown a lot. This could be put in `client.c` too if you don't need any static function from `lldpd.c`.
