### ISSUE TITLE
Request: Allow hostname (as well as FQDN) for chassis info

### ISSUE THREAD

**Issue by joelio** [vincentbernat/lldpd#154]
Hi,

I was wondering if it would be simple to implement just setting the hostname, rather than the FQDN name for the local chassis system info. When viewing some switch consoles, having an FQDN can cause some strange linewrap issues and makes using the provided search quite difficult as there's no multiline grep style support.

Apologies if this is already there, I couldn't see it. I have set via some automation hooks for our estate, but if would be handy if there was a configurable to set this via the tool!

Many thanks!
Joel

**Comment by vincentbernat** [comment]
Yes, it should be simple enough to add a configuration option for that. I'll release 0.9 first before adding such a feature.

**Comment by jrosser** [comment]
+1 for this, option to shorten the system name to just the hostname would tidy up "show cdp neighbors" greatly.

Thanks,
Jon.

**Comment by vincentbernat** [comment]
Sorry for the delay, I let this one slipped while it was pretty easy to implement. Could you confirm that "uname -n" gives the name you want or do you expect lldpd to shorten it?
