### ISSUE TITLE
How to add -lsqlite3 option into makefile

### ISSUE THREAD

**Issue by topsecret9x** [vincentbernat/lldpd#155]
Hi, 

My name is Slar, I'm a student, now I'm using your program in my project at school.
I want to test a function by adding into lldp.c in /src/daemon/, it will get input data from SQLite3 database, then output it. But there is always a problem that "undefined function sqlite3_open" when using "make" after "./configure". I think this problem happens because I can't using "-lsqlite3" option when compiling lldp.c file. 
I want to add "-lsqlite3" into your makefile to solve my problem, but I don't know it's legal or not?
If it's legal, could you give me some advice to do that? I really appreciate that.
Your program is really great, it's quite usefull for my project. 
Sorry for my bad English.
Thank you so much for your time.

Best regards,

**Comment by vincentbernat** [comment]
You can add it to `Makefile.am`, on the same line as `AM_LDFLAGS`. You need to run `./autogen.sh` after that.

**Comment by topsecret9x** [comment]
Thank you so much for your reply. I can do it now :+1:
