### ISSUE TITLE
Multithread liblldpctl access

### ISSUE THREAD

**Issue by mino98** [vincentbernat/lldpd#157]
Hello,
I wrote a small application with two threads, each of which opens its own `liblldpctl` connection:
````
const char *ctlname = lldpctl_get_default_transport();
lldpctl_conn_t *conn = lldpctl_new_name(ctlname, NULL, NULL, NULL);
````

Then, one thread is looking out for changes with the two:
````
lldpctl_watch_callback(conn, watchcb, NULL)
...
lldpctl_watch(conn)
````

The other thread just does some `lldpctl_get_interfaces(conn)` once every few minutes in a loop. 

In both threads I'm "dereferencing" everything that I use. Everything compiles and works fine, except that after a while the application crashes and in syslog I read:
````
LLDPD-WARNING[4522]: message received is too large
````

From `lib/lldpctl.h` I see that multiple access to `lldpd` shouldn't be a problem: 
````
    * The library is expected to be reentrant and therefore thread-safe. It is
    * however not expected that a connection to be used in several thread
    * simultaneously. This also applies to the different pieces of information
    * gathered through this connection. Several connection to lldpd can be used
    * simultaneously.
````

Am I missing anything? 

Thanks!

**Comment by vincentbernat** [comment]
Which version are you using?

I don't see any flaw in the way you do things and it should work as you expect. What kind of crash do you get? Is it a segfault? Is it always the same thread that is crashing?

**Comment by mino98** [comment]
Hi Vincent, I'm using 0.7.12 at the moment (I cannot upgrade easily, but I will if this is causing the issue).

I have that crash only when I run my application as a daemon, it doesn't seem to happen when in foreground for some unknown reason. My application seems to exit without generating any coredump and at the same time LLDP logs that `message received is too large` message. 

I'll try adding more debug in my application. Any other idea in the meanwhile?

**Comment by vincentbernat** [comment]
I don't see anything that should matter about this in the list of changes.

Does you crash happen if you make only one thread run?

**Comment by mino98** [comment]
No, it does not run with a single thread (either of them). It seems to be 100% reproducible. Is it possible that I'm not dereferencing an atom and this is causing it to fail? 

The only place where I may not be dereferencing is at something like:
````
lldpctl_atom_foreach(interfaces, interface) { ... }
````
After the cycle it is enough to deference
````
lldpctl_atom_dec_ref(interfaces);
````
and I don't need to:
````
lldpctl_atom_dec_ref(interface);
````
right?

**Comment by mino98** [comment]
I think I may have found the issue. At the end of my watch callback, I was doing a deref of  `interface` and `neighbor` as follows:
````
static void watchcb(lldpctl_conn_t *conn, lldpctl_change_t type, lldpctl_atom_t *interface, 
                    lldpctl_atom_t *neighbor, void *data) {

    //...
    lldpctl_atom_dec_ref(neighbor);
    lldpctl_atom_dec_ref(interface);
}
````

I've removed that and it seems not to crash anymore. Why is that?

**Comment by vincentbernat** [comment]
Yes, the foreach macro will deref the atom it iterates over for you: https://github.com/vincentbernat/lldpd/blob/master/src/lib/lldpctl.h#L1018-L1022

As for the watch callback, it will also do the deref for you (since it did provide the arguments). Maybe I should find a way to make the doc clearer about what should be derefed or not. The semantic is similar to Python. Since the memory is freed immediately when deref count reach 0, it's not possible to print a sensitive error message when you deref too much.

I suppose that you get some memory corruption, but I don't explain the "too large" error that you get. If your program is not too big, you should try to run it with valgrind. It's quite useful to catch those kind of errors.

**Comment by mino98** [comment]
Indeed it was due to my deref of the arguments of the watch callback. It makes sense *not* to do it, as you say, but it may also be a good idea to clarify it in the docs.

I went a bit further into the "too large" message: it indeed seems cause by memory corruption, as hdr.len seems to contain random garbage and fails to compare with "< HMSG_MAX_SIZE".

Thanks again for this great project Vincent! :)

**Comment by vincentbernat** [comment]
No problem! I just pushed a slight update of the documentation about reference counting. Dunno if it's better than it was. ;-)
