### ISSUE TITLE
custom TLVs not sent after link bounce

### ISSUE THREAD

**Issue by kkrajewsavaya** [vincentbernat/lldpd#158]
When generating custom TLVs using the lldpcli "configure lldp custom-tlv" command, the custom TLVs are initially sent as configured after the standard TLVs.  If the link is disconnected and then reconnected, the standard TLVs are sent but the custom TLVs are not.  If the same lldpcli commands are re-issued then the custom TLVs are once again sent.  (Version 7.19)

**Comment by vincentbernat** [comment]
Unfortunately, once a port goes down, all custom attached information attached to it is lost. This is fixed in 0.9.0, released a few weeks ago.

**Comment by vincentbernat** [comment]
Will not be fixed in 0.7 branch. Switch to 0.9 if it's important.
