### ISSUE TITLE
Mac OS X package link is down, gives a 404

### ISSUE THREAD

**Issue by melikyuksel** [vincentbernat/lldpd#159]
http://media.luffy.cx/files/lldpd/lldpd-0.9.0.pkg

No longer working!

**Comment by vincentbernat** [comment]
Unfortunately, I still have some trouble to generate OS X packages, so it lags a bit. The site automatically put a link to the latest version, even if it doesn't exist. The latest version for OS X is http://media.luffy.cx/files/lldpd/lldpd-0.7.19.pkg.

I have a 0.9 almost ready but I am only able to compile it for El Capitan. I need to fetch an older SDK to make something more universal.

**Comment by melikyuksel** [comment]
Ah, I see. The 0.7.19 doesn't work on El Capitan anyway, so it's not much of a loss to even have the link up.

**Comment by vincentbernat** [comment]
I just pushed lldpd 0.9.1 for OSX. Should work from OSX 10.9. Tested on 10.11 only.
