### ISSUE TITLE
handling custom TLV duplicates

### ISSUE THREAD

**Issue by kanrajag** [vincentbernat/lldpd#162]
Hi
With 0.9.0, user has the ability to create a custom-tlv. But if user tries to modify the oui-info, then a new instance of the custom-tlv is created instead of over-writing the existing. This happens even when a new custom-tlv is received on an interface.

Can custom-tlv be unique per oui+sub_type ? is there a reason to allow multiple TLVs having the same "oui+sub_type" ?

**Comment by vincentbernat** [comment]
@commodo do you have an opinion about this?

**Comment by commodo** [comment]
Hello,

Sorry about the long text.

I wanted to reply to this earlier, but decided to wait until reading the IEEE 802.1AB document a bit.
I will first admit, I am not entirely clear on what the document enforces and whether the current custom TLVs implementation in lldpd is entirely according to the spec.

There are some cases in the LLDP spec (example Annex F, sections 3 and 4), where it says how to handle cases of multiple instances of a subtype + OUI.

Annex F.3.3.a
> Port And Protocol VLAN ID TLVs are subject to the following rules:
>      a) If more than one Port And Protocol VLAN ID TLV is defined for a port, the PPVID value shall be
>          different from any other PPVID defined for the port.

Annex F.4.4
> F.4.5 VLAN Name TLV usage rules
>   If more than one VLAN Name TLV is defined for a port, the VLAN ID and the associated VLAN name
>   combination shall be different from any other VLAN ID and VLAN name combination defined for the port.

These TLVs have the same OUI (00-80-C2), and Annex F.3 describes subtype 2 (Port And Protocol VLAN ID TLV) and Annex F.4 describes subtype 3 (VLAN Name TLV)

Then in section 9.6.2 Organizationally Specific TLV usage rules:
> The Organizationally Specific TLV usage rules should include:
> a) The number of Organizationally Specific TLVs that may be contained in an LLDPDU and any
>     additional information field subtypes that would identify differences between two TLVs with the
>     same OUI and organizationally defined subtype (for example, see F.3.3 a).

If I am understanding this correctly, this means that each implementer (or organization) of it's own specific TLVs should define the number of the same subtype, or how to handle the same subtype being present.

As far as I can tell, lldpd does that fine.

In our case don't use more than OUI+subtype yet; we've discussed internally about it, but we did not find a case yet where we would need it.
This may change later as our organization grows.

The way that we use custom TLVs, is that we clear the custom TLVs and we re-apply all (custom TLVS) and other lldpd configuration.
I was thinking of implementing a `lldpcli unconfigure custom-tlv oui 00,11,22 subtype X` which would only unconfigure certain subtypes.
But that's another story. 

I think that there could be other cases (same as the ones in Annex F) where the same subtype+OUI could be used.
So, it should be up to the organization/implementer of those subtypes to control that.

We use another daemon that queries lldpd for our custom TLVs, and in that daemon we control all the logic of where those TLVs are valid, or whether the number of TLVs is valid and so on.

I hope this answers the initial questions.

Thanks
Alex

**Comment by vincentbernat** [comment]
So, the best way would be to have a `add` or `replace` keyword to override the default behavior when submitting a custom TLV.

**Comment by kanrajag** [comment]
@commodo - thanks for the reply. In your case, since you expect only one instance of your OUI+subtype TLV, you get around the current design by unconfiguring ALL custom-tlv and then re-applying it ?
The problem with that approach is that un-configuring will cause LLDPD to send out the TLV again without the custom-tlvs at all (via levent_update_now). This will incorrectly indicate to the neighbor that the TLV is not present and it might take un-expected action? unless you are pausing LLDPD during this time..

I like Vincent proposal of using the "add" or "replace" keyword (default could be "add" to keep existing behavior the same). this allows for LLDPD to apply a new config in an atomic fashion and update the neighbor properly

**Comment by commodo** [comment]
I also like the add + replace keyword approach.
I don't mind which behavior is default ; since custom TLVs in lldpd are fairly new, and it won't affect our case.

@kanrajag : yes, we do the unconfiguring of all custom TLVs with a pause ; so:
pause
unconfigure lldpd (custom TLVs and all)
load configuration again
resume

During pause and resume, lldpd will not broadcast anything.

This method is a bit overkill, but the idea (for us in the beginning) was to keep things simple and improve in small iterations.

**Comment by vincentbernat** [comment]
To be continued in #163.
