### ISSUE TITLE
Implement a blacklist for drivers with opt-out

### ISSUE THREAD

**Issue by kanrajag** [vincentbernat/lldpd#164]
Hi
After commit (9e78f3a69b9328f21483ba6751c92eda6e73b781), we are not able to distinguish certain virtual interfaces and we end up sending LLDP packets over them. I was thinking we could use "qdisc" (via IFLA_QDISC) to distinguish virtual devices?

if qdisc=="noqueue", then we can be sure its a virtual device, since that is not available for physical devices (look up http://linux-tc-notes.sourceforge.net/tc/doc/sch_noqueue.txt)

this solves the problem in our setups.

**Comment by vincentbernat** [comment]
Unfortunately, `noqueue` is also used for interfaces like veth or macvlan.

You could revert commit a2eb343 and add the appropriate drivers to blacklist to the list of blacklisted drivers.

**Comment by kanrajag** [comment]
ok. i just added the blacklist drivers code and made specific check for "vxlan".. you can close this issue

**Comment by vincentbernat** [comment]
This could be made configurable. On one hand, vxlan and macvlan are usually used only in multipoint and it makes little sense to run LLDP over them but on the other, someone could use them as point to point and expect lldpd to use them as regular interfaces (so, they cannot be just be blacklisted without an opt-out).

I'll leave this bug and rename it to implement blacklist with opt-out.

**Comment by vincentbernat** [comment]
In aed5788058eb, I specifically ignore VXLAN interfaces. There is no opt-out of this yet. If people complain about that, I'll add a opt out. As this meets your requirement, I'll close this issue for now. People, feel free to reopen if you need to have LLDP over VXLAN.
