### ISSUE TITLE
How to enable LLDP to support in ieee802.15.4 network

### ISSUE THREAD

**Issue by zmingshi** [vincentbernat/lldpd#165]
Hi,
   If there is any way to enable LLDP to support ieee802.15.4? That is, LLDPDU could be transmitted in a non-Ethernet data link layer, and LLDP protocol can support ieee802.15.4 device discovery (e.g. 6lowpan). 
   If an encapsulation protocol (e.g. GRE) for LLDPDU frame is feasible?

Thanks very much for any help!

**Comment by vincentbernat** [comment]
Hi!

Is it the same issue as #72?

**Comment by zmingshi** [comment]
Hi,
Sorry for the late reply. I think the issue may be different. I have read the issue actually. 
In my case, I'm doing an experiment about ieee802.15.4 device discovery. In more detail, I have two modules supporting ieee802.15.4 and 6lowpan, each module is hooked up with a Raspberry Pi. Also, I have installed lldpd (v0.7.19) on the two Raspberry Pis. My objective is to hope lldpd could monitor wpan interface or 6lowpan interface, and hope 'show neighbor' command could show the detailed interface information.
A referred material suggests that: **for the data link layer that cannot directly transmit an Ethernet frame including the LLDPDU (e.g. 802.15.4), the Ethernet frame may be transferred using an encapsulation protocol over the IP**. There, GRE is suggested for encapsulation, the protocol type for GRE is 0x6558.
I tried to create a GRE tunnel via Linux command 'sudo ip link add ip6gre1 type ip6gretap remote ff02::1 local fd2d:388:6b7a:2::1', but it seems not work. 
Do you have any suggestions for creating such a GRE tunnel or about how to make LLDP monitor such interface? Thank you very much for any suggestion!
Best Regards!

**Comment by vincentbernat** [comment]
What's the output of `ip l l` for the ieee802.15.4 interface?

**Comment by zmingshi** [comment]
Below is the output of 'ip l l',
![image](https://cloud.githubusercontent.com/assets/4213535/13390745/385bf838-df0b-11e5-8ac7-b1508bf53536.png)
There, wpan0 is the ieee802.15.4 interface.
Thanks!

**Comment by vincentbernat** [comment]
The way I see it, lldpd could:

 1. Detect non-Ethernet interfaces
 2. Encapsulate LLDP frames into GRE datagrams (without any help from the kernel)
 3. Be able to receive such frames

For 1, we could have a whitelist of interfaces we want to handle. What's the result of `ethtool -i wpan0`?

For 2, the GRE part seems easy enough. However, I have no idea which destination IP to use. Is it multicast, is it broadcast? Having another implementation that already does something similar would help.

For 3, this should be easy once we figured out how to do 2.

**Comment by zmingshi** [comment]
Hi,
Yeah, I think your understanding is right!
For 1, I tried the command 'ethtool -i wpan0', the result shows:
![image](https://cloud.githubusercontent.com/assets/4213535/13415689/be0a5934-df97-11e5-95a1-a5a580abb73d.png)
That's easy to be understood, since ethtool is used for Ethernet devices.
Also, what do you mean by saying **we could have a whitelist of interfaces we want to handle** for detecting non-Ethernet interfaces? If the such whitelist configuration (
![image](https://cloud.githubusercontent.com/assets/4213535/13416318/90d1f5ee-df9c-11e5-854f-21fce63ddc43.png)
) is to make sure lldpd could listen and send LLDPDU to the interface?

For 2, the destination IP address of GRE packet is the multicast address for all nodes on the local link (ff02::1) for IPv6. As for the GRE part, I have tried to create such tunnel based on the link [http://benoit.papillault.free.fr/blog/?p=54](url), the difference from the referred link is that the tunnel type for my case is 'ip6gretap'. The tunnel name I created is 'ip6gre1', the ip6gre1 link information is below:
![image](https://cloud.githubusercontent.com/assets/4213535/13417115/b9e9ffc4-dfa3-11e5-9ef8-7d7d02defcde.png)
when I use lldpd to monitor ip6gre1, the result 'show sta' shows below:
![image](https://cloud.githubusercontent.com/assets/4213535/13417773/cd8d4b0c-dfa9-11e5-92f0-4327747a15d6.png)
It shows that received packets are 0. Then I use wireshark to capture transmitted packets, it shows 
![image](https://cloud.githubusercontent.com/assets/4213535/13417900/091a0dbc-dfab-11e5-908f-b5e98e585e59.png), which shows LLDPDU isn't encapsulated by GRE.
I think if the GRE is correctly configured, then the protocols in captured packets maybe look like [protocols in the frame: wpan:6lowpan:ipv6:gre:eth:lldp], that's right?
Thanks!

**Comment by vincentbernat** [comment]
If you do the GRE tunnel yourself, it should just work but I don't think that's how LLDP over GRE should work. I think that LLDP over GRE is sending LLDP frames encapsulated into GRE without Ethernet encapsulation.

I just tested to run the same GRE tunnel as you did configure and it works just fine for me. I see that lldpd is sending LLDPDU inside the GRE tunnel. In Wireshark, if you capture directly on the GRE interface, it is expected to get only `eth:lldp`.

On each side, use `tcpdump -pni ip6gre1` and check that you get LLDP frames:

```
07:30:35.378726 LLDP, length 205: neo.luffy.cx
```

**Comment by zmingshi** [comment]
I also get the similar result using `tcpdump -pni ip6gre1`, and I also think such configure seems not correct.

Your saying "LLDP over GRE is sending LLDP frames encapsulated into GRE without Ethernet encapsulation" means I should add some code into lldpd (lldpd.h ?) for encapsulating LLDPDU into GRE, right?

**Comment by vincentbernat** [comment]
For your second paragraph, yes.

For the first one, do you get the same result on both sides? Do you see the LLDPU emitted by the other side?

**Comment by zmingshi** [comment]
Yes, I get the similar result on both sides, and the LLDPDU is indeed emitted by the other side

**Comment by vincentbernat** [comment]
If you run lldpd on one side, you don't see anything on the other side, right? So, it is mostly a problem with the GRE tunnel not working. If you run `tcpdump -pni wpan0 proto gre`, do you see anything?

**Comment by commodo** [comment]
[ so a bit from me ; sorry to barge in ]
Just a quick question: but why would LLDP need to work on top of GRE ?
From what I know, GRE is an L2 encapsulation over IP (L3). 
And LLDP is an L2 proto (LL == Link Layer) ; so, encapsulation over GRE is kind of defeating the point of LLDP ?

Maybe it would be an idea to make lldpd work on top of 802.15.4 physical links.
I did not check the IEEE spec for LLDP regarding what kind of link-types it should support or not.
But I think maybe lldpd could focus more of physical links than GRE (or GRE-type) tunnels.

**Comment by zmingshi** [comment]
For the first question - yes, I can't see anything on other side.
When I run the command `tcpdump -pni wpan0 proto gre`, it shows that 
![image](https://cloud.githubusercontent.com/assets/4213535/13421339/bb81defe-dfc8-11e5-9a9b-c044d11f4c70.png)

**Comment by vincentbernat** [comment]
@commodo You are right. But when LLDP must run on top of non Ethernet links, it's usual for specs to just say "use GRE". I think the point is not make the user setup a GRE tunnel but make the implementation encapsulate the LLPDU into a GRE packet (GRE header with ether type of `0x88cc` + LLDPDU). But this needs some code in `lldpd` and it would be great if there was some confirmation that there really exists implementations doing that.

The "trying to make LLDP work inside an Ethernet GRE tunnel" is just a temporary workaround for @zmingshi.

**Comment by vincentbernat** [comment]
@zmingshi I think this is just your GRE tunnel which is not working. You can test that by adding an IP on both side on the tunnel (`ip addr add 192.168.15.1/24 dev ip6gre1` and `ip addr add 192.168.15.2/24 dev ip6gre1` on the other side) and check that you can't ping `192.168.15.2`.

**Comment by commodo** [comment]
@vincentbernat oh, alright ; wasn't aware of this ; we use `lldpd` on eth links.
Thanks for the clarification.

**Comment by zmingshi** [comment]
@vincentbernat Yes, I have added an IP address on both sides on tunnel, and I can't ping

**Comment by zmingshi** [comment]
So, you mean the GRE tunnel type 'ip6gretap' is not suitable for my case, right? 
I found it in the link [http://www.dsm.fordham.edu/cgi-bin/man-cgi.pl?topic=IP-LINK&ampsect=8](url), in this man page, it shows `ip6gretap  - Virtual L2 tunnel interface GRE over IPv6`. Maybe I misunderstood it.

**Comment by vincentbernat** [comment]
No, it's suitable but the way you configured it makes it doesn't work. Are you sure you can use a multicast address as a remote address?

**Comment by zmingshi** [comment]
I'm not sure, the multicast address will affect the tunnel? I will have a try to replace the multicast address with an unicast address

**Comment by vincentbernat** [comment]
Yes, I don't think that GRE has any provision to listen to multicast packets.

**Comment by zmingshi** [comment]
It is ok now, the LLDPDU can be received by other side. When I configure the IP address, they can ping successfully! Thank you very much!
So, by the configuration, LLDPDU frame is encapsulated into GRE, right?

Another question: why the capabilities in the virtual interface is as below:
![image](https://cloud.githubusercontent.com/assets/4213535/13422447/dbf47438-dfcf-11e5-9ae0-156a67e0f611.png)
I can't see anything about wpan interface information by command `show neighbor`.

**Comment by vincentbernat** [comment]
Yes, the LLDPDU frame is encapsulated into an Ethernet frame which is encapsulated in GRE. However, you have to configure manually a GRE tunnel between neighbors, so it defeats a bit the discovery part.

For the capabilities: you have no bridge enabled, you don't have IP forwarding enabled, you have some wireless interfaces (I suppose "iw" see the WPAN interface).

You won't see anything about the wpan interface as a neighbor as the neighbor is the GRE interface.

**Comment by zmingshi** [comment]
Why do you think LLDPDU frame is first encapsulated into an Ethernet frame? In my opinion, LLDPDU frame itself is an Ethernet frame, after the tunnel configuration, the Ethernet frame is then encapsulated in GRE.

For the capabilities: I understand it, thank you!

For the wpan interface: If I want to find the wpan interface, then I will need to add some code to lldpd, right?

**Comment by vincentbernat** [comment]
Well, that's semantics. I think that if lldpd was transmitting itself the LLDPDU over GRE, it would be (over the wire):

 - GRE header, with ethertype of 0x88cc
 - LLDP TLVs

Here, you have:

 - GRE header, with ethertype of 0x6558 (Ethernet bridging)
 - Ethernet destination, source, ethertype of 0x88cc
 - LLDP TLVs

For your last question, right. Finding another implementation that already uses GRE would help to know what should be done.

**Comment by zmingshi** [comment]
ok, I understand it, thank you very much for your kind help!

**Comment by xwqian** [comment]
Hi, @vincentbernat 

I see the LLDP could be used to non-Ethernet data link by configuring GRE tunnel.
But, is it easy to realize this feature without GRE tunnel?

To be able to realize this feature, I think the following issues should be fixed:
1. lldpd should be able to identify wpan interface (take 802.15.4 for example)
2. lldpd should be able to obtain information of wpan interface, e.g. mac address (64-bit)
3. lldpd should be able to put information of wpan into LLDPDU
4. lldpd should be able to transmit LLDPDU over non-Ethernet link

Do you have idea for the implementation? Thank you very much!

**Comment by vincentbernat** [comment]
The main question remains the format of the LLDPDU. Do you have another implementation of LLDP that is sending LLDPDU over a wpan interface? If yes, capture one of those LLDPDU to see how they are done.

**Comment by xwqian** [comment]
Hi, @vincentbernat 
Sorry, so late to reply.
I haven't found any implementation of LLDP over the wpan interface. But, I think the main difference for wpan interface from other common interface like wlan is the length of mac address, maybe the length of mac address can be specified in certain field of LLDPDU, right?
If you think LLDPDU for wpan is not the usual case of 802.1AB, maybe the LLDPDU for wpan can be stored in TLVs of which the TLV Type is 127, right?

The main TLVs for wpan interface I want to implement is the End_Of_LLDPDU TLV, Chassis_ID TLV, Port_ID TLV, Time_to_Live TLV and Port_Description TLV, I also hope customized TLVs could be created over wpan interface.

**Comment by vincentbernat** [comment]
There shouldn't be a problem with the LLDPDU itself. However, the LLDPDU needs to be encapsulated in a 802.15.4 frame. My supposition is that it should be encapsulated in a GRE packet (so, lldpd should build a GRE packet, encapsulates it in an IP packet, encapsulates it in a 802.15.4 MAC packet or maybe just leave the last part to the OS). But maybe this should be sent directly in a 802.15.4 payload. In all cases, I need to know the destination/source MAC addresses (and in case of GRE, destination/source addresses and when not GRE, all other fields for the MAC header).

**Comment by xwqian** [comment]
I use the solution (configure GRE with ip tools) mentioned at the start of this issue, the captured lldp packet is as below:
![image](https://cloud.githubusercontent.com/assets/23471632/21604656/61308c70-d1df-11e6-8b73-1542096340b7.png)
The dst/src address for GRE tunnel is generated by OS automatically when creating GRE interface
The src address for LLDPDU is the address of GRE interface
If this could help you?

**Comment by vincentbernat** [comment]
GRE can encapsulate LLDP directly, so I don't need the Ethernet II part. However, I need to decide on the other information. This leaves a lot of choices. Ideally, I think the GRE tunnel should be point to multipoint with a multicast destination. Dunno which address should be used. Without some documentation or an existing implementation (from a constructor or someone which is part of some IEEE working group), I cannot do much. I do not want a custom implementation that would only work with lldpd (people would rely on it and if the implementation is wrong, it will be painful to correct it).
