### ISSUE TITLE
lldpd with agentX flood syslog

### ISSUE THREAD

**Issue by Alucardfh** [vincentbernat/lldpd#166]
HI,

I have a large amount of message like (every 15 seconds): 
lldpd[39703]: AgentX session to master agent attempted to be re-opened.

Although everything seems to work fine even on the snmp polling side.

Is there a way of either get rid of the message or to reduce the logging level.

Thanks

**Comment by vincentbernat** [comment]
The message is an indication of something going wrong. I think you should find the cause. The message itself comes from libsnmp and would be difficult to remove. If you can attach a debugger to lldpd, you could place a breakpoint on `subagent_open_master_session` and check why it is called.

**Comment by vincentbernat** [comment]
Also, please, provide your version of lldpd and libsnmp.

**Comment by Alucardfh** [comment]
The version of lldpd and snmp I am using are below.

# lldpd -v
0.9.0

# rpm -qa | grep snmp
net-snmp-libs-5.7.1-31.3.x86_64
net-snmp-perl-5.7.1-31.3.x86_64
net-snmp-5.7.1-31.3.x86_64
net-snmp-agent-libs-5.7.1-31.3.x86_64
net-snmp-utils-5.7.1-31.3.x86_64


I am not versed in debugging C code and my attempt wasn't very conclusive.
Here is what I tried : 

# ps aux | grep lldp
root     12335  0.0  0.0 107696  1912 ?        Ss   13:23   0:00 /usr/local/sbin/lldpd -x
_lldpd   12353  0.0  0.0 106080  3884 ?        S    13:23   0:00 /usr/local/sbin/lldpd -x

#gdb -p 12353
[...]
(gdb) break subagent_open_master_session
Breakpoint 1 at 0x2aaaaaafbab0
(gdb) continue
Continuing.

Breakpoint 1, 0x00002aaaaaafbab0 in subagent_open_master_session () from /usr/lib64/libnetsnmpagent.so.30
(gdb) n
Single stepping until exit from function subagent_open_master_session,
which has no line number information.
0x00002aaaaaafbff1 in ?? () from /usr/lib64/libnetsnmpagent.so.30
(gdb) n
Cannot find bounds of current function
(gdb) n
Cannot find bounds of current function
(gdb)

**Comment by vincentbernat** [comment]
You almost did it. Use "bt" in `gdb`. If symbols are missing, you should try to install the debug packages for NetSNMP. Note that attaching the debugger stops the program, so to check that it's not the reason for the first reconnect, I would do `continue` until the program run uninterrupted for 10-15 seconds (you can enter `continue` once and repeat with just "enter"). Then, use "bt".

**Comment by vincentbernat** [comment]
Also, do you know if snmpd is configured to connect through a Unix socket or a TCP connection? `lsof -n -p $(pidof snmpd)` should tell if it's listening on an Unix socket (like `/var/agentx/master`) or TCP (port 705 if I remember correctly).

**Comment by Alucardfh** [comment]
Ok I'll need to install the debug packages for snmp as the trace doesn't look really interesting : 

(gdb) break subagent_open_master_session
Breakpoint 1 at 0x2aaaaaafbab0
(gdb) continue
Continuing.

Breakpoint 1, 0x00002aaaaaafbab0 in subagent_open_master_session () from /usr/lib64/libnetsnmpagent.so.30
(gdb) bt
#0  0x00002aaaaaafbab0 in subagent_open_master_session () from /usr/lib64/libnetsnmpagent.so.30
#1  0x00002aaaaaafbff1 in ?? () from /usr/lib64/libnetsnmpagent.so.30
#2  0x00000037066726fb in run_alarms () from /usr/lib64/libnetsnmp.so.30
#3  0x00000000004232a6 in levent_snmp_timeout (fd=<value optimized out>, what=<value optimized out>, arg=0x64f220) at ../../../src/daemon/event.c:112
#4  0x00000000004272c3 in event_process_active_single_queue (base=0x64f640, flags=1) at ../../libevent/event.c:1368
#5  event_process_active (base=0x64f640, flags=1) at ../../libevent/event.c:1438
#6  event_base_loop (base=0x64f640, flags=1) at ../../libevent/event.c:1639
#7  0x00000000004231d8 in levent_loop (cfg=0x64f220) at ../../../src/daemon/event.c:578
#8  0x000000000040c00b in lldpd_main (argc=<value optimized out>, argv=<value optimized out>, envp=<value optimized out>) at ../../../src/daemon/lldpd.c:1833
#9  0x000000303e61ecdd in __libc_start_main () from /lib64/libc.so.6
#10 0x0000000000409e79 in _start ()
(gdb)


Snmp is using the Unix socket /var/agentx/master

I'll try to install de missing packages on Tuesday.

Thanks for your help

**Comment by vincentbernat** [comment]
Yes, it would be easier if we know what the missing function is. I can also try to reproduce on my side. You are running on RHEL 7 or Fedora? In thise case, is SELinux enabled? Maybe there is something in the audit log then.

**Comment by Alucardfh** [comment]
It is a Centos 6.2 with snmp upgraded to 5.7.
Selinux is disabled.

Which honestly might be entirely the reason for the issue.

**Comment by vincentbernat** [comment]
How did you upgrade to 5.7? It's just to try to reproduce. I am not that familiar with CentOS.

**Comment by Alucardfh** [comment]
Hi Vincent,

I upgraded to 5.7 by getting the RPMs from Centos 6.7.
I then compiled lldpd.

I am not sure of what happened but restarting snmpd and lldpd seem to have cleared the issue.

Nonetheless I believe the issue lie in my particular setup and not with lldpd as it has been deployed on about 500 servers and only a handful had the issue.

I think you can close this issue.

Thanks for you time

**Comment by vincentbernat** [comment]
OK, let's close. Reopen if this happens again.
