### ISSUE TITLE
change destination mac in lldpd

### ISSUE THREAD

**Issue by athreyaDell** [vincentbernat/lldpd#171]
This is not an issue and something that I am looking for: I was able to install lldpd in 2 qemu which run on a single VM(cent os) via a linux bridge. For obvious reasons the bridge wont forward these lldp packets. Hence I need to change the destination mac of the lldp packets so that they are forwarded through the switch(for other reasons too related to stp I need to make this change). So could you please tell me what is the destination mac set to in the lldp packets and where does this setting happen? Thanks you in advance!

**Comment by vincentbernat** [comment]
You can change the address in `src/daemon/lldp-tlv.h` (definition of `LLDP_MULTICAST_ADDR`). You can also change the Linux bridge to make it forward LLDP packets by echoing 16384 into `/sys/class/net/br0/bridge/group_fwd_mask`.

**Comment by athreyaDell** [comment]
That was really quick. Thank you. I figured the way out to make the linux bridge forward the lldp packets. However this could effect other employees (as per my mentor). change the multicast destn address seems to be a better fix. Also I had to change it for stp related issue. Thank you for the quick reply which saved me some time!

**Comment by athreyaDell** [comment]
Hi vincent, Will changing the destination MAC create problems ? Thanks

Our requirement
LLDP must be configured to use destination MAC 01:80:C2:00:00:00, same MAC as BPDUs or it will not flow through blocked ports. This is required for Spanning Tree in Disabled Mode.

**Comment by vincentbernat** [comment]
lldpd won't care much about that. Note that if you also want to be able to receive frames, you also have to modify `LLDPD_FILTER_F` in `src/daemon/lldpd.h` (change `0xc200000e` to `0xc2000000`).

**Comment by athreyaDell** [comment]
yup that's right..thank you for the headsup!

**Comment by athreyaDell** [comment]
hi Vincent, The packets are generated  with destination address MAC 01:80:C2:00:00:00 but somehow they are still not received at the other end. I am not sure if the linux bridge is forwarding it. Any comments on this ?  (I have modified the  LLDPD_FILTER_F  as specified to receive).

**Comment by vincentbernat** [comment]
It should be forwarded if STP is disabled or forward mask has first bit set. Well, this depends on the kernel version. Old 2.6 kernels (before 2.6.32) may have a different behavior. Checking if it is forwarded is easy, just sniff on the output interface.

**Comment by athreyaDell** [comment]
perfect..worked after the STP was disabled ! Thank you! I appreciate your quick response Vincent

**Comment by athreyaDell** [comment]
Hi Vincent, You have been of great help so far. Thanks for that.
The next step I am trying to do is integrate this lldpd with a switch-daemon. So every time there is a new lldp packet coming in (meaning the MIB has to be updated) the switch would recognize it through a function provider. If I am not very clear pardon me.

Questions:
1)To achieve this I am trying to figure out where in the code are these MIBs(being updated) every time when there is a new lldp packet coming in discovering a new neighbor.
I am assuming that LLDPD stores the neighbor information in MIBS. It tries to write into these mibs every time there is an update.

2) how is this writing into mibs happening ? (I see that its not using snmp)
3)location of the mibs?

**Comment by vincentbernat** [comment]
The code for that is in `src/daemon/lldpd.c`, function `lldpd_decode()`.

**Comment by athreyaDell** [comment]
is there a library which lets other daemons to interact with lldp ( so that the other daemon knows of new lldp packets).

there are 2 daemons: switchd and lldpd.
the switchd needs to use a library from the lldpd(if it exists) to interact with it and know if there is a new lldp packet coming in discovering a new neighbor.
please point me to that library. I don't want to keep polling because I want to make it single thread non blocking.

please point me to that library if it exists. Thanks

**Comment by vincentbernat** [comment]
The library is in `src/lib`. It's installed when you do `make install`. Look at `src/lib/lldpctl.h` for the API. A complete example on how to use it is the `lldpcli` command-line client.

**Comment by athreyaDell** [comment]
Hi Vincent,

Currently the information about its neighbors is stored in structs. I was wondering if there is a way that the lldp protocol stores the neighbors data in mibs rather than structs ?
I got a few hits for snmp and mibs in the lldp, hence was curious.Thanks

**Comment by vincentbernat** [comment]
You can attach lldpd to an snmpd agent (with `-x`) as an AgentX subagent.

**Comment by athreyaDell** [comment]
/home/root# lldpd -x snmpd
SNMP support is not built-in

**Comment by vincentbernat** [comment]
`./configure --with-snmp`

**Comment by athreyaDell** [comment]
while using lldp api to get some neighbor information as an binary executable, the code works fine and displays me the requested info but when I try to use the same apis (same code) on a zactor thread it(lldpctl_new_name)  fails.

const char *ctlname = lldpctl_get_default_transport();

 conn = lldpctl_new_name(ctlname, NULL, NULL, NULL); 

code is exactly the same except that now I am trying it on a thread. not sure what is going on to make it fail.

**Comment by vincentbernat** [comment]
What's a "zactor" thread?

**Comment by athreyaDell** [comment]
you can consider that as a normal thread. 
http://czmq.zeromq.org/manual:zactor

actually lldpctl_new_name is not failing,
this is failing..in the sense its returning NULL/0
 iface_list = lldpctl_get_interfaces(conn);

**Comment by vincentbernat** [comment]
`lldpctl_new_name()` is doing so little that I can't quite see how it could return NULL. Is it really `lldpctl_new_name()` that is returning NULL?

**Comment by athreyaDell** [comment]
lldpctl_get_interfaces(conn) is returning NULL .My first comment was confusing.

**Comment by athreyaDell** [comment]
hey actually I figured out. Since lldp apis are called by daemon,the daemon doesn't have permission.
so probably some change in the service file of the daemon. Do you know if lldp needs to be added as a supplementary user group?

**Comment by vincentbernat** [comment]
Read the error with `lldpctl_last_error()` and/or use `strace` to see what is happening.

**Comment by vincentbernat** [comment]
Just adjust the permissions of the Unix socket used by lldpd.

**Comment by athreyaDell** [comment]
Hi Vincent,

Is there anyway I can change the destination address of lldp to 01:80:C2:00:00:00 without fixing the code..by using arguments like -d for daemon. Is there anything such way of doing it ?

**Comment by athreyaDell** [comment]
or by using a configuration file something of that sort ? if so please direct me please.

**Comment by vincentbernat** [comment]
No, there is no way to do that.

**Comment by athreyaDell** [comment]
Howdy,

What I am trying to do: send lldp packets to the following address: 01:80:C2:00:00:00 
my previous changes(changing destination mac LLDP_MULTICAST_ADDR and changing receiving side filter)  worked fine but it wont be accepted in the open source world.

hence I am trying to add another option lldpd -n (nearest customer bridge) which sends the lldp packets to the new address. However on addition of a filter ({ 0x15, 0, 2, 0xc2000000 }) it segfaults, meaning the sockets are not getting configured properly. Could you please help me make this addition. What would be the right entry ?
fyi: changing 0x15, 0, 2, 0xc200000e  to 0x15, 0, 2, 0xc2000000 works perfectly.
Thanks

**Comment by vincentbernat** [comment]
I have pushed a commit to receive LLDP frames from the addresses that you need. Could you test that first? You still need to modify `src/daemon/protocols/lldp.c` in `_lldp_send`, `mcastaddr` should be `LLDP_ADDR_NEAREST_CUSTOMER_BRIDGE`.

**Comment by athreyaDell** [comment]
Yup I tested it.. Works perfect. sorry for the delay in update due to weekend.. It was generous of you to have done these commits so quickly while I only asked how to do it. I am inspired by your motivation. Thank you again!

**Comment by vincentbernat** [comment]
With this additional commit, you should be able to use "configure lldp agent-type nearest-customer-bridge" to change the MAC address.

**Comment by athreyaDell** [comment]
HI Vincent,
we dont want to use the lldpcli command "configure lldp agent-type nearest-customer-bridge" to change the MAC. we actually needed lldpd -l(or some other option) to do the magic (change the destination mac to 01:80:C2:00:00:00) and not change it( mcastaddr ) manually in the code( src/daemon/protocols/lldp.c  in  _lldp_send ). I genuinely appreciate all the help so far.

**Comment by vincentbernat** [comment]
Put the command in /etc/lldpd.conf. I don't want to add more flags for `lldpd`.

**Comment by athreyaDell** [comment]
yup I had explained the same thing: To put the command in  /etc/lldpd.conf.
Unfortunately I didn't deliver it well before to my boss. They are perfectly ok with this method when I explained again! Thank you!

Now all I am looking for is the release of 0.9.4 tar ball. Because its still at 0.9.3 and an update ticket right now would lead the upgrade team to upgrade to 0.9.3 which I don't want. Though I can test it locally, I want everyone to have the updated package so that they can use my code associated with it.
Thank you

**Comment by vincentbernat** [comment]
I just released 0.9.4.

**Comment by athreyaDell** [comment]
..It takes just a lunch time and you have the work done! You are an inspiration to me. Thank you again!

**Comment by athreyaDell** [comment]
The software version was updated and I am trying to use the latest package but I get this output on executing the new cli command (configure lldp agent-type nearest-customer-bridge): unknown command from argument 3: `agent-type`

**Comment by vincentbernat** [comment]
I suppose that you are using an older version of lldpcli. Check its version with `lldpcli -v`.

**Comment by athreyaDell** [comment]
yes. I wasn't doing it right. sorry for the confusion. Its working.

**Comment by athreyaDell** [comment]
could you please tell me how the service file lldpd.service location might have changed from 0.7.7 to 0.9.4
For the code 0.7.7
the following code in lldpd.inc (bitbake file) would kick start the lldpd daemon but now it doesn't.
FILES_${PN} += "/lib/systemd/system/lldpd.service"
inherit systemd
SYSTEMD_SERVICE_${PN} = "lldpd.service"

infact I don't see the lldpd.service file in the src/daemon folder as well. Any idea whats happening here ?

**Comment by athreyaDell** [comment]
has the location of service file changed from 0.7.7 to 0.9.4 . I am having trouble with the bitbake files with regards to the service file location

**Comment by athreyaDell** [comment]
something about the location of service file has changed between 0.7.7 and 0.9.4 ?
