### ISSUE TITLE
Network Policy TLV

### ISSUE THREAD

**Issue by bhdl** [vincentbernat/lldpd#172]
Hi Vincent,

Do you know what command LLPD to send Network Policy TLV ?

Thank you,
Bryan

**Comment by vincentbernat** [comment]
See manual page for lldpcli.

**Comment by bhdl** [comment]
Will the command custom-tlv do it?
 configure lldp custom-tlv [add | replace] oui oui subtype subtype
       [oui-info content]

Thank you

**Comment by vincentbernat** [comment]
Search for "network policy". There is "configure med policy".

**Comment by bhdl** [comment]
Thank you.

**Comment by bhdl** [comment]
Hi Vincent,

I try command:
lldpcli configure med policy application voice priority  voice dscp 46

and got WARN but no LLDP in wireshark trace

2016-04-15T11:38:43 [WARN/lldpctl] unknown command from argument 1: `configure`

Do I need to run “lldpd” after “lldpcli”?

Thank you,
Bryan

**Comment by vincentbernat** [comment]
This means that lldpcli thinks you are not root.

**Comment by bhdl** [comment]
How do I run lldpcli in runtime as root using system(“lldpcli …”) command?

Thank you,
Bryan

**Comment by athreyaDell** [comment]
first go into root mode:   su
next enter the password.
execute lldpcli

**Comment by bhdl** [comment]
Does lldpd require running as root?

Thank you,
Bryan

**Comment by bhdl** [comment]
Hi Vincent,

How does lldpd.conf work? Can I build to include .conf file?

Thank you,
Bryan

Sent from my iPhone

On Apr 15, 2016, at 2:03 PM, Vincent Bernat <notifications@github.com<mailto:notifications@github.com>> wrote:


This means that lldpcli thinks you are not root.

-

**Comment by bhdl** [comment]
Hi Vincent,

How do I execute lldpcli configure in embedded linux without root login?

Thank you,
Bryan
