### ISSUE TITLE
Assertion ctx failed in evmap_io_active

### ISSUE THREAD

**Issue by bhdl** [vincentbernat/lldpd#176]
Hi,

There is sometime error message: "Assertion ctx failed in evmap_io_active. Aborted."
I have to rerun lldpd manually.

 Do you know what cause the ctx failed?

Thank you

**Comment by vincentbernat** [comment]
Could you try with `export EVENT_NOEPOLL=1`?

**Comment by vincentbernat** [comment]
Likely to be related to buggy epoll in old kernel. Closing.
