### ISSUE TITLE
Problems enabling CDP on Centos 7

### ISSUE THREAD

**Issue by masonke** [vincentbernat/lldpd#178]
Having a problem enabling CDP on Centos 7. Using lldpd 0.7.19

Have tried adding -c, '-c' and DAEMON_ARGS="-c" to the /etc/lldpd.conf file, but still get an error like 
  unknown command from argument 1: `-c`

What is the correct format for the file to enable CDP?

Sample log entry below

May 12 08:31:38 foo lldpd[64286]: protocol LLDP enabled
May 12 08:31:38 foo lldpd[64286]: protocol CDPv1 disabled
May 12 08:31:38 foo lldpd[64286]: protocol CDPv2 disabled
May 12 08:31:38 foo lldpd[64286]: protocol SONMP disabled
May 12 08:31:38 foo lldpd[64286]: protocol EDP disabled
May 12 08:31:38 foo lldpd[64286]: protocol FDP disabled
May 12 08:31:38 foo lldpd[64286]: libevent 2.0.22-stable initialized with epoll method
**May 12 08:31:38 foo lldpcli[64284]: unknown command from argument 1: `DAEMON_ARGS=-c`**
May 12 08:31:38 foo lldpcli[64284]: an error occurred while executing last command
May 12 08:31:38 foo lldpd: Starting lldpd: [  OK  ]
May 12 08:31:38 foo lldpcli[64284]: lldpd should resume operations

**Comment by vincentbernat** [comment]
The `/etc/lldpd.conf` file should contain commands understood by lldpcli (see its manual page). To enable CDP on CentOS, you should modify `/etc/sysconfig/lldpd` instead.

**Comment by masonke** [comment]
Thank you, I was not clear on where to make those changes. Since I
completely missed that, where is that in the docs?

**Comment by vincentbernat** [comment]
No, it is not. It just follows the convention on Redhat/CentOS that to modify the behaviour of a daemon, you should check `/etc/sysconfig/daemonname`. I have added a mention here: http://vincentbernat.github.io/lldpd/installation.html
