### ISSUE TITLE
lldpcli watch doesn't show changes in neighbor info in xml or json formats

### ISSUE THREAD

**Issue by gvchaitanya2610** [vincentbernat/lldpd#179]
Hi,
When running 'lldpcli -f xml watch' with xml/json enabled I don't see the response being generated though there are neighbor changes detected.
Normal 'lldpcli -f xml show neighbors' is returning the neighbor info in xml format as expected.
Kindly take a look into this issue.

Thanks.

**Comment by vincentbernat** [comment]
Does it work when you don't specify a format?

**Comment by gvchaitanya2610** [comment]
Yes it works when no format is given or -f plain is given.

**Comment by vincentbernat** [comment]
OK, I see why. I'll push a fix soon.
