### ISSUE TITLE
Make pid file configurable at runtime

### ISSUE THREAD

**Issue by mjoras** [vincentbernat/lldpd#181]
Right now the lldpd pid file is only configurable at compile time. This is less than ideal for our use case of lldpd, which is to have daemons per-interface. Each daemon is treated as a service, and pid files are required for the service functionality (i.e. stopping) to work.

It would be nice if lldpd had this as a configurable option, since right now we work around this by making our own pid file per-instance when we spawn lldpd.

If you're willing to point me in the right direction for adding this functionality I'd be willing to try it myself and make a PR.

**Comment by vincentbernat** [comment]
It's quite trivial and not worth the time to explain how to do that. I'll push a commit in the next minutes.

**Comment by mjoras** [comment]
Thanks!
