### ISSUE TITLE
FreeBSD: 0.9.3 doesn't build anymore

### ISSUE THREAD

**Issue by matsimon** [vincentbernat/lldpd#185]
Bonjour Vincent

I wanted to update the FreeBSD port when I ran across a build issue.

A minor issue: I'm missing a tag for 0.9.3 for quick and easy identification but I was able to work without. I think it should be commit 0517bd3bdd5605c752892e09f55671b4439a12ef

The error message I'm getting on FreeBSD 10.3 (clang 3.4.1) is as follows:
```
  CC       atoms/custom.lo
  CC       atoms/chassis.lo
  GEN      atom-glue.c
cc: fatal error: no input files
cc: fatal error: no input files
*** Error code 1

```

I was able to pin down things to commit starting d954509eb76a18b2a96ec826cba90b9a093d05f9 causing issues.

After digging down a littble bit more I think I see what is happening:
```
$ ls src/lib/atom-glue.*
src/lib/atom-glue.c.tmp src/lib/atom-glue.h.tmp
```
src/lib/Makefile generated (by autogen I suppose) contains an 'mv' command for i.e. 'atom-glue.c' which doesn't seem to work out since the .tmp files remain atom-glue.[c|h] respectively. If I rename them after the first make the build passes.

That's what I was able to collect so far in the time I could spend. I suspect that mv isn't doing on FreeBSD what you intended it to do i.e. what autogen.sh generates src/lib/Makefile.

**Comment by vincentbernat** [comment]
❦ 12 juin 2016 22:44 CEST, Mathieu Simon <notifications@github.com> :

> A minor issue: I'm missing a tag for 0.9.3 for quick and easy
> identification but I was able to work without. I think it should be
> commit 0517bd3

Yes, that's the one. I pushed the tag.

> src/lib/Makefile generated (by autogen I suppose) contains an 'mv'
> command for i.e. 'atom-glue.c' which doesn't seem to work out since
> the .tmp files remain atom-glue.[c|h] respectively. If I rename them
> after the first make the build passes.

You can find the mv in `src/lib/Makefile.am`. This rule should be
verbatim in the generated `src/lib/Makefile`. I don't see why it wouldn't
work. In `src/lib`, could you just run `make atom-glue.c V=1`?  And
check if it creates `atom-glue.c`. The `atom-glue.h.tmp` shouldn't be
here either. Maybe that's the same problem. I suppose you are using BSD
make?

I'll dig more myself in a VM.
-- 
Make your program read from top to bottom.
            - The Elements of Programming Style (Kernighan & Plauger)

**Comment by vincentbernat** [comment]
I just pushed a change. Could you test? You need to run `./autogen.sh` first. If it works, I can do a release soon, so you don't have to patch autoconf-generated files.

**Comment by matsimon** [comment]
>  I suppose you are using BSD make?
Yes, and that seems to be causing the issue. If I use gmake instead, that seems to work.

Since I'm not familiar with the differences between GNU and BSD make I had to do some searching which which turned up this message to [freebsd-questions@ list](https://lists.freebsd.org/pipermail/freebsd-questions/2007-April/147533.html): The difference seems to be with GNU make's automatic variables use.

With my limited knowledge I tried to be "smart" by replacing `$@` by `atom-glue.c.tmp` in `src/lib/Makefile.am` however It seems that `./configure` is being too smart since afterwards `$@` is back in the `resulting src/lib/Makefile`

I think it's up to you to decide whether it's worth trying to work around the differences or stick with GNU make (but then it should be documented).

Until 0.9.2 also the OpenBSD folks used their BSD make in their ports makefile. I could force the use of GNU make in the FreeBSD port, however that drags in a couple of other build dependencies.

**Comment by matsimon** [comment]
Sorry @vincentbernat I wasn't refreshing while you have pushed the commit, let me check asap!

**Comment by matsimon** [comment]
Thanks Vincent!

Confirmed confirmed on 10.3 amd64 and for shits and giggles: PPC64 too as a quick compile test only. ;-)

I just learned something about the differences with the various 'make' imeplementations thanks to you and I'm glad that you could resolve it with such a small fix. As added bonus I saw your import of the OpenBSD media patch, Stuart is going to like that.

-- Mathieu

**Comment by vincentbernat** [comment]
For some reason, this broke with GNU make. I am trying to fix that and I'll do a release.

**Comment by vincentbernat** [comment]
0.9.4 has been released.

**Comment by matsimon** [comment]
Hi Vincent

Sorry that I couldn't back to you before the weekend. However I'm having new issues with 0.9.4 for which I'll open new issues. The problem with BSD make itself is resolved that's what I can confirm.
