### ISSUE TITLE
Redirecting lldpcli -f xml watch to a file

### ISSUE THREAD

**Issue by gvchaitanya2610** [vincentbernat/lldpd#187]
Hi,
Is there a way to redirect the output generated from 'lldpcli -f xml watch' for a neighbor info change to a file ? Given that lldpcli watch is a blocking call, piping the output is not possible.

Thanks.

**Comment by vincentbernat** [comment]
You can use it in a loop. `lldpcli -f xml watch limit 1`.

**Comment by gvchaitanya2610** [comment]
Thanks for the response. This works well when there is a change in a single ngbr info.
But in case we have multiple ngbrs changed their info simultaneously (See example below) we will be able to pipe only one of the changes and the rest are lost. Is there a way to capture this multiple ngbr change into a file ?

Regards.

**On a side note:** Here the xml is also malformed as all the changes are simply dumped to stdout.

**Example:** multiple ngbr info change simultaneously 

<?xml version="1.0" encoding="UTF-8"?>
<lldp-updated label="LLDP neighbor updated">
 <interface label="Interface" name="eth1" via="LLDP" rid="1" age="0 day, 00:00:00">
  <chassis label="Chassis">
   <id label="ChassisID" type="mac">08:00:27:2e:46:6b</id>
   <name label="SysName">lldp000</name>
   <descr label="SysDescr">Ubuntu 14.04.4 LTS Linux 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64</descr>
   <ttl label="TTL">120</ttl>
   <mgmt-ip label="MgmtIP">168.127.182.76</mgmt-ip>
   <mgmt-ip label="MgmtIP">fe80::a00:27ff:fe2e:466b</mgmt-ip>
   <capability label="Capability" type="Bridge" enabled="off"/>
   <capability label="Capability" type="Router" enabled="off"/>
   <capability label="Capability" type="Wlan" enabled="off"/>
   <capability label="Capability" type="Station" enabled="on"/>
  </chassis>
  <port label="Port">
   <id label="PortID" type="mac">08:00:27:2e:46:6b</id>
   <descr label="PortDescr">eth0</descr>
  </port>
 </interface>
</lldp-updated>
<?xml version="1.0" encoding="UTF-8"?>
<lldp-updated label="LLDP neighbor updated">
 <interface label="Interface" name="eth0" via="LLDP" rid="1" age="0 day, 00:00:00">
  <chassis label="Chassis">
   <id label="ChassisID" type="mac">08:00:27:2e:46:6b</id>
   <name label="SysName">lldp000</name>
   <descr label="SysDescr">Ubuntu 14.04.4 LTS Linux 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64</descr>
   <ttl label="TTL">120</ttl>
   <mgmt-ip label="MgmtIP">168.127.182.76</mgmt-ip>
   <mgmt-ip label="MgmtIP">fe80::a00:27ff:fe2e:466b</mgmt-ip>
   <capability label="Capability" type="Bridge" enabled="off"/>
   <capability label="Capability" type="Router" enabled="off"/>
   <capability label="Capability" type="Wlan" enabled="off"/>
   <capability label="Capability" type="Station" enabled="on"/>
  </chassis>
  <port label="Port">
   <id label="PortID" type="mac">08:00:27:86:a5:bc</id>
   <descr label="PortDescr">eth1</descr>
  </port>
 </interface>
</lldp-updated>

**Comment by vincentbernat** [comment]
In this case, you can pipe the output to a file using the shell:

    lldpcli -f xml watch > /tmp/output.xml

However, lldpcli doesn't flush the results between each neighbor, so you will get the changes late. It's easy to change that. Would it work for you?

**Comment by vincentbernat** [comment]
Assuming that flushing of output is enough to meet the need. Reopen if not.
