### ISSUE TITLE
Unnessesary dependencies (libjansson, libxml2)

### ISSUE THREAD

**Issue by bjne** [vincentbernat/lldpd#188]
It would be nice to just generate the json/(xml) output directly instead of
having to depend on external libraries. lldpd is useful also for embedding,
and json is allways useful..

**Comment by vincentbernat** [comment]
If there are some odd characters in some of the received strings, using libjansson and libxml2 ensures me that I am generating valid JSON/XML. Hence, I would prefer to stick to them. What's your constraint? It's possible to compile statically libjansson inside lldpcli.

Generating JSON is simple enough to be a possibiilty as an alternative to libjansson and json-c.

**Comment by bjne** [comment]
Its mostly frustration about adding "unnessesary" dependencies in general.
Json string encoding should be straight forward..

**Comment by vincentbernat** [comment]
Implementation could be taken from http://git.ozlabs.org/?p=ccan;a=blob;f=ccan/json/json.c;h=2f0452aebe568277f554072eff7685bdd6b33fc9;hb=HEAD#l1106 (but as you see, not as straight forward as one may think).

**Comment by bjne** [comment]
Eventually: https://github.com/nlohmann/json/blob/ec7a1d834773f9fee90d8ae908a0c9933c5646fc/src/json.hpp#L4604-L4697
