### ISSUE TITLE
Adding subtype for management Ip

### ISSUE THREAD

**Issue by gvchaitanya2610** [vincentbernat/lldpd#190]
Hi,
Is there a provision to add management ip subtype in the neighbor info, as this would make it clear if the parsed address is for ipv4 or ipv6 or any other type.

   <mgmt-ip label="MgmtIP">192.168.1.97</mgmt-ip>
   <mgmt-ip label="MgmtIP">2602:304:b11e:2060:944f:97e8:be0:566b</mgmt-ip>

Thanks.

**Comment by gvchaitanya2610** [comment]
Hi did you get a chance to take a look at the above query ?
Thanks.

**Comment by vincentbernat** [comment]
Sorry, I currently have no time and it seems quite easy to workaround the difficulty. If you have ":", it's an IPv6 address, otherwise, it's IPv4.

**Comment by vincentbernat** [comment]
I prefer not to change the output of lldpcli (to not break other uses) while there is an easy way to get the information (checking if address has `:` in it).
