### ISSUE TITLE
lldpd agentx and snmp traps

### ISSUE THREAD

**Issue by stannous** [vincentbernat/lldpd#193]
While I can use lldpd (with -x) with snmpd just fine, I'm wondering how to configure lldpd/snmpd to send traps automatically for neighbor changes (adds/delete/update).  I see some code in 
src/daemon/agent.c:agent_notify(), but it's not clear to me how it is used.   I can configure
traps for specific OIDs if known in advance in /etc/snmp/snmpd.conf and configure the
trap sink, but how do I configure lldpd to send traps for neighbor changes?   In /etc/snmp/snmpd.conf or /etc/lldpd.conf?  

Thanks,
Sam

**Comment by vincentbernat** [comment]
As a subagent, lldpd will always transmit traps to master agent. So, if you want to process them, you need to configure the master agent (in `/etc/snmp/snmpd.conf`), like you would do for more regular traps like IF-MIB linkUp and linkDown.

**Comment by stannous** [comment]
With snmptrapd and snmpd configured appropriately, I do see some traps from lldpd:

Link goes down:  this must be automatic.  I do not see which neighbor disappeared.

`
# this appears to not be an snmptrap message but only a syslog from lldpd
2016-08-09T16:24:31.798511+00:00 abc-01 lldpd[4138]: error while receiving frame on swp3: Network is down

2016-08-09T16:24:32.855156+00:00 abc-01 snmptrapd[3945]: 2016-08-09 16:24:32 10.0.1.7(via UDP: [127.0.0.1]:56265->[127.0.0.1]:162) TRAP, SNMP v1, community public#012#011LLDP-MIB::lldpNotifications Enterprise Specific Trap (1) Uptime: 0:04:11.88#012#011LLDP-MIB::lldpStatsRemTablesInserts = Gauge32: 4 table entries#011LLDP-MIB::lldpStatsRemTablesDeletes = Gauge32: 0 table entries#011LLDP-MIB::lldpStatsRemTablesDrops = Gauge32: 0 table entries#011LLDP-MIB::lldpStatsRemTablesAgeouts = Gauge32: 0
`

Link comes back up:  This is also automatic.

`2016-08-09T16:31:07.293938+00:00 abc-01 snmptrapd[3945]: 2016-08-09 16:31:07 10.0.1.7(via UDP: [127.0.0.1]:56265->[127.0.0.1]:162) TRAP, SNMP v1, community public#012#011LLDP-MIB::lldpNotifications Enterprise Specific Trap (1) Uptime: 0:10:46.31#012#011LLDP-MIB::lldpStatsRemTablesInserts = Gauge32: 5 table entries#011LLDP-MIB::lldpStatsRemTablesDeletes = Gauge32: 0 table entries#011LLDP-MIB::lldpStatsRemTablesDrops = Gauge32: 0 table entries#011LLDP-MIB::lldpStatsRemTablesAgeouts = Gauge32: 0#011LLDP-MIB::lldpLocPortDesc.5 = STRING: swp3#011LLDP-MIB::lldpRemSysName.64700.5.2 = STRING: switch2#011LLDP-MIB::lldpRemPortDesc.64700.5.2 = STRING: swp3
`

This is good because this notification tells me the OID of the new row in the table
(64700), but what about the link went down?

`# snmptranslate -Td 1.0.8802.1.1.2.1.1.6.1.3
LLDP-MIB::lldpPortConfigNotificationEnable
lldpPortConfigNotificationEnable OBJECT-TYPE
  -- FROM	LLDP-MIB
  -- TEXTUAL CONVENTION TruthValue
  SYNTAX	INTEGER {true(1), false(2)} 
  MAX-ACCESS	read-write
  STATUS	current
  DESCRIPTION	"The lldpPortConfigNotificationEnable controls, on a per
            port basis,  whether or not notifications from the agent
            are enabled. The value true(1) means that notifications are
            enabled; the value false(2) means that they are not."
  DEFVAL	{ false }
::= { iso(1) std(0) iso8802(8802) ieee802dot1(1) ieee802dot1mibs(1) lldpMIB(2) lldpObjects(1) lldpConfiguration(1) lldpPortConfigTable(6) lldpPortConfigEntry(1) 3 }
`

When I walk this part of the MIB (using LLDP-MIB-200505060000Z.txt  and lldpd version based on 0.9.1-0) I do not get any response.   

Is this part of the LLDP-MIB supported in any way?   How can I configure lldpd to send these port notifications?

Do I need to specify exact OIDs in my snmpd.conf to monitor?

**Comment by vincentbernat** [comment]
`lldpPortConfigNotificationEnable` is not implemented. Notifications are always enabled.

As for the content, the MIB only says to send the counters. If you look at `lldpRemTable`, they expect you to store the previous values to know what changed. Since it was easy to send info about the neighbor when it appears, this was done. However, notifications are sent too late to still have information about the neighbor when it is deleted. Therefore, the information doesn't appear.

**Comment by vincentbernat** [comment]
I am closing this as there is not much I can do. Once your receive the trap, you can walk `lldpRemTable` by using the value of `lldpStatsRemTableLastChangeTime`. This is explained in the MIB.
