### ISSUE TITLE
service that requires lldpd cannot find it

### ISSUE THREAD

**Issue by kdubezerra** [vincentbernat/lldpd#194]
I'm installing a service that depends on the lldpd daemon on Cumulus Linux (https://cumulusnetworks.com). It's packaged in a .deb file and installs fine with Cumulus v2.5 (lldpd v0.7.11), but my service cannot find lldpd on Cumulus v3 (lldp v0.9.1).  My service has the following header in the LSB script:

```
### BEGIN INIT INFO
# Provides: myservice
# Required-Start: $remote_fs $network $syslog lldpd
# Required-Stop: $network $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: My Service
# Description: Long description of My Service.
### END INIT INFO
```

When installing its from a debian package, 

```
+ /usr/sbin/update-rc.d myservice defaults
insserv: Service lldpd has to be enabled to start service myservice
insserv: exiting now!
update-rc.d: error: insserv rejected the script header
dpkg: error processing package myservice (--install):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 myservice
```

After that, I ran status and lldpd is in fact running:

```
vagrant@p1r1s2:~$ sudo systemctl status lldpd
● lldpd.service - LLDP daemon
   Loaded: loaded (/lib/systemd/system/lldpd.service; enabled)
   Active: active (running) since Fri 2016-08-12 08:23:54 UTC; 4h 50min ago
     Docs: man:lldpd(8)
 Main PID: 769 (lldpd)
   CGroup: /system.slice/lldpd.service
           ├─769 lldpd: monitor .
           └─782 lldpd: 2 neighbors

Aug 12 08:23:54 cumulus lldpd[769]: dmiinfo = {bios_version:VirtualBox,manufacturer:innotek GmbH,model:VirtualBox,sysserialnum:0,sysversion:,sysasset:}
Aug 12 08:23:54 cumulus lldpcli[776]: cannot find configuration file/directory /etc/lldpd.conf: No such file or directory
Aug 12 08:23:54 cumulus lldpd[782]: created chroot directory /var/run/lldpd
Aug 12 08:23:54 cumulus lldpd[782]: /etc/localtime copied to chroot
Aug 12 08:23:54 cumulus lldpd[782]: found lsb_release = Cumulus Linux, lsb_version = 3.0.1
Aug 12 08:23:54 cumulus lldpd[782]: protocol LLDP enabled
Aug 12 08:23:54 cumulus lldpd[782]: protocol CDPv1 enabled
Aug 12 08:23:54 cumulus lldpd[782]: protocol CDPv2 enabled
Aug 12 08:23:54 cumulus lldpd[782]: libevent 2.0.21-stable initialized with epoll method
Aug 12 08:23:54 cumulus lldpcli[776]: LLDP PortID TLV type set to new value : ifname
```

Apparently, the system cannot find LSB scripts for lldpd:

```
vagrant@p1r1s2:~$ update-rc.d lldpd enable
update-rc.d: error: cannot find a LSB script for lldpd
vagrant@p1r1s2:~$ update-rc.d lldpd defaults
update-rc.d: error: initscript does not exist: /etc/init.d/lldpd
```

**Comment by vincentbernat** [comment]
lldpd should come with an init.d script. How did you  install it?

**Comment by kdubezerra** [comment]
I did a `sudo apt-get update && sudo apt-get install lldpd`. The package is coming from http://repo3.cumulusnetworks.com/repo/pool/cumulus/l/lldpd.

**Comment by kanrajag** [comment]
This is the lldpd agent that is modified by Cumulus. We removed the init.d script from our repo because we only target jessie based systems and we solely rely on systemd. The presence of the init.d file was causing some issues during installation - so we decided to remove it. Please use the upstream version of lldpd if you need to use init.d script

**Comment by kdubezerra** [comment]
I'm using Cumulus VX v3, which I believe is based on Debian jessie, no?

```
vagrant@p1r1s2:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Cumulus Linux
Description:	Cumulus Linux 3.0.1
Release:	3.0.1
Codename:	jessie
```

**Comment by vincentbernat** [comment]
Maybe, the easiest way to fix that would be to use a systemd unit for your service.

**Comment by kdubezerra** [comment]
Thanks for the replies! My installation script now checks for the availability of LSB, systemd and of lldpd's init.d file, then it decides what to do. Now it's working fine with both Cumulus v2.5 and Cumlus v3. I believe this issue can be closed. Thanks again!
