### ISSUE TITLE
How to make two or more lldpd daemon run at the same Linux machine

### ISSUE THREAD

**Issue by zmingshi** [vincentbernat/lldpd#195]
Hi,

I installed lldpd v0.9.4 on a Linux machine, I want to know how to enable two or more lldpd daemon. I know `-L` should be used, but could you give me a simple example? Thank you very much!

Best Regards!

**Comment by vincentbernat** [comment]
`lldpd -u /var/run/lldpd2.socket` and query it with `lldpcli -u /var/run/lldpd2.socket show neigh`.

**Comment by zmingshi** [comment]
Hi, @vincentbernat 

I start two lldpd daemons on one machine, one daemon is used to listen to wlan0 interface, and another is used to listen to eth0 interface. Then I want to configure one daemon as `tx-only`, and another daemon as `rx-and-tx` at the lldpd startup, then how to configure the daemon as `tx-only`, I tried the command `-u /usr/local/var/run/lldpd1.socket configure lldp status tx-only` in configuration file (lldpd1.socket is for wlan0 interface), but it failed, the configuration seems not work.
Thank you very much!
Best Regards!

**Comment by vincentbernat** [comment]
What do you mean by configuration file? The configuration file (`/etc/lldpd.conf`) is common to both daemons. You need to issue the `lldpcli -u /usr/local/var/run/lldpd1.socket configure lldp status tx-only` command directly.

**Comment by zmingshi** [comment]
I just mean the file `/etc/lldpd.conf` and I get it. I also tried the command and it was indeed ok. I thought the configuration file could be set differently for each daemon. If it is common, then I have no question about it. Thank you!
