### ISSUE TITLE
Why only 4 lldp neighbors are shown from lldpctl

### ISSUE THREAD

**Issue by ton31337** [vincentbernat/lldpd#199]
Hi,

why I see only 4 lldp neighbors from lldpctl? After restart I see others, but only 4 at a time..

D.

**Comment by vincentbernat** [comment]
Are they all on the same port? Do each neighbor has a distinct MSAP (chassis ID and port ID)?

**Comment by ton31337** [comment]
This case happens when using virtualization, for instance vmware esxi, you should be able to see all other vms as lldp.

**Comment by vincentbernat** [comment]
Try to run lldpd with `-H 0`.

**Comment by ton31337** [comment]
Same here, but solved just disabling transmit mode, enabled only receive mode, it's enough for my case.
