### ISSUE TITLE
  configure system taking effect only after 180 sec

### ISSUE THREAD

**Issue by gvchaitanya2610** [vincentbernat/lldpd#202]
Hi Vincent,
When ever we use  'lldpcli configure system' followed by corresponding parameter, observing the changed value in the neighbor only after 180sec irrespective of the configured TTL value. Is there a way to reduce this latency ? Can we have the update going immediately or the following transmission after TTL.

Thanks.

**Comment by vincentbernat** [comment]
You can use `lldpcli update` to send LLDPDU to all neighbors immediately.

**Comment by gvchaitanya2610** [comment]
This is not about sending but the receiving state machine.

But based on 802.11AB 
9.2.7.5 mibUpdateObjects()
The mibUpdateObjects() procedure updates the MIB objects corresponding to the TLVs contained in the
received LLDPDU for the LLDP remote system if MIB space is available, as follows:
a) Compare the MSAP identifier in the current LLDPDU with the MSAP identifiers in the LLDP
remote systems MIB:
1) If a match is found, **replace all current information associated with the MSAP identifier in the
LLDP remote systems MIB with the information in the current LLDPDU.**

But looks like only after TTL value are the new ngbr info is updated in the local cache. 
Can you please  take a look at this as for a TTL of 120 the update is happening after 180s.

**Comment by vincentbernat** [comment]
Is the neighbor also running lldpd? lldpd doesn't delay updates consecutive to a received LLDPU. The problem you seem to face is that lldpd may not send immediately a new TLV but may wait for 30 seconds (the default transmit interval). Unless you modified those values, I don't see why something would wait 180s to be updated.

**Comment by vincentbernat** [comment]
I am closing the bug. If new information is available, feel free to reopen.
