### ISSUE TITLE
error while running lldpd

### ISSUE THREAD

**Issue by Akshayjimmy** [vincentbernat/lldpd#205]
lldpcli: error while loading shared libraries: liblldpctl.so.4: cannot open shared object file: No such file or directory

**Comment by vincentbernat** [comment]
How did you install lldpd?

**Comment by Akshayjimmy** [comment]
I followed the steps which is given in the
Vincentbernat.github.io/lldpd/installation.html#install-from-source

**Comment by vincentbernat** [comment]
After `sudo make install`, try run `sudo ldconfig`.

**Comment by Akshayjimmy** [comment]
After that what I have to do

**Comment by vincentbernat** [comment]
Do you still have the same error?

**Comment by Akshayjimmy** [comment]
after that i do sudo lldpd -d
its show in this error
unable to create control socket at /usr/local/var/run/lldpd.socket: No such
file or directory

**Comment by Akshayjimmy** [comment]
no its showing this error
unable to create control socket at /usr/local/var/run/lldpd.socket: No such
file or directory

**Comment by vincentbernat** [comment]
Use `mkdir -p /usr/local/var/run`.

**Comment by Akshayjimmy** [comment]
cannot find configuration file/directory /usr/local/etc/lldpd.conf: No such
file or directory

now this is the error

**Comment by vincentbernat** [comment]
This is not a fatal error. If there are no other errors, lldpd should be running in background. Check with `ps auxww | grep lldpd`.

**Comment by Akshayjimmy** [comment]
Yes It is running

**Comment by vincentbernat** [comment]
Does lldpcli works?

**Comment by Akshayjimmy** [comment]
Yes ,working

Thank you
