### ISSUE TITLE
br0 is not forwarding 

### ISSUE THREAD

**Issue by Akshayjimmy** [vincentbernat/lldpd#207]
i run llpd in veth0 and i try to capture packet from veth3 wich is connected to br0 other side

**Comment by vincentbernat** [comment]
Is it on the same host? If yes, what's the output of `brctl`? LLDP being a "link-layer" protocol, it is expected that it is not forwarded through bridges.

**Comment by Akshayjimmy** [comment]
Yes
Showing commands

**Comment by vincentbernat** [comment]
Sorry, not a support forum, if you can't collect minimal information about your problem, ask for help from your workmates.
