### ISSUE TITLE
Not able to retrieve LLDP-MED location identification from Cisco SG200-08P

### ISSUE THREAD

**Issue by chiudavid** [vincentbernat/lldpd#210]
## Steps to reproduce the problem

 1. Installed lldpd 0.9.5 from openSUSE Build Service to Lubuntu 14.04.5

 2. Changed the daemon arguments to `-M 3`

 3. Wait for a LLDPDU from the remote switch (Cisco SG200-08P , release 1.0.8.3).
 
## Expected outcome

- If the switch provides "Civic Address" location
`lldpcli show neighbors details` should show the civic address embedded in LLDPDU

## Current outcome

- If the switch provides "Civic Address" location
`lldpcli show neighbors details` shows that the remote switch supports location, but no address is shown

**Comment by vincentbernat** [comment]
I don't remember if "show neighbors" shows everything. Try to add `details`.

If there are still stuff missing, would you be able to provide a pcap of the packet? Use:

```
tcpdump -pni eth0 -vv -X ether host 01:80:c2:00:00:0e
```

**Comment by chiudavid** [comment]
I have tested again and the coordinate-based location problem is only due to wrong settings, I have edited the issue. But I still cannot see the civic address after using `lldpcli show neighbors details`

This is the output:
```
LLDP neighbors:
-------------------------------------------------------------------------------
Interface:    eth0, via: LLDP, RID: 3, Time: 0 day, 00:00:46
  Chassis:     
    ChassisID:    mac 00:da:55:d3:5e:2d
    TTL:          120
  Port:        
    PortID:       ifname g1
    PMD autoneg:  supported: yes, enabled: yes
      Adv:          1000Base-T, HD: no, FD: yes
      MAU oper type: unknown
  LLDP-MED:    
    Device Type:  Network Connectivity Device
    Capability:   Capabilities, yes
    Capability:   Policy, yes
    Capability:   Location, yes
    Capability:   MDI/PSE, yes
    Capability:   Inventory, yes
    Inventory:   
      Hardware Revision: V02
      Software Revision: 1.0.8.3
      Firmware Revision: 1.0.8.3
      Serial Number: PSZ19531BWT
      Manufacturer: 0xbc00
      Model:        SG 200-08P
      Asset ID:     1
-------------------------------------------------------------------------------
```
Please also find the pcap attached
[civic.pcap.zip](https://github.com/vincentbernat/lldpd/files/613393/civic.pcap.zip)

**Comment by vincentbernat** [comment]
This is fixed in master. The address length was smaller than the space allocated for the TLV and lldpd was therefore discarding it.
