### ISSUE TITLE
detecting interface as neighbors

### ISSUE THREAD

**Issue by athreyaDell** [vincentbernat/lldpd#211]
Currently the lldpd is detecting one of the interfaces 
( bcm0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000 link/ether b0:83:fe:f2:81:86 brd ff:ff:ff:ff:ff:ff ) as neighbors I believe.
I am trying to analyze why exactly does lldp detect so many neighbors while it has none.
Sharing the output of "show neighbors" on "lldpcli" and output of "ifconfig" and "ip link show".

[iplinkshow.txt](https://github.com/vincentbernat/lldpd/files/619447/iplinkshow.txt)
[ifconfig.txt](https://github.com/vincentbernat/lldpd/files/619448/ifconfig.txt)
[showneighbors.txt](https://github.com/vincentbernat/lldpd/files/619450/showneighbors.txt)

if you could give me some hint as to what is happening here, I would be grateful to you. Thanks!

**Comment by vincentbernat** [comment]
I am unsure to understand. There is no neighbor detected on bcm0 (which is down).

**Comment by athreyaDell** [comment]
from the lldpcli: show neighbors output in showneighbors.txt ,  isnt lldpd detecting neighbors on eth0 ?
the neighbors - chassis id is same as bcm0 interface which is down.
I was expecting it to show no neighbors..

**Comment by vincentbernat** [comment]
The chassis ID is one of the interfaces' MAC address. The chassis ID is global to a host (and should stay stable). Look at the port ID to see which port is emitting those LLDPDU. It seems that lldpd is configured to send them on eth0 as well.

**Comment by athreyaDell** [comment]
Thanks!

**Comment by athreyaDell** [comment]
I guess all I need to understand is the output:
From the output down here isnt eth0.4004 detecting its own interface as neighbor ?

PortID:       mac b0:83:fe:f2:81:4a is the mac of eth0.4004 and is being detected on  eth0.4004.

[lldpcli] # show neighbors
-------------------------------------------------------------------------------
LLDP neighbors:
-------------------------------------------------------------------------------
Interface:    eth0.4004, via: LLDP, RID: 17, Time: 0 day, 00:00:06
  Chassis:     
    ChassisID:    mac b0:83:fe:f2:81:46
    SysName:      ec-2.abcef12.local
    SysDescr:     Poky (Yocto Project Reference Distro) 2.0 (jethro) Linux 4.1.12.iDRAC #9 SMP Tue Nov 22 12:12:00 CST 2016 armv7l
    TTL:          4
    MgmtIP:       10.36.0.17
    MgmtIP:       fde1:53ba:e9a0:de12:b283:feff:fef2:8148
    Capability:   Bridge, off
    Capability:   Router, off
    Capability:   Wlan, off
    Capability:   Station, on
  Port:        
    PortID:       mac b0:83:fe:f2:81:4a
    PortDescr:    eth0.4004
  Unknown TLVs:
    TLV:          OUI: 00,01,E8, SubType: 8, Len: 22 65,63,2D,32,2D,62,30,3A,38,33,3A,66,65,3A,66,32,3A,38,31,3A,34,37

**Comment by athreyaDell** [comment]
I guess all I need to understand is the output:
From the output down here isnt eth0.4004 detecting its own interface as neighbor ?

PortID: mac b0:83:fe:f2:81:4a is the mac of eth0.4004 and is being detected on eth0.4004.

[lldpcli] # show neighbors

LLDP neighbors:

Interface: eth0.4004, via: LLDP, RID: 17, Time: 0 day, 00:00:06
Chassis:
ChassisID: mac b0:83:fe:f2:81:46
SysName: ec-2.abcef12.local
SysDescr: Poky (Yocto Project Reference Distro) 2.0 (jethro) Linux 4.1.12.iDRAC #9 SMP Tue Nov 22 12:12:00 CST 2016 armv7l
TTL: 4
MgmtIP: 10.36.0.17
MgmtIP: fde1:53ba:e9a0:de12:b283:feff:fef2:8148
Capability: Bridge, off
Capability: Router, off
Capability: Wlan, off
Capability: Station, on
Port:
PortID: mac b0:83:fe:f2:81:4a
PortDescr: eth0.4004
Unknown TLVs:
TLV: OUI: 00,01,E8, SubType: 8, Len: 22 65,63,2D,32,2D,62,30,3A,38,33,3A,66,65,3A,66,32,3A,38,31,3A,34,37

**Comment by vincentbernat** [comment]
It seems so. Could you check with tcpdump if you see the packet "coming back" (you could see the packet twice, once when it is sent and a second time when it comes back)? lldpd should filter out its own packets. This is done in interfaces-linux.c in `iflinux_eth_recv()` function. You may want to add some code here to check it works properly.

**Comment by athreyaDell** [comment]
[lldp.txt](https://github.com/vincentbernat/lldpd/files/622323/lldp.txt)

Its actually a pcap file. change the extension from .txt to .pcap to see it in the wireshark. I do see 2 LLDP packets but not sure if the lldp packets sent by eth0.4004 is received by eth0.4004. Both packets have the same source (eth0.4004) and destination as the multicast address which lldp uses.

**Comment by vincentbernat** [comment]
Since the two packets occur at the same time, I think you have the outgoing packet and the incoming one. Since the time is exactly the same (but the precision seems to be a bit low), it's possible that the Linux kernel itself is mirroring the packet back to the original interface. Maybe it's because of the use of the STP MAC address or maybe something else. Could you try the normal LLDP MAC first to see if you still have the same problem?

Maybe the integrated switch on your platform broadcast packets to all ports including the incoming one.

**Comment by athreyaDell** [comment]
I tried with the normal MAC (01:80:c2:00:00:0e) and i see the exact same behaviour.
[asd.txt](https://github.com/vincentbernat/lldpd/files/622390/asd.txt)

**Comment by vincentbernat** [comment]
So, something seems to be sending back the packet, which is not expected even in a broadcast context (IEEE 802.1D 7.7.1 says that you cannot forward a frame to the same port it comes from). Another solution would be for lldpd to discard packets when they have the MAC address of the port that sent it (but this could trigger unexpected behavior for devices sharing MAC with several ports).

**Comment by athreyaDell** [comment]
yup thanks for all the input!

**Comment by vincentbernat** [comment]
Tell me if you don't find anything on your side. I may consider discarding packets coming from our own MAC address.

**Comment by athreyaDell** [comment]
sure thing!
