### ISSUE TITLE
Add Repo for Fedora 24/25

### ISSUE THREAD

**Issue by Phhere** [vincentbernat/lldpd#214]
It would be nice when you could publish a repo for fedora 24/25

**Comment by vincentbernat** [comment]
I have added Fedora 24. The openSUSE build service doesn't have a builder for Fedora 25 yet.

**Comment by vincentbernat** [comment]
Let's keep it open to remember to add Fedora 25.

**Comment by vincentbernat** [comment]
Fedora 25 has just been added!
