### ISSUE TITLE
lldpd consumes 100% cpu

### ISSUE THREAD

**Issue by ortal99** [vincentbernat/lldpd#215]
lldpd running on a 10G Mellanox card (I suspect it happens only with this card type)
after a few days LLDP start to consume 100% CPU, with the following messages filling up /var/log/messages:
15 05:28:31 XXXX lldpd[3471]: error while receiving frame on mlx0: Resource temporarily unavailable

Debugging shows that epoll returns EPOLLERR for the socket. libevent translate it to IN+OUT,
and then lldpd's recvmsg returns -1, errno=EAGAIN.
returning to the event loop, epoll will immediately return again with the same EPOLLERR, causing a 100% cpu loop.

my dirty fix is to add an exit(1) in this situation and have systemd restart lldpd.

**Comment by vincentbernat** [comment]
Could you check if it happens because the interface was down shortly before the problem? You should be able to confirm that from the kernel log. I'll investigate what is the proper thing to do (I suppose, close the socket and reopen it, but the difficulty is to detect the error condition).

**Comment by vincentbernat** [comment]
There is a very similar problem here: http://archives.seul.org/libevent/users/Jul-2013/msg00027.html. Unfortunately, it is on UDP and it was because the `IP_RECVERR` option was set. This is not the case with lldpd. And this option cannot be set for `AF_PACKET`.

**Comment by ortal99** [comment]
Hi,

Thank you for the prompt reply. 
The interface wasn't down. We have more than a hundred servers with this setup and there issue happens every few days on at least one server. 
The kernel docs for select claims that it's legal for "select" to return a read and then the read can return EAGAIN.  In the other hand, the epoll does return an error. I guess you can escalate this issue to libevent, to get the error propagated through the API. 
Another solution is to just ignore the select manual and always reopen the socket on EAGAIN. (I looked at the logs and didn't see Ani occurrence of a single EAGAIN, so I would just ignore that possibility)

Best regards,
Or Tal

**Comment by vincentbernat** [comment]
It seems that if there is an error condition queued on the socket, we have to read it to clear the error condition. There can be an error condition due to timestamping. Could you check with `ethtool -k` if hardware timestamping is enabled (and if you can, try to disable it with `ethtool -K`).

I see that for UDP, when `IP_RECVERR` is not enabled, no error is added in the error queue for the socket. Such a condition doesn't exist for raw packets while they share the code for receiving. When polling, the fact that the error queue is not empty triggers a POLLERR. So, the definitive solution would be to try to get error messages if we get EAGAIN.

**Comment by vincentbernat** [comment]
So, see #216 for a possible fix (waiting for the unittests to run).

**Comment by vincentbernat** [comment]
Tests are fine. Would you be able to test out if it fixes your problem?

**Comment by ortal99** [comment]
Hi,

Thanks for the quick fix! I'll start testing it today.  It will take me a while to fully deploy because I'd like to deploy in on our staging servers and wait for that message in the logs , testing CPU usage before I'll de lot in all our servers. 

Best regards,
Or Tal

**Comment by vincentbernat** [comment]
Since it is not worse than the previous situation, I have merged the PR. Feel free to report any problem (or any success).

**Comment by ortal99** [comment]
Hi, quick update:  it takes a long time to deploy new software in or environment. It will take be another month to fully deploy. Currently I have the patch running on 45 servers, and it does look better than before. 

Best regards,
Or Tal

**Comment by vincentbernat** [comment]
Thanks for the report. I have release 0.9.6 with the assumed fix. If your tests fail at some point, please reopen this issue.
