### ISSUE TITLE
LAG interface issue with TTL=0

### ISSUE THREAD

**Issue by dmitry-kutergin** [vincentbernat/lldpd#221]
When working on LAG HA, we found an issue with our switch-lldpd interaction. When administratively disabling interface (which is the one out of two aggregated into a single LAG interface) switch sends last LLDP packet with TTL=0 before actually disabling the port.
![lldp_ttl0](https://cloud.githubusercontent.com/assets/25600657/22676015/dc1424b4-ec9d-11e6-8df2-9a22c39c90f7.JPG)
After that lldpd through lldpctl reports that there is no LLDP neighbors at all, but another LAG member is still up. The log looks like this:

> Feb 07 02:17:47 cs031 lldpd[105433]: 2017-02-07T02:17:47 [ DBG/event] received something for dpdk_port_0
Feb 07 02:17:47 cs031 lldpd[105433]: 2017-02-07T02:17:47 [ DBG/receive] receive a frame on dpdk_port_0
Feb 07 02:17:47 cs031 lldpd[105433]: 2017-02-07T02:17:47 [ DBG/interfaces] receive PDU from ethernet device dpdk_port_0
Feb 07 02:17:47 cs031 lldpd[105433]: 2017-02-07T02:17:47 [ DBG/receive] decode received frame on dpdk_port_0
Feb 07 02:17:47 cs031 lldpd[105433]: 2017-02-07T02:17:47 [ DBG/decode] decode a received frame on dpdk_port_0
Feb 07 02:17:47 cs031 lldpd[105433]: 2017-02-07T02:17:47 [ DBG/decode] guessed protocol is LLDP (from MAC address)
Feb 07 02:17:47 cs031 lldpd[105433]: 2017-02-07T02:17:47 [ DBG/decode] using decode function for LLDP protocol
Feb 07 02:17:47 cs031 lldpd[105433]: 2017-02-07T02:17:47 [ DBG/lldp] receive LLDP PDU on dpdk_port_0
Feb 07 02:17:47 cs031 lldpd[105433]: 2017-02-07T02:17:47 [ DBG/lldp] extra data after lldp end on dpdk_port_0
Feb 07 02:17:47 cs031 lldpd[105433]: 2017-02-07T02:17:47 [ DBG/decode] search for the same MSAP
Feb 07 02:17:47 cs031 lldpd[105433]: 2017-02-07T02:17:47 [ DBG/decode] MSAP is already known
Feb 07 02:17:47 cs031 lldpd[105433]: 2017-02-07T02:17:47 [ DBG/decode] 1 neighbors for dpdk_port_0
Feb 07 02:17:47 cs031 lldpd[105433]: 2017-02-07T02:17:47 [ DBG/decode] send notifications for changes on dpdk_port_0
Feb 07 02:17:47 cs031 lldpd[105433]: 2017-02-07T02:17:47 [ DBG/event] schedule next cleanup
Feb 07 02:17:47 cs031 lldpd[105433]: 2017-02-07T02:17:47 [ DBG/event] immediate cleanup on port dpdk_port_0 (1486433867, **0**, 1486433867)
Feb 07 02:17:47 cs031 lldpd[105433]: 2017-02-07T02:17:47 [ DBG/event] immediate cleanup on port dpdk_port_1 (1486433867, **0**, 1486433842)

Which means that it received that LLDP packet with TTL=0, updated chassis field c_ttl (in src/daemon/protocol/lldp.c):

```
case LLDP_TLV_TTL:
    CHECK_TLV_SIZE(2, "TTL");
    chassis->c_ttl = PEEK_UINT16;
    ttl_received = 1;
    break;
```

And then since those to ports belongs to a single chassis, and apparently chassis structure is being reused, it applied this c_ttl=0 to both ports of the chassis (in src/daemon/event.c):
```
if (now >= port->p_lastupdate + port->p_chassis->c_ttl) {
	tv.tv_sec = 0;
	log_debug("event", "immediate cleanup on port %s (%lld, %d, %lld)",
				hardware->h_ifname,
				    (long long)now,
				    port->p_chassis->c_ttl,
				    (long long)port->p_lastupdate);
	break;
} 
```

Which effectively renders both ports offline from point of view of lldpctl until any next LLDP packet arrives on either of the ports (up to 30 seconds in our case).

So if it is a bug, is not is better to hold c_ttl in per port structure not shared per_chassis?
If it is a feature how to overcome it in the described above case?
Thanks.

**Comment by vincentbernat** [comment]
The TTL is not part of the MIB, so it's difficult to know if it should be stored in the chassis or the port. However, setting the TTL to 0 is clearly meant to clear only the appropriate MSAP from the database, not a whole chassis.

An easy fix would be to detect this edge case earlier, clear the port and not update the chassis with the new TTL value.

**Comment by dmitry-kutergin** [comment]
So is there a plan to fix this or any possible workaround? I tried starting 2 instances of lldpd but they refuse to start because of some shared socket (/var/run/lldpd.socket as far as I remember).

**Comment by vincentbernat** [comment]
Yes, I plan to fix it. You can run two instances by using a different socket for each (with `-u`) and a different set of interfaces (with `-I`).

**Comment by dmitry-kutergin** [comment]
Cool, thx!

**Comment by vincentbernat** [comment]
If you can, you could test PR #222.
