### ISSUE TITLE
Discarded count not incremented for a malformed LLDP packet

### ISSUE THREAD

**Issue by sriharshamadala** [vincentbernat/lldpd#223]
# Discarded count not incremented for a malformed LLDP packet

When I intentionally write an LLDP packet with zero-padded payload I see the received count incremented but not any of the other counters.

## Steps to reproduce the problem
1. Create a tap interface:
```
ip tuntap add dev tap1 mode tap
ip link set dev tap1 up
```
2. launch the lldp in rx-only mode to listen to the Tap interface, like so:
```
lldpd -r -C tap1
```
3. Followed [this tutorial](http://backreference.org/2010/03/26/tuntap-interface-tutorial/) to create a [tap_client.c](https://github.com/vincentbernat/lldpd/files/784055/tap_client.txt) that writes a custom packet to the tap interface. The packet content is:
        
        lldp_packet_data_buffer[++ii] = htonl(0x0180c200);
        lldp_packet_data_buffer[++ii] = htonl(0x000e0080);
        lldp_packet_data_buffer[++ii] = htonl(0x1688309f);
        lldp_packet_data_buffer[++ii] = htonl(0x88cc0207);
        
        lldp_packet_data_buffer[++ii] = htonl(0x00000000);
        lldp_packet_data_buffer[++ii] = htonl(0x00000000);
        lldp_packet_data_buffer[++ii] = htonl(0x00000000);
        lldp_packet_data_buffer[++ii] = htonl(0x00000000);

        lldp_packet_data_buffer[++ii] = htonl(0x00000000);
        lldp_packet_data_buffer[++ii] = htonl(0x00000000);
        lldp_packet_data_buffer[++ii] = htonl(0x00000000);
        lldp_packet_data_buffer[++ii] = htonl(0x00000000);

        lldp_packet_data_buffer[++ii] = htonl(0x00000000);
        lldp_packet_data_buffer[++ii] = htonl(0x00000000);
        lldp_packet_data_buffer[++ii] = htonl(0x00000000);
        lldp_packet_data_buffer[++ii] = htonl(0x00000000);

        lldp_packet_data_buffer[++ii] = htonl(0x00000000);
        lldp_packet_data_buffer[++ii] = htonl(0x00000000);
        lldp_packet_data_buffer[++ii] = htonl(0x00000000);
        lldp_packet_data_buffer[++ii] = htonl(0x00000000);

        lldp_packet_data_buffer[++ii] = htonl(0x00000000);
        lldp_packet_data_buffer[++ii] = htonl(0x00000000);
        lldp_packet_data_buffer[++ii] = htonl(0x00000000);
        lldp_packet_data_buffer[++ii] = htonl(0x00000000);

        lldp_packet_data_buffer[++ii] = htonl(0x00000000);

4. On another shell run the tcpdump command:
```
tcpdump -vvv -i tap1 'ether proto 0x88cc'
```
## Expected outcome
I would expect the discarded count to be same as received count

## Current outcome
discarded count is not incremented.

lldpcli show statistics
-------------------------------------------------------------------------------
LLDP statistics:
-------------------------------------------------------------------------------
Interface:    tap1
  Transmitted:  0
  Received:     3
  Discarded:    0
  Unrecognized: 0
  Ageout:       0
  Inserted:     0
  Deleted:      0

**Comment by vincentbernat** [comment]
Thanks for reporting! This has been fixed in 32f0dee.
