### ISSUE TITLE
replace custom TLV needs lldpd to be restarted ?

### ISSUE THREAD

**Issue by athreyaDell** [vincentbernat/lldpd#225]
This is not an issue. Its more of a question:

does custom tlv replace need lldpd to be restarted when added to lldpd.conf on a running lldpd.

 configure lldp custom-tlv [add | replace] oui oui subtype subtype
       [oui-info content]

**Comment by vincentbernat** [comment]
When added to `lldpd.conf`, yes. When added through `lldpcli`, no.

**Comment by athreyaDell** [comment]
cool. I was looking for API/functions to serve this purpose. Any pointers would be helpful.

**Comment by vincentbernat** [comment]
Look at `cmd_custom_tlv_set()` function in `src/client/conf-lldp.c`.

**Comment by athreyaDell** [comment]
thanks!

**Comment by athreyaDell** [comment]
So is there a way I could send commands to lldpd over the socket perhaps so that the custom TLVs could be replaced. Or the right way to go about is to update the config file and restart the daemon ?

**Comment by vincentbernat** [comment]
Use lldpcli: `lldpcli configure lldp custom-tlv replace ...`.

**Comment by athreyaDell** [comment]
well there is rejection to use of bash/shell for the purpose..is there a sdk way of doing it ?
rather than writing into config file and restarting daemon

**Comment by vincentbernat** [comment]
Look at `src/lib/lldpctl.h`. `lldpcli` uses this lib, so you can look at its source code to see how it works.
