### ISSUE TITLE
lldp -l is running,  lldpcli  show statistics :  all 0

### ISSUE THREAD

**Issue by nickyticky** [vincentbernat/lldpd#226]
I can't make it work.
BusyBox Linux machine has lldpd -l running.  lldpcli show statistics : all 0 . ??
show chassis seems to be fine.
Ubuntu VM has lldpd running and lldpcli show statistics : Transmitted : 36 ....

Thank you
```

**Comment by vincentbernat** [comment]
I don't understand the question. Explain your problem is more details and post complete output of the commands you use.

**Comment by nickyticky** [comment]
Thank you for your quick response.
The question is:  why lldpd -l is not working (no transmitting/receiving). lldpcli show statistics displays 
LLDP statistics:
-----------------------------------------
Interface:    eth0
Transmitted:     0
Received :         0
Discarded:        0

**Comment by vincentbernat** [comment]
You should have some errors in the logs. If not, run with `lldpd -dddd`.

**Comment by nickyticky** [comment]
Hi,

I built lldpd_1.0.8 for arm64. Here is the issue :  arguments ports and custom-tlv are not recognized by lldpcli. 
What is wrong with my build or config ?
Thank you,

[lldpcli] # configure lldp ports eth0 status tx-only
2020-11-12T05:29:13 [WARN/lldpctl] unknown command from argument 3: `ports`

[lldpcli] # configure lldp custom-tlv oui 33,44,55 subtype 44
2020-11-12T05:29:30 [WARN/lldpctl] unknown command from argument 3: `custom-tlv`

[lldpcli] # configure lldp tx-interval 30

[lldpcli] # configure lldp status rx-and-tx

**Comment by vincentbernat** [comment]
What's the output of `lldpcli -vv`?
