### ISSUE TITLE
Cannot build from lldpd-0.9.7.tar.gz

### ISSUE THREAD

**Issue by tbetker** [vincentbernat/lldpd#229]
Hi Vincent,

I have downloaded https://github.com/vincentbernat/lldpd/archive/0.9.7.tar.gz (from the https://github.com/vincentbernat/lldpd/releases page) and followed the "Install from source" instructions:

```
$ tar xvf lldpd-0.9.7.tar.gz
$ cd lldpd-0.9.7
$ mkdir build
$ cd build
$ ../configure
$ make
```
The first problem is that `configure` is missing. I worked around this by running `./autogen.sh` (right after `cd lldpd-0.9.7`).

The next problem is that `make` fails with the following error message:

```
make[3]: Entering directory 'XXX/lldpd-0.9.7/build/src/daemon'
  CC       liblldpd_la-frame.lo
  CC       liblldpd_la-client.lo
  CC       liblldpd_la-priv.lo
  CC       liblldpd_la-privsep.lo
  CC       liblldpd_la-privsep_io.lo
  CC       liblldpd_la-privsep_fd.lo
  CC       liblldpd_la-interfaces.lo
make[3]: *** No rule to make target '../../../libevent/*.c', needed by '../../libevent/libevent.la'.  Stop.
```
The `libevent` directory is actually completely empty in the .tar.gz (while Git has a lot of files there).

Best regards,
Thomas

**Comment by vincentbernat** [comment]
Hi!

The release tarballs from GitHub are a snapshot of the git repository. You need to also use `git submodule init`. But instead, use the tarballs linked in the instructions: [0.9.7](https://media.luffy.cx/files/lldpd/lldpd-0.9.7.tar.gz).

**Comment by tbetker** [comment]
Hi Vincent,

okay, got it. Would it be possible to add some warning to the GitHub "releases" page that you cannot actually use these tarballs to build _lldpd_ (or that additional steps are required)?

Alternatively, would it be possible to add some explicit text to your "Installation" page that you should not use the tarballs from the GitHub "releases" page?

Thanks,
Thomas

**Comment by vincentbernat** [comment]
I don't see a possibilty to disable the release page or to add a warning text here. I can add a word on the installation page.

**Comment by vincentbernat** [comment]
Done.

**Comment by tbetker** [comment]
Wow, that was fast. Thanks!
