### ISSUE TITLE
FreeBSD and DragonFly: Indirect follow-up on #186

### ISSUE THREAD

**Issue by matsimon** [vincentbernat/lldpd#231]
Hi Vincent

I didn't get the chance to update the FreeBSD ports until now but realized that #186 has somehow come back or actually wasn't gone. I have the strong guess that I didn't thorougly or consistently check with all options back then, my bad. 

Only when I tried all options individually and not the default set of options in the port Makefile that I discovered the build consistently failed only if ``--with-snmp`` was given.

I could confirm this with FreeBSD 10.3, 11.0 and DragonFly BSD 4.8 (on amd64). 

## Minimal steps to reproduce the problem
1. Get the tarball of 0.9.7 (or any version later than 0.9.4 from git, then using autogen.sh)
2. Have net-snmp installed (``pkg install net-snmp``)
3. Compile `lldpd` with `./configure --with-snmp && make`
4. The build fails only if configured ``--with-snmp``, not if not enabled as follows like in #186:

```
interfaces-bsd.c: In function 'ifbsd_macphy':
interfaces-bsd.c:474:2: warning: implicit declaration of function 'typeof' [-Wimplicit-function-declaration]
  typeof(ifmr.ifm_ulist[0]) media_list[32] = {};
  ^
interfaces-bsd.c:474:28: error: expected ';' before 'media_list'
  typeof(ifmr.ifm_ulist[0]) media_list[32] = {};
                            ^
compilation terminated due to -Wfatal-errors.
*** Error code 1
```

The current "working" hack I found to be working on Dragonfly and FreeBSD was as follows - but I'm uncertain if I'm not causing unknown damage elsewhere:
```
--- src/daemon/interfaces-bsd.c.orig    2017-06-11 23:00:17.000000000 +0200
+++ src/daemon/interfaces-bsd.c 2017-06-11 22:56:55.000000000 +0200
@@ -470,7 +470,7 @@
 {
 #ifdef ENABLE_DOT3
        struct ifmediareq ifmr = {};
-#ifdef HAVE_TYPEOF
+#ifdef HOST_OS_OPENBSD
        typeof(ifmr.ifm_ulist[0]) media_list[32] = {};
 #else
        int media_list[32] = {};
```
If HOST_OS_OPENBSD works instead of HAVE_TYPEOF, commit bdc8f796579f0576b62166ed71c761510d9a2499 could be reverted. For regression testing I built lldpd with the exact same configure options on OpenBSD 6.1 where it didn't break the build with or without this change. I did miss NetBSD which I hadn't at hand.

What's your opinion on this?

**Comment by vincentbernat** [comment]
I don't remember if I tested that in #186. There must be some reason that the `configure` check succeeds while the compilation fails. Are you using clang or gcc for compilation?

**Comment by matsimon** [comment]
Hi

The poudriere build environment on FreeBSD 11 uses the system-integrated Clang 3.8.0.
However I've forced the port to be built with GCC at some point for testing but there was no difference.

Dragonfly BSD 4.8 ships with GCC 5.4.1, they have another way of building ports which I haven't explored yet (I think synth).

At that point I don't think there is much chance of a difference with GCC vs. Clang.

**Comment by vincentbernat** [comment]
I would prefer to keep using `typeof`. OpenBSD did change the width of this variable and I believe the other BSD may have to do the same at some point as the current width is too small to support all possible media.

I think the problem is that `typeof` is correctly defined in the default settings, but is not available with the flags added for NetSNMP. Can you get an output of the error when running `make V=1` to get the compiler command-line?

**Comment by matsimon** [comment]
Working on it, but I have currently the guess that using __typeof__ instead of the more GNU C specific typeof might actually work for all BSDs I have yet tested: It fixes FreeBSD and doesn't break OpenBSD.

I came across to 2 things in the clang documentation:
* The parser recognizes “asm” and “typeof” as keywords in gnu* modes; the variants “__asm__” and “__typeof__” are recognized in all modes. (https://clang.llvm.org/docs/UsersManual.html)
* By default, Clang builds C code in GNU C11 (https://clang.llvm.org/compatibility.html)

On FreeBSD I could also confirm that by extending the default CFLAGS by "-std=gnu99" it builds with typeof. (Something I'd like to check back on Dragonfly since it uses GCC as well.)

**Comment by vincentbernat** [comment]
The `AC_C_TYPEOF` autoconf macro should handle that, but it is run without using all flags, so `typeof` may be valid with the flags used by the macro and invalid without it. The NetSNMP CFLAGS should only be used with SNMP related files, so I think this is not the problem. Maybe it's just a matter of putting the macro later. The gcc command-line used to compile `interface-bsd.c` will tell us.

**Comment by vincentbernat** [comment]
@matsimon did you get a chance to grab the command-line used to compile `interface-bsd.c`?

**Comment by matsimon** [comment]
Hi Vincent

Hmm, sorry for not updating you earlier. A FreeBSD ports commiter (looks like his handle on GH is @dbaio) came up with an option in the ports makefile that sets GNU C99 standard which makes the build pass again. (again, only causing issues when linking against Net-SNMP) - Any objections from your side?

**Comment by vincentbernat** [comment]
Do you have a link with the change?

**Comment by dbaio** [comment]
Hi.
With `-std=gnu99` is builds fine.
Here are the build logs with `make V=1`.

[lldpd-0.9.9 FreeBSD 12 amd64-head - default](https://people.freebsd.org/~dbaio/lldpd-0.9.9-12-amd64-head-default.log) :red_circle:
[lldpd-0.9.9 FreeBSD 12 amd64-head - gnu99](https://people.freebsd.org/~dbaio/lldpd-0.9.9-12-amd64-head-gnu99.log) :white_check_mark:

Regards.

**Comment by vincentbernat** [comment]
This is not the first time NetSNMP crazy CFLAGS triggers problem like this. I am pushing a change to try to avoid compiling most of the files with these CFLAGS.

**Comment by vincentbernat** [comment]
I think #270 should also fix the issue in a more future-proof way. In the meantime, pushing `-stdc=gnu99` is a valid workaround.

**Comment by matsimon** [comment]
Hey, thanks the Bug in FreeBSD (for cross-reference) is:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=225595

I think this issue can be closed now. Thanks Vincent and Danilo!

**Comment by dennypage** [comment]
Thank you all!
