### ISSUE TITLE
zsh completion file installed in non-default location

### ISSUE THREAD

**Issue by woodsb02** [vincentbernat/lldpd#232]
# Bug description
The zsh completion file `_lldpcli` is installed in `$(zshcompletiondir)` which is currently set in `src/client/Makefile.am` to `$(datadir)/zsh/vendor-completions`.

The default zsh codebase looks for completion files in `DATADIR/zsh/site-functions`, and therefore does not find the lldpcli completion file.

Debian Linux adds additional directories to the fpath for search for zsh loadable functions [1, 2, 3], however this is not the case with all Linux/BSD/Unix distributions.
[1] https://anonscm.debian.org/cgit/collab-maint/zsh.git/tree/debian/rules#n32
[2] https://anonscm.debian.org/cgit/collab-maint/zsh.git/tree/debian/README.Debian#n51
[3] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=620452

## Steps to reproduce the problem

 1. Install `lldpd` on an operating system which does not add $(datadir)/zsh/vendor-completions to the default zsh fpath.

 2. Attempt zsh completions by typing "lldpcli " and then hitting the TAB key.
 
## Expected outcome

zsh should provide valid lldpcli completions:
```
# lldpcli <TAB>
configure    -- Change system settings
exit         -- Exit interpreter
help         -- Get help on a possible command
pause        -- Pause lldpd operations
resume       -- Resume lldpd operations
show         -- Show running system information
unconfigure  -- Unconfigure system settings
update       -- Update information and send LLDPU on all ports
watch        -- Monitor neighbor changes
```

## Current outcome

zsh cannot find lldpcli completions, so instead provides normal completions for the files in the present working directory.

```
# lldpcli <TAB>
list    of     files    in     present     working     directory
```

# Additional information
FreeBSD bug report: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=220244
alt linux package spec showing _lldpcli completion file being moved: https://packages.altlinux.org/en/Sisyphus/srpms/lldpd/spec

**Comment by vincentbernat** [comment]
Thanks, I didn't know!
