### ISSUE TITLE
Active/Passive handling for team'd network devices seems to be missing

### ISSUE THREAD

**Issue by athienem** [vincentbernat/lldpd#234]
When running 0.9.7 on a machine with a configured active/passive pair of interfaces bundled together to one team, the machine is losing packets on each lldp beacon transmission.

The problem looks to be exactly same known issue as exists with bonding as described at https://github.com/vincentbernat/lldpd/wiki/Status-of-bonding-support.

Sniffing on eth0 (active) and eth1 (passive) tcpdump will show packets with the port id of eth0 and team0 leaving on eth0 and packets with the port id of eth1 leaving on eth1.
Packets on both eth0 as well as eth1 show the same source mac address as the mac addresses have been changed.

The steps taken for bonding should probably be applied to teams as well, rather than just returning early as is the current code.

**Comment by vincentbernat** [comment]
Yes, we can apply the same strategy as for bonds. I need to investigate a bit how teams differ. Could you give the output of `ip -d l l dev team0` and `ip -d l l dev eth0` (assuming `eth0` is part of `team0`)? If the active/backup information was provided to the kernel, this should be easy, but from what I understand, this is not the case.

**Comment by athienem** [comment]
ip does not have the necessary information. It does know about master and slave relations but nothing about active/passive state as far as I can see.

```
[root@bb1 ~]# for dev in team0 enp6s0 enp7s0; do ip -d l l dev $dev; done
8: team0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT qlen 1000
    link/ether 00:25:90:33:0c:ce brd ff:ff:ff:ff:ff:ff promiscuity 0
    team addrgenmode eui64
2: enp6s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master team0 state UP mode DEFAULT qlen 1000
    link/ether 00:25:90:33:0c:ce brd ff:ff:ff:ff:ff:ff promiscuity 0
    team_slave addrgenmode eui64
4: enp7s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master team0 state UP mode DEFAULT qlen 1000
    link/ether 00:25:90:33:0c:ce brd ff:ff:ff:ff:ff:ff promiscuity 0
    team_slave addrgenmode eui64
[root@bb1 ~]#
```

That matches up with what's available under /sys/class/net/

Unfortunately I do not know enough about the netlink details to really grok https://github.com/jpirko/libteam/wiki/Infrastructure-Specification on first reading, but it seems a userspace app should easily be able to get link state through netlink or possibly even better through libteam.

using the teamnl tool, which uses libteam.so, the data seems to be available and easily queryable:

```
[root@bb1 ~]# teamnl team0 getoption mode
activebackup
[root@bb1 ~]# teamnl team0 getoption activeport
4
[root@bb1 ~]# ip link show enp7s0
4: enp7s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master team0 state UP mode DEFAULT qlen 1000
    link/ether 00:25:90:33:0c:ce brd ff:ff:ff:ff:ff:ff
[root@bb1 ~]#
```

Looking at https://github.com/jpirko/libteam/blob/master/include/team.h seems to offer all the functions one might need.

**Comment by vincentbernat** [comment]
So, in fact, it's easy to know if an interface is part of a team. The only missing bit is how to get the real MAC address of an interface. Do you have it in `teamnl ports` or `teamnl options`?

**Comment by athienem** [comment]
I am not seeing it in `teamnl ports` nor `teamnl options`:

```
[root@bb1 ~]# teamnl team0 ports
 4: enp7s0: up 1000Mbit FD
 2: enp6s0: up 1000Mbit FD
[root@bb1 ~]# teamnl team0 options
 queue_id (port:enp7s0) 0
 priority (port:enp7s0) 100
 user_linkup_enabled (port:enp7s0) false
 user_linkup (port:enp7s0) true
 enabled (port:enp7s0) true
 queue_id (port:enp6s0) 0
 priority (port:enp6s0) 0
 user_linkup_enabled (port:enp6s0) false
 user_linkup (port:enp6s0) true
 enabled (port:enp6s0) false
 activeport 4
 mcast_rejoin_interval 0
 mcast_rejoin_count 1
 notify_peers_interval 0
 notify_peers_count 1
 mode activebackup
[root@bb1 ~]#
```

But there seems to be a function in libteam to get the original hwaddr from the interface information structure at https://github.com/jpirko/libteam/blob/master/libteam/ifinfo.c#L603:

```
/**
 * @param ifinfo	ifinfo structure
 *
 * @details Get ifinfo original hardware address.
 *
 * @return Pointer to memory place where hwaddr is.
 **/
TEAM_EXPORT
char *team_get_ifinfo_orig_hwaddr(struct team_ifinfo *ifinfo)
{
	return ifinfo->orig_hwaddr;
}

/**
 * @param ifinfo	ifinfo structure
 *
 * @details Get ifinfo original hardware address length.
 *
 * @return Hardware address length.
 **/
TEAM_EXPORT
uint8_t team_get_ifinfo_orig_hwaddr_len(struct team_ifinfo *ifinfo)
{
	return ifinfo->orig_hwaddr_len;
}
```

**Comment by vincentbernat** [comment]
OK, then I'll make a first patch treating a team like a bond but with the downside to not know the original MAC address. Then, I'll do a second one to learn the real MAC address using libteam.

**Comment by vincentbernat** [comment]
So, the latest commit fixes half of the problem. Linking to libteam just to get the MAC address from teamd seems a bit expensive (all the more I am in a chroot and I don't have an easy access to the Unix socket sets by teamd). What could be done is retrieving the permanent MAC address using ethtool. This would be done only for bond devices and team devices. This would remove the need to parse `/proc/net/bond` too. But this could be a bit disruptive for some users.

**Comment by vincentbernat** [comment]
Added an additional commit to use ethtool to get device MAC address if possible.

**Comment by athienem** [comment]
Had a quick look at the code. Change looks good as far as I can see.
I'll build current HEAD later tonight and test to see if it results in a stable team link without confused switches.

**Comment by athienem** [comment]
Installed the master on a test machine that experienced the issues described before.

Looks much better now, as seen from the switch:

```
  Local Port   : 23
  ChassisType  : mac-address
  ChassisId    : 00 e0 81 46 7f de
  PortType     : mac-address
  PortId       : 00 e0 81 46 7f de
  SysName      : sysiphus.bawue.net
  System Descr : CentOS Linux 7 (Core) Linux 3.18.44-20.el7.x86_64 #1 SMP ...
  PortDescr    : enp4s4f0
------------------------------------------------------------------------------
  Local Port   : 24
  ChassisType  : mac-address
  ChassisId    : 00 e0 81 46 7f de
  PortType     : mac-address
  PortId       : 00 e0 81 46 7f df
  SysName      : sysiphus
  System Descr : CentOS Linux 7 (Core) Linux 3.18.44-20.el7.x86_64 #1 SMP ...
  PortDescr    : enp4s4f1
```

PortIds are using different mac addresses now, so that looks like it is working correctly.

Thank you for the quick turnaround on the fix.

**Comment by vincentbernat** [comment]
Thanks. I'll make a release soon.
