### ISSUE TITLE
(low): More consistent JSON data

### ISSUE THREAD

**Issue by Bobobo-bo-Bo-bobo** [vincentbernat/lldpd#236]
Not a bug per se, more a feature request ;)

While doing mass import of JSON files generated with:

`lldpd -f json`

on Debian 9 (x86_64) (`lldpd 0.9.6`) I've stumbled about the somehow inconsistent format
of the JSON output.

Almost all systems have multiple NICs, hence the structure
is an array (as it would be expected):

```{
  "lldp": {
    "interface": [
      {
        "em0": {...
```

but for systems with a single NIC the structure for the interface is not a list (with just one element), but:

```{
  "lldp": {
    "interface": {
        "eth0": {...
```

The same effect can be observed for the `mgmt-ip` (`"mgmt-ip": [ "192.168.1.202",
"fd9c:df44:fce4:e77a:4853:3716:7f61:d483" ]` for a mutli-valued entry vs. `"mgmt-ip": "fd9c:df44:fce4:e77a:5018:71de:be5e:b226"` for a single-valued entry) and - perhaps - 
for the `capability` (and maybe other value I didn't found yet).

Is it possible to generate a more "consistent" JSON output for possible multi-valued entries?
So they will alway be represented as an array (for single values as an array with only one element).

This may simplify parsing of the generated JSON data as the parser doesn't need to peek at those data structures before handling them.

**Comment by vincentbernat** [comment]
There is a configure option to get a more consistent output. This is `--enable-json0`. What could be done is to add a `-f json0` format to force this format.

**Comment by bastelfreak** [comment]
Hi @vincentbernat,

I'm automatically parsing the json output with facter[0]. Would it be possible that you add the suggested -f json0 option?

[0] https://docs.puppet.com/facter/3.7/

**Comment by Bobobo-bo-Bo-bobo** [comment]
When build with `--enable-json0` the output looks right.

But it re-introduce the previous error of generating invalid JSON if the description of the remote operating system contains line break(s) as it can often be seen when the remote end is a
switch. In this case the observed value of, e.g.:

```
1920-8G Switch Software Version 5.20.99, Release 1108
Copyright(c)2010-2015 Hewlett-Packard Development Company, L.P.
```

will result in:

```
1920-8G Switch Software Version 5.20.99, Release 1108 \ 0x0c \ 0x0a
Copyright(c)2010-2015 Hewlett-Packard Development Company, L.P.
```
(in bytes: `5c 0d 5c 0a`)
instead of:

```
1920-8G Switch Software Version 5.20.99, Release 1108 \r\n
Copyright(c)2010-2015 Hewlett-Packard Development Company, L.P.
```
(in bytes: `5c 72 5c 6e`)

**Comment by vincentbernat** [comment]
Which version of lldpd are you using?

**Comment by vincentbernat** [comment]
OK, I found the bug.

**Comment by vincentbernat** [comment]
See commit 04a15281a75c.
