### ISSUE TITLE
Question: At what point is lldpd available for query, on system boot?

### ISSUE THREAD

**Issue by davidhousedev** [vincentbernat/lldpd#241]
I am trying to execute lldpd from a Python script which is initiated by a `systemd` unit. When I run my script after my computer has fully booted up, it runs without a problem. However, when the unit executed my script on system boot, the lldpd service returns nothing. From what I can tell, the lldp daemon is still starting up even after its service has already started.

Is there a way to guarantee that lldpd is ready to send requests through `systemd`?

Here is my Python script, 3.6 required:
```python
import subprocess
result = subprocess.check_output('lldpctl -f keyvalue', shell=True)
```

And here is my unit file for initiating the lldp query:
```
[Unit]
Description=Queries over LLDP
After=syslog.target networking.target lldpd.service

[Service]
Type=simple
WorkingDirectory=/scripts/
ExecStart=/scripts/lldp_script.py

[Install]
WantedBy=multi-user.target
```

Thank you for your time.

**Comment by vincentbernat** [comment]
Once the service is started, lldpd is available for query. However, there is no guarantee that neighbors are discovered or not. Your best bet is to poll every second until you get something.

**Comment by davidhousedev** [comment]
Thank you, Vincent!
