### ISSUE TITLE
Can't access LLDP-MED using lldpd

### ISSUE THREAD

**Issue by yj48** [vincentbernat/lldpd#242]
Calling `lldpd -M 2` (or 1, 3 or 4) brings error message "-M requires an argument between 1 and 4" along with options list. Doesn't happen when doing something like `lldpd -d -D main`, and `lldpd` daemon runs successfully.

Probably extremely small, most likely me doing something wrong, but any help much appreciated!

**Comment by vincentbernat** [comment]
Which version of lldpd are you using? Could you also tell me the output of `ldd $(which lldpd) | grep libbsd`?

**Comment by yj48** [comment]
Using version 0.9.8. Output of ldd is:
        
libbsd.so.0 => /usr/local/lib/libbsd.so.0 (0x29580000)
libbsd.so.0 (LIBBSD_0.0) => /usr/local/lib/libbsd.so.0
libbsd.so.0 (LIBBSD_0.2) => /usr/local/lib/libbsd.so.0
/usr/local/lib/libbsd.so.0:

**Comment by vincentbernat** [comment]
Would you know which version of libbsd this is? The conversion is done with `strtonum()` from libbsd (if present) or fallback to an included copy (if not present).

**Comment by yj48** [comment]
Version `0.4.2`, which I believe doesn't include `strtonum()`, although please correct me if you think I'm wrong. There's the issue, thank you very much for your help!

**Comment by vincentbernat** [comment]
0.4.2 includes strtonum and uses almost the same code that the one which is embedded in lldpd (and the same one as more recent libbsd). So, it doesn't seem to be the culprit. If you compiled lldpd yourself, can you add some quick debug code in `src/daemon/lldpd.c`? Search for `lldpmed = strtonum(optarg, 1, 4, &errstr);` and add `fprintf(stderr, "--%s--", optarg);` before this line.

**Comment by yj48** [comment]
Result gives `--2--` as expected, and then carries on with the "M requires an argument....." message

**Comment by vincentbernat** [comment]
So, can you add a printf after `strtonum()`. Something like:

```
fprintf(stderr, "lldpmed = %d, errno = %d, errstr=%s\n", lldpmed, errno, errstr);
```

**Comment by yj48** [comment]
lldpmed = 0, errno = 34 and errstr = too small.

Thanks again for your help!

**Comment by vincentbernat** [comment]
Do you know how to use gdb? This should be easy enough:

```
gdb $(which lldpd) --args -M 2
b strtonum
run
```

It should stop on strtonum. First, confirm that the first argument is "2", minval is 1 and maxval is 4. Then, you can step in the function using `next`. At some point, you'll pass `strtoll()`. Once past this function, use `print ll`. You should get 2. If `gdb` is not usable, we'll use the embedded `strtonum()` instead, since it's easier to debug with printf.

**Comment by vincentbernat** [comment]
```
gdb --args $(which lldpd) -M 2
```

**Comment by yj48** [comment]
Problem fixed, in `strtonum` putting `LL` after the 1 and 4 makes it work. Just fyi, a 32 bit processor is being used and it's being cross compiled, incase this issue comes up again with someone else

**Comment by vincentbernat** [comment]
It means there is an header missing. When compiling, don't you get a warning for `liblldpd_la-lldpd.lo`?

**Comment by vincentbernat** [comment]
Also, if you can `grep libbsd_ config.log` to check what was used to compile with libbsd. There may be some magic stuff that's not compatible with cross-compiling.

**Comment by vincentbernat** [comment]
After digging a bit my memory, I remember there is an issue with cross-compilation with libbsd: the headers of the host may be used. See https://patchwork.ozlabs.org/patch/659019/, except the failure happened far earlier. I have added additional checks to catch this issue but they don't seem to prevent the failure in your case. A `grep isystem config.log` would help to know what has been computed. Only pkg-config 0.29.2 does the right thing for cross-compilation.

**Comment by vincentbernat** [comment]
A quick workaround to disable libbsd once the issue is detected is to add `libbsd_CFLAGS=no` to `./configure`. It would be better if there was a way to detect the brokenness.

**Comment by vincentbernat** [comment]
Cannot go forward without more information. Please reopen if the issue still exists (with requested information).
