### ISSUE TITLE
TLV send from PD does not show new allocated power for PSE

### ISSUE THREAD

**Issue by mikem388** [vincentbernat/lldpd#243]
I have lldp working on an embedded device using Android. Everything appears to work correctly. However, I went for testing at a lab prior to getting certified and they said there is an error in the protocol. I send a message the says I have 13 watts and request 24.6 watts. The PSE send back a message that says I requested 24.6 watts and it allocated 24.6. The next message I send has the original values, 13 and 24.6.
The lab says I should be sending a message with 24.6 allocated and 24.6 requested.

My conf file looks like this:
configure system hostname "Company"
configure system description "Company Device"
configure system interface pattern eth0
configure dot3 power pd supported enabled powerpairs signal class class-4 type 2 source pse priority high requested 24600 allocated 13000

**Comment by vincentbernat** [comment]
Currently lldpd only sends static TLV. You need to plug your own logic with an external application to modify the power TLV to update the values. Reading the spec, it seems that updating the allocated value with the value received from the PSE would be the expected behaviour for a PD. I'll try to implement that.

**Comment by mikem388** [comment]
I have a solution that works for me, a one line change to lldp_decode. In the LLDP_TLV_DOT3_POWER case after the 802.3at power TLV is decoded add:
        hardware->h_lport.p_power.allocated = port->p_power.allocated;

**Comment by vincentbernat** [comment]
I'll do something similar, guarded with a condition to check that the current role is PD.
