### ISSUE TITLE
Can Chassis ID's value  be locally assigned ?  It seems to be Mac address or system name now. 

### ISSUE THREAD

**Issue by vic-lin-accton** [vincentbernat/lldpd#244]
Hi Sir,

   I can not find any instruction to modify Chassis ID using our own local use byte string.
Check those Usage doc, it seems to us only use MAC to compute or system name
for Chassis ID.

- Vic

**Comment by vincentbernat** [comment]
Yes, this is currently not possible. I'll try to add this possibility in the next month.

**Comment by vincentbernat** [comment]
Fixed by #263.
