### ISSUE TITLE
After lldpd got SIGKILL, respawn didn't work

### ISSUE THREAD

**Issue by xiesheng211** [vincentbernat/lldpd#245]
# Bug description
I realized the issue when I restarted the lldpd several times within short time period. Then I found lldpd failed to respawn and kept the state:

status lldpd
lldpd start/running

After I looked at the log, I found that there was a slow shut down which 5 seconds after we sent the SIGTERM to lldpd service, if still running, upstart job will send SIGKILL to lldpd. But after that the lldpd didn't respawned by upstart.(There is no limit for respawn).

lldpd version is 0.9.4

## Steps to reproduce the problem

"killall -s 9 lldpd" can reproduce the problem:

        init: lldpd main process (21023) killed by KILL signal
	init: lldpd main process ended, respawning
	lldpd[22027]: unable to create control socket because it already exists
	lldpd[22027]: check if another instance is running
	lldpd[22027]: another instance is running, please stop it
	lldpd[22027]: giving up
	init: lldpd main process (22027) terminated with status 1
	init: lldpd main process ended, respawning

After this, there is no log shows that it respawned.

However, "restart lldpd" can recover from this state:

        lldpd[21023]: unable to create control socket because it already exists
        lldpd[21023]: check if another instance is running
        lldpd[21023]: unable to connect to socket /var/run/lldpd.socket: Connection refused
        lldpd[21023]: old control socket is present, clean it

**Comment by vincentbernat** [comment]
❦ 24 septembre 2017 22:38 GMT, Sheng Xie <notifications@github.com> :

> After this, there is no log shows that it respawned.

And no process lldpd either or is there a process remaining?
-- 
Writing is easy; all you do is sit staring at the blank sheet of paper until
drops of blood form on your forehead.
		-- Gene Fowler

**Comment by xiesheng211** [comment]
There is no process remaining.
    ps aux | grep lldpd
    root      3308  0.0  0.0  10708  2204 pts/2    S+   23:41   0:00 grep --color=auto lldpd

**Comment by vincentbernat** [comment]
The fact a process is still here after a short time is expected. Signals are asynchronous. "D" state means the process is currently in kernel-land and not killable. I wouldn't expect it to be in this state long enough for you to observe it but it seems the case.

Also, the fact that it could take 5 seconds for lldpd to stop is also a mystery. Is it a system with many ports?

Are you on CentOS 6 or Ubuntu something? It's odd to be in `start/running` (the normal state) while there is no process at all remaining.

**Comment by xiesheng211** [comment]
Still don't know why taking 5 seconds to stop. My system has 7 ports is on Ubuntu. I think the problem may also relate to upstart because even though lldpd said "another instance is running", it exist with code 1 and upstart respawn should work whenever the control socket cannot be connected.

**Comment by vincentbernat** [comment]
So, you are on Ubuntu Trusty? I'll have to try to reproduce this issue. There is a small interaction between lldpd and upstart to let lldpd tell it's ready. Maybe there is a bug around that.

**Comment by xiesheng211** [comment]
Yes mine is on Ubuntu. I guess you are talking about the "expect stop". I also tried to think about if that can cause the problem but couldn't figure out.

**Comment by vincentbernat** [comment]
Which Ubuntu, Trusty? The `expect stop` should stay as lldpd will stop itself so that Upstart will resume it. Maybe that's where the problem is.

**Comment by xiesheng211** [comment]
System is on top of Ubuntu version is 14.04. It is trusty.

NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"

**Comment by vincentbernat** [comment]
After testing a bit, it's easy to reproduce. This seems a bug with upstart not handling respawning when the job stops before sending SIGSTOP. This has already been [reported](https://bugs.launchpad.net/upstart/+bug/712351) but without any answer (which is not uncommon with Upstart). As Ubuntu discontinued any interest in Upstart, I don't see how to fix that.

Maybe we can workaround your use case. Why are you using "-9". The problem arises when the monitor process is killed first. This is the one monitored by upstart but this is not the one having the socket. It's not possible to ask upstart to monitor the other process (which is a child of the main one and therefore, upstart cannot know when it is stopped). If you kill the monitor process with SIGTERM instead, it will kill its child first. Another solution would be to kill the child instead of the monitor. The monitor will terminate after that: `killall -s 9 -u _lldpd lldpd`.

**Comment by vincentbernat** [comment]
OK, I didn't read correctly your initial bug report. We can either increase `kill timeout` or we can discover why it takes 5 seconds for lldpd to stop (something that shouldn't happen). Is there anything in the logs about lldpd when it is stopped that would help understand that?

**Comment by xiesheng211** [comment]
Not sure increasing timeout is safe to get rid of this problem, as there is another way to make this issue happen without SIGKILL, keeping sending SIGTERM also can cause the problem:
"for i in $(seq 1000); do killall lldpd; done"
Unfortunately, the log which shut down lldpd reached 5 second timeout get lost. I don't think is timeout is common but I will update on this page once I get another 5 seconds timeout happen.

**Comment by vincentbernat** [comment]
If the timeout doesn't happen often, I think I will just merge #247 (just need to test it).

**Comment by vincentbernat** [comment]
No luck, bug is still here with `expect fork`.

**Comment by vincentbernat** [comment]
If changing logging priority of upstart (with `initctl log-priority debug`), I get:

```
Oct  2 19:43:32 VM-15b0f0b1-a8af-4407-9f06-eaa99e0d968b kernel: [ 1414.460677] init: lldpd state changed from running to stopping
Oct  2 19:43:32 VM-15b0f0b1-a8af-4407-9f06-eaa99e0d968b kernel: [ 1414.461053] init: lldpd state changed from stopping to killed
Oct  2 19:43:32 VM-15b0f0b1-a8af-4407-9f06-eaa99e0d968b kernel: [ 1414.461097] init: lldpd state changed from killed to post-stop
Oct  2 19:43:32 VM-15b0f0b1-a8af-4407-9f06-eaa99e0d968b kernel: [ 1414.461134] init: lldpd state changed from post-stop to starting
Oct  2 19:43:32 VM-15b0f0b1-a8af-4407-9f06-eaa99e0d968b kernel: [ 1414.461349] init: lldpd state changed from starting to security
Oct  2 19:43:32 VM-15b0f0b1-a8af-4407-9f06-eaa99e0d968b kernel: [ 1414.461389] init: lldpd state changed from security to pre-start
Oct  2 19:43:32 VM-15b0f0b1-a8af-4407-9f06-eaa99e0d968b kernel: [ 1414.461426] init: lldpd state changed from pre-start to spawned
Oct  2 19:43:32 VM-15b0f0b1-a8af-4407-9f06-eaa99e0d968b kernel: [ 1414.463810] init: lldpd main process (3653)
Oct  2 19:43:32 VM-15b0f0b1-a8af-4407-9f06-eaa99e0d968b kernel: [ 1414.465462] init: lldpd main process (3653) executable changed
Oct  2 19:43:32 VM-15b0f0b1-a8af-4407-9f06-eaa99e0d968b lldpd[3653]: unable to create control socket because it already exists
Oct  2 19:43:32 VM-15b0f0b1-a8af-4407-9f06-eaa99e0d968b lldpd[3653]: check if another instance is running
Oct  2 19:43:32 VM-15b0f0b1-a8af-4407-9f06-eaa99e0d968b lldpd[3653]: another instance is running, please stop it
Oct  2 19:43:32 VM-15b0f0b1-a8af-4407-9f06-eaa99e0d968b lldpd[3653]: giving up
Oct  2 19:43:32 VM-15b0f0b1-a8af-4407-9f06-eaa99e0d968b kernel: [ 1414.469948] init: lldpd main process (3653) terminated with status 1
Oct  2 19:43:32 VM-15b0f0b1-a8af-4407-9f06-eaa99e0d968b kernel: [ 1414.469963] init: lldpd main process ended, respawning
Oct  2 19:43:32 VM-15b0f0b1-a8af-4407-9f06-eaa99e0d968b kernel: [ 1414.470041] init: lldpd state changed from spawned to post-start
Oct  2 19:43:32 VM-15b0f0b1-a8af-4407-9f06-eaa99e0d968b kernel: [ 1414.470302] init: lldpd state changed from post-start to running
```

For some reason, the instance transition from spawned to post-start despite status error 1. The best I can do is to start with `-d`. Like what was done in #248.
