### ISSUE TITLE
10 second requirement for Power via MDI TLV

### ISSUE THREAD

**Issue by mikem388** [vincentbernat/lldpd#249]
From 802.3at Clause 33.6.2: 
Under normal operation, an LLDPDU containing a Power via MDI TLV with an updated value for "PSE allocated power value" field shall be sent within 10 seconds of receipt of a LLDPDU containing a Power via MDI TLV where the "PD requested power value" is different from the previously communicated value.

Testing showed various times up to about 25 seconds. I believe we were waiting for the 30 second timer. I changed the timer to 10 seconds to verify this and met the timing requirement. However I didn't want to run the loop that often. I put a call to "levent_send_now" at the end of the LLDP_TLV_DOT3_POWER case in lldp_decode and now send the PDU back to the PSE instantly.

Mike

**Comment by vincentbernat** [comment]
❦ 12 octobre 2017 14:36 -0700, mikem388 <notifications@github.com> :

> From 802.3at Clause 33.6.2: 
> Under normal operation, an LLDPDU containing a Power via MDI TLV with
> an updated value for "PSE allocated power value" field shall be sent
> within 10 seconds of receipt of a LLDPDU containing a Power via MDI
> TLV where the "PD requested power value" is different from the
> previously communicated value.
>
> Testing showed various times up to about 25 seconds. I believe we were
> waiting for the 30 second timer. I changed the timer to 10 seconds to
> verify this and met the timing requirement. However I didn't want to
> run the loop that often. I put a call to "levent_send_now" at the end
> of the LLDP_TLV_DOT3_POWER case in lldp_decode and now send the PDU
> back to the PSE instantly.

That's the right thing to do I think.

I didn't forget your other issue, I just lack time to integrate it
correctly (with tests).

**Comment by mikem388** [comment]
Thank you!

________________________________________
