### ISSUE TITLE
lldpcli zombie

### ISSUE THREAD

**Issue by tbetker** [vincentbernat/lldpd#250]
When configured without privilege separation, starting `lldpd` creates a `lldpcli` zombie -- the daemon never calls waitpid() for the process forked by lldpd_configure().

This does not occur with privilege separation because sig_chld() in src/daemon/priv.c happens to call waitpid(-1, ...) if a SIGCHLD is received and the monitored child is still running.

I am attaching a quick hack to get rid of the zombie; it sets SIGCHLD to SIG_IGN, so terminated children will not become zombies. This may not be entirely clean, but it works for me ...

Note that there are some conditions for this patch:
* We don't want to ignore SIGCHLD before lldpd_get_lsb_release() since the latter uses waitpid().
* We assume that nobody will call wait() or waitpid() afterwards, as this may block forever.
* We rely on `ldpcli`, if running, not to exit before we enter levent_loop(); it sends at least a "resume" command and waits for the response (even if /etc/lldpd.conf is missing or empty).

[lldpcli-zombie.patch](https://github.com/vincentbernat/lldpd/files/1400835/lldpcli-zombie.patch.txt)

**Comment by vincentbernat** [comment]
I agree with your analysis but I have pushed another fix in #251. This way, I get a similar code path with and without privilege separation. I didn't test it much. If the test passes, could you check it fixes your problem too?

An alternative would be to ignore SIGCHLD in both cases but I am afraid to introduce some regressions.
