### ISSUE TITLE
Ethernet Alliance Acceptance

### ISSUE THREAD

**Issue by mikem388** [vincentbernat/lldpd#254]
Vincent,
Just wanted to let you know with my two changes, I passed the certification for Ethernet Alliance acceptance.

Mike

**Comment by vincentbernat** [comment]
❦ 15 novembre 2017 19:12 GMT, mikem388 <notifications@github.com> :

> Just wanted to let you know with my two changes, I passed the
> certification for Ethernet Alliance acceptance.

Great! Sorry for being slow to integrate them. Still have to find some
time.
-- 
Use uniform input formats.
            - The Elements of Programming Style (Kernighan & Plauger)
