### ISSUE TITLE
Add fedora 27 packages

### ISSUE THREAD

**Issue by bastelfreak** [vincentbernat/lldpd#255]
Hi @vincentbernat, thanks for the great project!
Fedora 27 got released a few days ago. Would it be possible to create a repo for that as well?

**Comment by vincentbernat** [comment]
It's not available on openSUSE Build Service. Note however, lldpd is available "natively": https://admin.fedoraproject.org/pkgdb/package/rpms/lldpd/

**Comment by vincentbernat** [comment]
I have enabled the repository on OBS.
