### ISSUE TITLE
Question about the sequence of custom tlv is kept ?

### ISSUE THREAD

**Issue by viclin999** [vincentbernat/lldpd#258]
Edited: see question below.

**Comment by viclin999** [comment]
Hi Vincent,

One simple question is if TX side send  a sequence of same oui/subtype  TLVs content are a,b,c , will RX side 'lldpcli show nei' see the same sequence in a,b,c without random or any interruption by any other TLV ?     

Thanks for your answer in advance

**Comment by vincentbernat** [comment]
I didn't test it myself, but from the code source, custom TLV are stored in a list (in the same order as received) and they are displayed in the same way. So, yes.

**Comment by viclin999** [comment]
OK. Thanks again
