### ISSUE TITLE
update ubuntu trusty package to 0.7.8 (or later)

### ISSUE THREAD

**Issue by nuttle** [vincentbernat/lldpd#260]
# Bug description

The ubuntu trusty distribution of lldpd is at 0.7.7 ([trusty/lldpd](https://packages.ubuntu.com/trusty/net/lldpd)).  This is a bit unfortunate, as 0.7.8 has a couple of fixes that are of particular interest in the environment at my work.  Specifically, this subset (taken/edited from [lldpd/NEWS](https://github.com/vincentbernat/lldpd/blob/master/NEWS)):

```
lldpd (0.7.8)
  * Changes:
    + Ability to override the hostname.
  * Fixes:
    + Fix lldpcli behaviour when suid.
```

The second of these in fairly minor; there's an easy workaround.  The first of these is a very significant limitation for us; we have a large class of machines which will be on trusty for some time.

I realize trusty is old and much less active, and that we can solve this ourselves.  But, lldpd is really useful, and I suspect this would be helpful to many users.  Would it be possible to update the trusty package, please?  Thanks very much for considering this!

## Steps to reproduce the problem

 1. `sudo apt-get install lldpd`; observe the bugs present in 0.7.7 and fixed in 0.7.8.
 
## Expected outcome

Consider moving up at least to 0.7.8, but possibly to 0.7.19 (same as xenial); bugs are gone.

## Current outcome

Fixes from 0.7.8 are missing in 0.7.7.

**Comment by vincentbernat** [comment]
Hello,

Unfortunately, I cannot do much about that. Ubuntu only accept updates if they fix grave bugs or security issues. It's unlikely they accept a new version only for additional features. What you can do is to fetch packages from here instead: https://software.opensuse.org/download.html?project=home:vbernat&package=lldpd. You'll get the latest version of lldpd.

**Comment by nuttle** [comment]
Thanks!

**Comment by nuttle** [comment]
As it happens, we have a local repo, set up using [vincent.bernat.im/en/blog/2014-local-apt-repositories](https://vincent.bernat.im/en/blog/2014-local-apt-repositories), so "Thanks" twice.  :-)
