### ISSUE TITLE
valgrind on lldp

### ISSUE THREAD

**Issue by dips2178** [vincentbernat/lldpd#262]
Im using lldpd-0.9.5. 

lldpd works fine on its own.

Wanted to run valgrind on it to check for memory leaks. But now it  fails to start with foll errors :

unable to create control socket because it already exists
unable to create control socket because it already exists
check if another instance is running
check if another instance is running
unable to connect to socket /var/run/lldpd.socket: Connection refused
[WARN/control] unable to connect to socket /var/run/lldpd.socket: Connection refused
old control socket is present, clean it
[INFO/main] old control socket is present, clean it

Am I missing something ? Valgrind runs as root.
Has anyone had success with valgrind for lldpd ?

Thanks,
Deepa.

**Comment by vincentbernat** [comment]
I am also using valgrind and didn't run into any trouble with
lldpd. From your messages, it seems to work. Be sure to run with `-dd`
for lldpd to not run in background.

I am using this command (after compiling lldpd):

```
sudo libtool execute valgrind --suppressions=src/daemon/lldpd.supp
--show-leak-kinds=all --leak-check=full src/daemon/lldpd -dddd -L
$PWD/src/client/lldpcli
```

Another solution is to configure wth `--enable-sanitizers`. With a
version of gcc or clang recent enough, you'll also get memory leak
checks.
