### ISSUE TITLE
privilege separation broken on NetBSD 7.x and 8.x

### ISSUE THREAD

**Issue by mike-pumford** [vincentbernat/lldpd#264]
lldpd does not work out of the box on NetBSD 7.x and 8.x if privilege separation is enabled. I believe this is down to the fact that the code is assuming that fork and vfork are identical. This is true on a lot of systems but is not on NetBSD. In particular NetBSD suspends the parent process until the child exists or calls execve().This means that priv_init() gets stuck forever on the child as the parent process never gets to priv_loop();

This is part of the documented behaviour of vfork. 

disabling the #define in lldpd.h that defines fork to be vfork resolves the problem and allows lldpd to work on NetBSD.

**Comment by vincentbernat** [comment]
The `define` is on the other direction:

```c
#if HAVE_WORKING_FORK
# define vfork fork
#endif
```

The `HAVE_WORKING_FORK` comes from `AC_FUNC_WORK`. Could you provide the `config.log` file you get with NetBSD? Look for "working fork". You should get the test program used.

**Comment by mike-pumford** [comment]
[config.log](https://github.com/vincentbernat/lldpd/files/1595129/config.log)
I've attached the full config log but lookng at the relevent bit it has:
configure:22601: checking vfork.h presence
configure:22601: gcc -E  conftest.c
conftest.c:38:19: fatal error: vfork.h: No such file or directory
 #include <vfork.h>
                   ^
compilation terminated.
configure:22601: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "lldpd"
| #define PACKAGE_TARNAME "lldpd"
| #define PACKAGE_VERSION "0.9.9"
| #define PACKAGE_STRING "lldpd 0.9.9"
| #define PACKAGE_BUGREPORT "https://github.com/vincentbernat/lldpd/issues"
| #define PACKAGE_URL "http://vincentbernat.github.io/lldpd/"
| #define PACKAGE "lldpd"
| #define VERSION "0.9.9"
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define HAVE_DLFCN_H 1
| #define LT_OBJDIR ".libs/"
| #define HAVE_TYPEOF 1
| #define HOST_OS_NETBSD 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_NETINET_IN_H 1
| #define HAVE_ARPA_NAMESER_H 1
| #define HAVE_NETDB_H 1
| #define HAVE_RESOLV_H 1
| #define HAVE_U_INT32_T 1
| #define HAVE_UINT32_T 1
| #define HAVE___PROGNAME 1
| #define HAVE_ALIGNOF 1
| #define HAVE_STDLIB_H 1
| #define HAVE_MALLOC 1
| #define HAVE_STDLIB_H 1
| #define HAVE_REALLOC 1
| /* end confdefs.h.  */
| #include <vfork.h>
configure:22601: result: no
configure:22601: checking for vfork.h
configure:22601: result: no
configure:22614: checking for fork
configure:22614: gcc -std=gnu99 -o conftest -g -O2   conftest.c  >&5
conftest.c:61:6: warning: conflicting types for built-in function 'fork' [enable
d by default]
 char fork ();
      ^
configure:22614: $? = 0
configure:22614: result: yes
configure:22614: checking for vfork
configure:22614: gcc -std=gnu99 -o conftest -g -O2   conftest.c  >&5
configure:22614: $? = 0
configure:22614: result: yes
configure:22624: checking for working fork
configure:22646: gcc -std=gnu99 -o conftest -g -O2   conftest.c  >&5
configure:22646: $? = 0
configure:22646: ./conftest
configure:22646: $? = 0
configure:22656: result: yes
configure:22677: checking for working vfork
configure:22787: result: yes

I have run ktrace on the binary and lldpd is using the vfork syscall on NetBSD (not sure how) rather than fork. I confirmed this by using ktrace -i lldpd -d. I wrote a standalone c program to simulate what lldpd does here (but massively simplified and ktraced that and its used fork so it must be something about how that vfork define interacts with the NetBSD system headers.

Mike

**Comment by mike-pumford** [comment]
Including unistd.h in lldpd.h does resolve the issue. It might also be better to only #define vfork to fork if configure hasn't detected a vfork implementation on the system. That would also avoid the issue.

**Comment by vincentbernat** [comment]
I have pushed a commit to fix this problem. The definition is moved in `lldpd.c` after all `#include`s.
