### ISSUE TITLE
aarch64 rpms

### ISSUE THREAD

**Issue by Phhere** [vincentbernat/lldpd#267]
It would be nice if you could provide rpms for aarch64 from suse build service

**Comment by vincentbernat** [comment]
Which distributions would you like?

**Comment by Phhere** [comment]
CentOS would be great

**Comment by vincentbernat** [comment]
Just tried, but I get the cryptic "unresolvable" message: https://build.opensuse.org/package/show/home:vbernat/lldpd. I have no clue why I get that and it's not the first time.

**Comment by Phhere** [comment]
Yes these message looks a bit strange. I was able to build the package from your source-rpm on my server

**Comment by vincentbernat** [comment]
This seems to have been solved in the meantime. Centos 7 and Centos 8 have aarch64 now.
