### ISSUE TITLE
Custom lldpd client - lldpctl keys management

### ISSUE THREAD

**Issue by Kosuu** [vincentbernat/lldpd#269]
Hello, I have a question about using the provided library rather than reporting bug.

I use lldpd to provide support for the lldp protocol for a VoIP phone. Situation forced me to write my own client implementation.  I am able to read the vlan configuration and med policy from the neighbor machines which support lldp-med. The problem is when I want to add or modify some of the information broadcast by my device. 

For example I successful set all keys related to: 
- lldpctl_k_port_med_policies,
- lldpctl_k_port_med_power.

Both are marked as writable(W) however I'm able to set key "lldpctl_k_config_paused" which is marked only as Integer value(I) to control daemon. This prompted me to think that keys marked as "I" are not read-only.

Unfortunately when trying to set values for keys such as:
- lldpctl_k_chassis_cap_available,
- ldpctl_k_chassis_cap_enabled,
- lldpctl_k_chassis_med_cap

I get error "The requested information does not exist". When I try read those values the mentioned error does not occur(i receive values) so I think the reason is that keys are only readable? What is more important is there a way to force daemon to set this keys to requested values(by using lldpctl.h) or set manually in less common way?

Best regards!

**Comment by vincentbernat** [comment]
The missing `W` for `lldpctl_k_config_paused` was an error. I just added it. As for the other properties you need, they are read-only. What would you expect to get when writing to them? Notably, which value would you assign? There may be another way to achieve what you want.

**Comment by Kosuu** [comment]
Thanks for quick reply.

My device, which is phone informs that it supports many capabilities (which are not important to me) but  I cannot force him to inform about what is necessary - that he is a telephone. I would like to be able to set the key values "lldpctl_k_chassis_cap_available" and "ldpctl_k_chassis_cap_enabled" to "LLDP_CAP_TELEPHONE"

What about med - i currently send information only about med policy and power but i also want to send med capabilities and info about med inventory(it would be great if I could set it manually).

**Comment by vincentbernat** [comment]
You can get `LLDP_CAP_TELEPHONE` with `-M 3`. For med inventory, did you notice the `-i` flag for `lldpd`? Or do you want to change that at runtime?

**Comment by Kosuu** [comment]
Thanks! Parameter `-M 3` solve my problems - i don't use `-i`. The most of med inv keys are properly set but some of them are empty (e.g Hardware Revision). It's definitely enough for me but you may consider making it more flexible by setting those keys as writable.

**Comment by vincentbernat** [comment]
Making them writable is not straightforward because some values are derived from them at startup. So, if you don't need it, I won't spend time on it.

**Comment by Kosuu** [comment]
Sure, thank you so much for help.
