### ISSUE TITLE
Update gpg key for apt packages?

### ISSUE THREAD

**Issue by bastelfreak** [vincentbernat/lldpd#279]
Hi,

I've configured your repository on Ubuntu16.04. During an 'apt update' it compains about the SHA1 signature:

```
W: http://download.opensuse.org/repositories/home:/vbernat/xUbuntu_16.04/Release.gpg: Signature by key 8DA446092C6244AFA007765B4B90925372E0A4F6 uses weak digest algorithm (SHA1)
```

On a long point of view they want to drop SHA1 completely. Would it be possible for you to update the key?

**Comment by vincentbernat** [comment]
It seems I have to push a new RSA key. The current one is a 1024-bit DSA key. I have just done that (with `osc signkey --create home:vbernat`) and forced a rebuild. This seems to work. You'll have to import the new key.

**Comment by bastelfreak** [comment]
Thanks, that's working fine now!
