### ISSUE TITLE
compile for android with snmp has error "configure: error: *** incorrect CFLAGS from net-snmp-config"

### ISSUE THREAD

**Issue by aizizai** [vincentbernat/lldpd#293]
# Bug description

when use the latest code(2018-07-13) compile for android with "--with-snmp" has error "configure: error: *** incorrect CFLAGS from net-snmp-config" 

## Steps to reproduce the problem

(android toolchain is ok)

1. git clone https://github.com/vincentbernat/lldpd.git   
2. ./autogen.sh    
3. mkdir build & cd build    
4. ../configure --host=arm-linux-androideabi --with-sysroot=$TOOLCHAIN/sysroot --prefix=/system --sbindir=/system/bin --with-privsep-group=root --with-privsep-user=root --with-snmp  
 
then comes the error:
```
.=== end of configure in libevent (/home/aizizai/data/work/lldp/lldpd/build/libe
vent/libevent)
checking for libcap... no
checking libcap (without pkg-config)... no
checking for a readline compatible library... no
checking for arm-linux-androideabi-net-snmp-config... no
checking for net-snmp-config... /usr/bin/net-snmp-config
checking whether C compiler supports flag "-DNETSNMP_ENABLE_IPV6 -fno-strict-al
iasing -g -O2 -fdebug-prefix-map=/build/net-snmp-UrIPzF/net-snmp-5.7.3+dfsg=. -
fstack-protector-strong -Wformat -Werror=format-security -DNETSNMP_USE_INLINE -
Ulinux -Dlinux=linux -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-al
iasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I
/usr/lib/x86_64-linux-gnu/perl/5.26/CORE -Wdate-time -D_FORTIFY_SOURCE=2 -I/usr
/include -DNETSNMP_NO_INLINE -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -
L/usr/lib/x86_64-linux-gnu -lnetsnmpmibs -lsensors -lpci -ldl -lnetsnmpagent -l
wrap -Wl,-E -lnetsnmp -lcrypto -lm" from Net-SNMP... no
configure: error: *** incorrect CFLAGS from net-snmp-config
aizizai@ubuntu:~/data/work/lldp/lldpd/build$ 
```

I guess I should cross-compile net-snmp either,but I do not know how to use it. please give some advice.thank you !

**Comment by vincentbernat** [comment]
You should get the error returned by the C compiler in `config.log`. If you are cross-compiling, yes, you need to cross-compile libraries too (and ensure `arm-linux-androideabi-net-snmp-config` is installed somewhere in the path). I don't know if it's easy or not as I didn't do it myself.

**Comment by aizizai** [comment]
ok,I will have a try.
