### ISSUE TITLE
Operational MAU Type field mismatch for 100BASE-T4

### ISSUE THREAD

**Issue by tikenh** [vincentbernat/lldpd#297]
This is an example of bug report. Try to adapt it to your case.

# Bug description
It seems that in the file https://github.com/vincentbernat/lldpd/blob/master/src/lldp-const.h,

#define LLDP_DOT3_MAU_10BASET4		14 

I think it should be rather 100BASE instead of 10BASE

#define LLDP_DOT3_MAU_100BASET4		14 

as defined in https://www.iana.org/assignments/ianamau-mib/ianamau-mib
 b100baseT4(14),     -- 100BASE-T4

**Comment by vincentbernat** [comment]
Thanks for noticing! I have pushed a fix.
