### ISSUE TITLE
Issue setting lldpd to receive only on Ubuntu 16.04

### ISSUE THREAD

**Issue by Pubstars** [vincentbernat/lldpd#301]
Hey,

I have lldpd running on an Ubuntu 16.04 system.  I can see neighbor devices fine and the daemon is controlled via systemctl.  However, I cannot seem to get configuration read in after a restart.

## Steps to reproduce the problem
```
systemctl restart lldpd.service
```
I see the following error in the status

```
● lldpd.service - LLDP daemon
   Loaded: loaded (/lib/systemd/system/lldpd.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2018-10-09 17:53:31 EDT; 3s ago
     Docs: man:lldpd(8)
 Main PID: 24655 (lldpd)
   CGroup: /system.slice/lldpd.service
           ├─24655 lldpd: monito
           └─24658 lldpd: no neighbo

Oct 09 17:53:31 root systemd[1]: Starting LLDP daemon...
Oct 09 17:53:31 root systemd[1]: Started LLDP daemon.
Oct 09 17:53:31 root lldpd[24658]: protocol LLDP enabled
Oct 09 17:53:31 root lldpd[24658]: protocol CDPv1 disabled
Oct 09 17:53:31 root lldpd[24658]: protocol CDPv2 disabled
Oct 09 17:53:31 root lldpd[24658]: protocol SONMP disabled
Oct 09 17:53:31 root lldpd[24658]: protocol EDP disabled
Oct 09 17:53:31 root lldpd[24658]: protocol FDP disabled
Oct 09 17:53:31 root lldpd[24658]: libevent 2.0.21-stable initialized with epoll method
Oct 09 17:53:31 root lldpcli[24657]: unknown command from argument 1: `DAEMON_ARGS=-r`
```
I have added the arg to /etc/lldpd.d/README.conf (as this is only for testing)
```
DAEMON_ARGS="-r"
```

Essentially all I am trying to do is create a config file that puts lldpd in receive mode only on start up.

I have spent the last 2 hours going over the docs and issues and tried some of the config file commands others have used and nothing seems to work.  

Can you provide guidance or a place I can refer to for this please?

# Additional information

 - Output of `lldpd -vv`:
 
```
root@root:~# lldpd -vv
0.7.19

**Comment by vincentbernat** [comment]
`/etc/lldpd.d` should only contain commands for `lldpcli`. For the `-r` flag, you need to modify `/etc/default/lldpd`.

**Comment by Pubstars** [comment]
Thank you that fixed that issue.  Also we found that lldpd is sending BPDU packets which causes our switches to disable the interfaces to the station.  Is there a way to disable these packets?

**Comment by vincentbernat** [comment]
It doesn't send any BPDU. You can use tcpdump to check that.

**Comment by vincentbernat** [comment]
Not much to do here, closing.
