### ISSUE TITLE
CDP not working

### ISSUE THREAD

**Issue by p3rtinax** [vincentbernat/lldpd#302]
Dear Vincent,
First of all, thank you for this great daemon,

Here is my configuration on Ubuntu 16.04,
Build from source ( 1 hour ago )

root@ubuntu:~# lldpd -v
1.0.1-29-ge86777a

lldpd not running by default on boot, so I've added this line to /etc/rc.local:
lldpd -c -O /etc/lldpd.d/lldp.conf 

lldpd runs after reboot and read my custom config ( overriding platform and desc. )
When on another side I captured packets with Wireshark, LLDP packets are received and all configuration inside packets are correct, but filtering by "cdp" there is no packets at all!

I've tested lldp from apt-get, there is no difference, -c for Cisco CDP is not sending packets out of ports,
( tested both from daemon args or -c command line )

Could you please guide me to solve this problem?

There are 2 other things I have to ask,
when Installing from apt-get ( v0.7.9 ), lldpcli working fine and tab is showing me helps,
but when building from source lldpcli working, but when pressing tab just courser jump ( like text editor ) there is no showing help, or command completion feature, no clearing ( backspacing ) commands and everything must be the exact command I'd remember from installation from apt-get,

The other thing is, is it possible to enable or disable Capabilities? for instance, I'd like to have just router capability on and turn off other capabilities, is it possible?

**Comment by vincentbernat** [comment]
Use `-cc` to force sending CDP packets even when no peer is present.

You need to compile with libreadline or libedit if you want to get completion.

Currently, capabilities are not configurable. You get the router capability when routing is enabled.

**Comment by vincentbernat** [comment]
Did it work?

**Comment by xyzzy42** [comment]
Had a similar problem with a Cisco small business switch.  This switch sends both CDP and LLDP packets.  If lldpd gets the LLDP first, it goes into LLDP mode and doesn't send CDP.  But if it gets the CDP first, then it will send CDP.   I used "-H 10" to stop lldpd from doing this, combined with -ccccc to force sending CDPv2.

While the switch supports both protocols, PoE power negotiation only works via CDP (0x001a).  Using 802.3at power over MDI (00:12:0f 0x02) is never responded to by the switch.

**Comment by vincentbernat** [comment]
No answer from initial reporter. Closing.
