### ISSUE TITLE
lldpd.servce Loaded  Failed  

### ISSUE THREAD

**Issue by HelloLady** [vincentbernat/lldpd#308]
Hi,vincent:
I was installing lldpd form source on **Ubuntu 16.04 LTS** and referencing "http://vincentbernat.github.io/lldpd/installation.html" .I met the issue was that **lldpd.service loaded failed**
 
**Execute "ps aux|grep lldpd",ouput likes below**:
`# ps aux|grep lldpd`
`root      3208  0.0  0.0  15984   936 pts/11   S+   10:32   0:00 grep --color=auto lldpd`   
    
**Execute "lldpd start  && ps aux|grep lldpd",output likes below**:
`# lldpd start`
`# ps aux|grep lldpd`
`root      3287  0.0  0.0  13072  1924 ?        Ss   10:42   0:00 lldpd start`
`  _lldpd    3289  0.0  0.0  13072   148 ?        S    10:42   0:00 lldpd start`
`root      3291  0.0  0.0  15984  1088 pts/11   S+   10:42   0:00 grep --color=auto lldpd`
 
**Execute "lldpcli show neighbors",ouput likes  below**:
`# lldpcli show neighbors`
`-------------------------------------------------------------------------------`
`LLDP neighbors:`
`-------------------------------------------------------------------------------`

**Eexecute "lldpcli show stat",output likes below**:
`# lldpcli show stat`
`-------------------------------------------------------------------------------`
`LLDP statistics:`
`-------------------------------------------------------------------------------`
`Interface:    enp0s3`
`Transmitted:  50`
`Received:     0`
` Discarded:    0`
`Unrecognized: 0`
` Ageout:       0`
` Inserted:     0`
`Deleted:      0`
`-------------------------------------------------------------------------------`

**Execute "systemctl",output likes below**:
`# systemctl`
`.......`
`lightdm.service                         loaded active       running               Light Display Manager `
`● lldpd.service                          loaded failed        failed                  LLDP daemon`
`ModemManager.service          loaded active       running               Modem Manager`
`......`

How can I modify to let lldpd works? And if you need more detail information or anything else ,please let me know.Hope to get your reply.Thanks!

**Comment by vincentbernat** [comment]
What do you get if you do:

```
pkill lldpd
systemctl start lldpd
systemctl status lldpd
journalctl -u lldpd
```

**Comment by HelloLady** [comment]
Hi ,vincent:
First at all ,thanks you reply!!!
I tried to execute  the instructions you mentioned and get the ouput showing below:

`# pkill lldpd`

`# systemctl start lldpd`
`Job for lldpd.service failed because the control process exited with error code. See "systemctl status lldpd.service" and "journalctl -xe" for details.`

`# systemctl status lldpd`
`● lldpd.service - LLDP daemon
   Loaded: loaded (/lib/systemd/system/lldpd.service; enabled; vendor preset: enabled)
   Active: failed (Result: start-limit-hit) since 五 2018-11-30 14:58:32 CST; 10s ago
     Docs: man:lldpd(8)
  Process: 3712 ExecStart=/usr/local/sbin/lldpd $DAEMON_ARGS $LLDPD_OPTIONS (code=exited, status=1/FAILURE)
  Process: 3709 ExecStartPre=/bin/mkdir -p /usr/local/var/run/lldpd (code=exited, status=0/SUCCESS)
 Main PID: 3712 (code=exited, status=1/FAILURE)`
`11月 30 14:58:32 cqli-VirtualBox systemd[1]: lldpd.service: Service hold-off time over, scheduling restart.
11月 30 14:58:32 cqli-VirtualBox systemd[1]: Stopped LLDP daemon.
11月 30 14:58:32 cqli-VirtualBox systemd[1]: lldpd.service: Start request repeated too quickly.
11月 30 14:58:32 cqli-VirtualBox systemd[1]: Failed to start LLDP daemon.
11月 30 14:58:32 cqli-VirtualBox systemd[1]: lldpd.service: Unit entered failed state.
11月 30 14:58:32 cqli-VirtualBox systemd[1]: lldpd.service: Failed with result 'start-limit-hit'. `

`# journalctl -u lldpd`
`-- Logs begin at 五 2018-11-30 14:14:55 CST, end at 五 2018-11-30 14:58:32 CST. --
11月 30 14:15:05 cqli-VirtualBox systemd[1]: Starting LLDP daemon...
11月 30 14:15:05 cqli-VirtualBox systemd[1]: lldpd.service: Main process exited, code=exited, status=1/FAILURE
11月 30 14:15:05 cqli-VirtualBox systemd[1]: Failed to start LLDP daemon.
11月 30 14:15:05 cqli-VirtualBox systemd[1]: lldpd.service: Unit entered failed state.
11月 30 14:15:05 cqli-VirtualBox systemd[1]: lldpd.service: Failed with result 'exit-code'.
11月 30 14:15:05 cqli-VirtualBox systemd[1]: lldpd.service: Service hold-off time over, scheduling restart.`
`.......`

**Comment by HelloLady** [comment]
Thank for your reminding.
Yes, ` /usr/local/sbin/lldpd` exists.
```
# /usr/local/sbin/lldpd -ddd
2018-11-30T15:25:15 [INFO/main] protocol LLDP enabled
2018-11-30T15:25:15 [INFO/main] protocol CDPv1 disabled
2018-11-30T15:25:15 [INFO/main] protocol CDPv2 disabled
2018-11-30T15:25:15 [INFO/main] protocol SONMP disabled
2018-11-30T15:25:15 [INFO/main] protocol EDP disabled
2018-11-30T15:25:15 [INFO/main] protocol FDP disabled
2018-11-30T15:25:15 [INFO/event] libevent 2.0.22-stable initialized with epoll method
2018-11-30T15:25:15 [INFO/lldpctl] lldpd should resume operations
````

**Comment by vincentbernat** [comment]
What's the output of `systemctl cat lldpd` and the content of `/etc/default/lldpd` if any?

**Comment by vincentbernat** [comment]
In `/lib/systemd/system/lldpd.services`, could you delete all the `Protect` directives? Then, use `systemctl daemon-reload` and check if `systemctl start lldpd` works.

**Comment by HelloLady** [comment]
I din't find /lib/systemd/system/lldpd.services
````
# ls /lib/systemd/system/lldpd.services
ls: can not access '/lib/systemd/system/lldpd.services': no such file or directory
````

**Comment by vincentbernat** [comment]
Sorry, `/lib/systemd/system/lldpd.service`.

**Comment by HelloLady** [comment]
After  delete all the `Protect` directives,and then
````
root@cqli-VirtualBox:~# systemctl daemon-reload
root@cqli-VirtualBox:~# systemctl start lldpd
Job for lldpd.service failed because the control process exited with error code. See "systemctl status lldpd.service" and "journalctl -xe" for details.
root@cqli-VirtualBox:~# systemctl status lldpd.service
● lldpd.service - LLDP daemon
   Loaded: loaded (/lib/systemd/system/lldpd.service; enabled; vendor preset: enabled)
   Active: failed (Result: start-limit-hit) since 五 2018-11-30 18:24:30 CST; 21s ago
     Docs: man:lldpd(8)
  Process: 5107 ExecStart=/usr/local/sbin/lldpd $DAEMON_ARGS $LLDPD_OPTIONS (code=exited, status=1/FAILURE)
  Process: 5103 ExecStartPre=/bin/mkdir -p /usr/local/var/run/lldpd (code=exited, status=0/SUCCESS)
 Main PID: 5107 (code=exited, status=1/FAILURE)

11月 30 18:24:30 cqli-VirtualBox systemd[1]: Failed to start LLDP daemon.
11月 30 18:24:30 cqli-VirtualBox systemd[1]: lldpd.service: Unit entered failed state.
11月 30 18:24:30 cqli-VirtualBox systemd[1]: lldpd.service: Failed with result 'exit-code'.
11月 30 18:24:30 cqli-VirtualBox systemd[1]: lldpd.service: Service hold-off time over, scheduling restart.
11月 30 18:24:30 cqli-VirtualBox systemd[1]: Stopped LLDP daemon.
11月 30 18:24:30 cqli-VirtualBox systemd[1]: lldpd.service: Start request repeated too quickly.
11月 30 18:24:30 cqli-VirtualBox systemd[1]: Failed to start LLDP daemon.
11月 30 18:24:30 cqli-VirtualBox systemd[1]: lldpd.service: Unit entered failed state.
11月 30 18:24:30 cqli-VirtualBox systemd[1]: lldpd.service: Failed with result 'start-limit-hit'.
````
It still doesn't work.

**Comment by vincentbernat** [comment]
Could you create `/etc/default/lldpd` and put:

```
DAEMON_ARGS="-ddd"
```

Then, `systemctl start lldpd` and `journalctl -u lldpd`. It should give some hint on why this happens.

**Comment by HelloLady** [comment]
I  rebooted  my computer,and did follower operations,it seems work by  deleting all the `Protect` directives. Thank you very much!!!
But it still showed nothing about neighbors details by executing `lldpcli show neighbors`
````
# systemctl start lldpd
root@cqli-VirtualBox:/home/cqli# journalctl -u lldpd
-- Logs begin at 五 2018-11-30 18:56:51 CST, end at 五 2018-11-30 19:01:05 CST. --
11月 30 18:57:01 cqli-VirtualBox systemd[1]: Starting LLDP daemon...
11月 30 18:57:01 cqli-VirtualBox systemd[1]: Started LLDP daemon.
11月 30 18:57:01 cqli-VirtualBox lldpd[951]: protocol LLDP enabled
11月 30 18:57:01 cqli-VirtualBox lldpd[951]: protocol CDPv1 disabled
11月 30 18:57:01 cqli-VirtualBox lldpd[951]: protocol CDPv2 disabled
11月 30 18:57:01 cqli-VirtualBox lldpd[951]: protocol SONMP disabled
11月 30 18:57:01 cqli-VirtualBox lldpd[951]: protocol EDP disabled
11月 30 18:57:01 cqli-VirtualBox lldpd[951]: protocol FDP disabled
11月 30 18:57:01 cqli-VirtualBox lldpd[951]: libevent 2.0.22-stable initialized with epoll method
11月 30 18:57:01 cqli-VirtualBox lldpcli[950]: lldpd should resume operations
11月 30 19:01:05 cqli-VirtualBox systemd[1]: Started LLDP daemon.
root@cqli-VirtualBox:/home/cqli# ps aux|grep lldpd
root       947  0.0  0.0  13072  1952 ?        Ss   18:57   0:00 /usr/local/sbin/lldpd
_lldpd     951  0.0  0.0  13072   136 ?        S    18:57   0:00 /usr/local/sbin/lldpd
root      3418  0.0  0.0  15984   936 pts/8    S+   19:01   0:00 grep --color=auto lldpd
````
````
# systemctl status lldpd.service
● lldpd.service - LLDP daemon
   Loaded: loaded (/lib/systemd/system/lldpd.service; enabled; vendor preset: enabled)
   Active: active (running) since 五 2018-11-30 18:57:01 CST; 9min ago
     Docs: man:lldpd(8)
  Process: 942 ExecStartPre=/bin/mkdir -p /usr/local/var/run/lldpd (code=exited, status=0/SUCCESS)
 Main PID: 947 (lldpd)
   CGroup: /system.slice/lldpd.service
           ├─947 /usr/local/sbin/lldpd
           └─951 /usr/local/sbin/lldpd

11月 30 18:57:01 cqli-VirtualBox lldpd[951]: protocol LLDP enabled
11月 30 18:57:01 cqli-VirtualBox lldpd[951]: protocol CDPv1 disabled
11月 30 18:57:01 cqli-VirtualBox lldpd[951]: protocol CDPv2 disabled
11月 30 18:57:01 cqli-VirtualBox lldpd[951]: protocol SONMP disabled
11月 30 18:57:01 cqli-VirtualBox lldpd[951]: protocol EDP disabled
11月 30 18:57:01 cqli-VirtualBox lldpd[951]: protocol FDP disabled
11月 30 18:57:01 cqli-VirtualBox lldpd[951]: libevent 2.0.22-stable initialized with epoll method
11月 30 18:57:01 cqli-VirtualBox lldpcli[950]: lldpd should resume operations
11月 30 19:01:05 cqli-VirtualBox systemd[1]: Started LLDP daemon.
11月 30 19:06:25 cqli-VirtualBox systemd[1]: Started LLDP daemon.
````

````
# lldpcli show neighbors 
-------------------------------------------------------------------------------
LLDP neighbors:
-------------------------------------------------------------------------------
````

**Comment by vincentbernat** [comment]
It seems you are running inside Virtualbox. Usually, LLDP packets do not traverse bridges and therefore do not reach the virtual machine.

**Comment by HelloLady** [comment]
Hi,vincent:
Thanks for your patience to help me solving issue.And I meet a new issue **Failed to start LLDP daemon**, I change nothing compare with last week.

````
# service lldpd status
● lldpd.service - LLDP daemon
   Loaded: loaded (/lib/systemd/system/lldpd.service; enabled; vendor preset: enabled)
   Active: activating (start) since 一 2018-12-03 10:31:23 CST; 1min 7s ago
     Docs: man:lldpd(8)
  Process: 4157 ExecStartPre=/bin/mkdir -p /usr/local/var/run/lldpd (code=exited, status=0/SUCCESS)
 Main PID: 4159 (lldpd)
   CGroup: /system.slice/lldpd.service
           ├─4159 /usr/local/sbin/lldpd -ddd
           └─4162 /usr/local/sbin/lldpd -ddd

12月 03 10:31:23 cqli-VirtualBox systemd[1]: Starting LLDP daemon...
12月 03 10:31:23 cqli-VirtualBox lldpd[4159]: 2018-12-03T10:31:23 [INFO/main] protocol LLDP enabled
12月 03 10:31:23 cqli-VirtualBox lldpd[4159]: 2018-12-03T10:31:23 [INFO/main] protocol CDPv1 disabled
12月 03 10:31:23 cqli-VirtualBox lldpd[4159]: 2018-12-03T10:31:23 [INFO/main] protocol CDPv2 disabled
12月 03 10:31:23 cqli-VirtualBox lldpd[4159]: 2018-12-03T10:31:23 [INFO/main] protocol SONMP disabled
12月 03 10:31:23 cqli-VirtualBox lldpd[4159]: 2018-12-03T10:31:23 [INFO/main] protocol EDP disabled
12月 03 10:31:23 cqli-VirtualBox lldpd[4159]: 2018-12-03T10:31:23 [INFO/main] protocol FDP disabled
12月 03 10:31:23 cqli-VirtualBox lldpd[4159]: 2018-12-03T10:31:23 [INFO/event] libevent 2.0.22-stable initialized with epoll method
12月 03 10:31:23 cqli-VirtualBox lldpd[4159]: 2018-12-03T10:31:23 [INFO/lldpctl] lldpd should resume operations
````
````
# /usr/local/sbin/lldpd -ddd
2018-12-03T10:43:34 [INFO/main] unable to create control socket because it already exists
2018-12-03T10:43:34 [INFO/main] check if another instance is running
2018-12-03T10:43:34 [WARN/main] another instance is running, please stop it
2018-12-03T10:43:34 [CRIT/main] giving up

````
````
# service lldpd start
Job for lldpd.service failed because a timeout was exceeded. See "systemctl status lldpd.service" and "journalctl -xe" for details.

````
````
# journalctl -u lldpd
-- Logs begin at 一 2018-12-03 10:10:08 CST, end at 一 2018-12-03 10:23:51 CST. --
12月 03 10:10:16 cqli-VirtualBox systemd[1]: Starting LLDP daemon...
12月 03 10:10:16 cqli-VirtualBox lldpd[930]: 2018-12-03T10:10:16 [INFO/main] protocol LLDP enabled
12月 03 10:10:16 cqli-VirtualBox lldpd[930]: 2018-12-03T10:10:16 [INFO/main] protocol CDPv1 disabled
12月 03 10:10:16 cqli-VirtualBox lldpd[930]: 2018-12-03T10:10:16 [INFO/main] protocol CDPv2 disabled
12月 03 10:10:16 cqli-VirtualBox lldpd[930]: 2018-12-03T10:10:16 [INFO/main] protocol SONMP disabled
12月 03 10:10:16 cqli-VirtualBox lldpd[930]: 2018-12-03T10:10:16 [INFO/main] protocol EDP disabled
12月 03 10:10:16 cqli-VirtualBox lldpd[930]: 2018-12-03T10:10:16 [INFO/main] protocol FDP disabled
12月 03 10:10:16 cqli-VirtualBox lldpd[930]: 2018-12-03T10:10:16 [INFO/event] libevent 2.0.22-stable initialized with epoll method
12月 03 10:10:16 cqli-VirtualBox lldpd[930]: 2018-12-03T10:10:16 [INFO/lldpctl] lldpd should resume operations
12月 03 10:11:46 cqli-VirtualBox systemd[1]: lldpd.service: Start operation timed out. Terminating.
12月 03 10:11:46 cqli-VirtualBox systemd[1]: Failed to start LLDP daemon.
12月 03 10:11:46 cqli-VirtualBox systemd[1]: lldpd.service: Unit entered failed state.
12月 03 10:11:46 cqli-VirtualBox systemd[1]: lldpd.service: Failed with result 'timeout'.
12月 03 10:11:47 cqli-VirtualBox systemd[1]: lldpd.service: Service hold-off time over, scheduling restart.
12月 03 10:11:47 cqli-VirtualBox systemd[1]: Stopped LLDP daemon.
... ...
````
After install lldpd,is the  device starting to run lldpd.servic once power on automaticlly or  need to execute `service lldpd start`.And how to uninstall lldpd.servie?
