### ISSUE TITLE
lldpd Failed to run successfully on Linux?

### ISSUE THREAD

**Issue by goutaiping** [vincentbernat/lldpd#313]
Hi Vincent:
     I have been using your lldpd recently on Linux, it's greate on Unbuntu, but when I cross-compile and have encountered some problems:
     1、I successfully cross-compile lldpd-1.0.3:
        ../configure \
        --host=arm-openwrt-linux-gnueabi \
        --sysconfdir=/etc \
        --localstatedir=/var \
     2、I created user __ldpd, 
     3、but when I "lldpd -i eth0" and "lldpdcli show neighbors", It always Fail,
           -------------------------------------------------------------------------------
           LLDP neighbors:
          -------------------------------------------------------------------------------
         when I "lldpd -ddd"
2000-04-18T06:17:08 [INFO/privsep] no libcap support, running monitor as root
2000-04-18T06:17:08 [INFO/main] protocol LLDP enabled
2000-04-18T06:17:08 [INFO/main] protocol CDPv1 disabled
2000-04-18T06:17:08 [INFO/main] protocol CDPv2 disabled
2000-04-18T06:17:08 [INFO/main] protocol SONMP disabled
2000-04-18T06:17:08 [INFO/main] protocol EDP disabled
2000-04-18T06:17:08 [INFO/main] protocol FDP disabled
2000-04-18T06:17:08 [INFO/event] libevent 2.0.22-stable initialized with epoll method
2000-04-18T06:17:08 [WARN/interfaces] cannot get ethtool link information with GLINKSETTINGS (requires 4.9+). 25G+ speeds may be missing in MAC/PHY TLVs
2000-04-18T06:17:08 [INFO/privsep] unable to get system name
2000-04-18T06:17:08 [INFO/privsep] unable to get system name
2000-04-18T06:17:08 [INFO/lldpctl] lldpd should resume operations

Do you know why? Looking forward to your reply, Thank you

**Comment by vincentbernat** [comment]
Does `tcpdump -eni eth0  ether host 01:80:c2:00:00:0e` (wait at least 30 seconds) give you any output?

**Comment by vincentbernat** [comment]
As you can see, you only see the packets emitted by lldpd. You do not receive LLDP packets. These packets may have been filtered by the internal switch of your router. Maybe there is a way to avoid that.

**Comment by goutaiping** [comment]
But I connected the device directly to the computer, and there was no other device in between

**Comment by goutaiping** [comment]
Do I need to configure any files?Such as lldpd. conf, and so on

**Comment by vincentbernat** [comment]
Linux does not receive the LLDP packets, there is not much `lldpd` can do here. Which device is it?

**Comment by goutaiping** [comment]
A linux-based bridge device is being developed

**Comment by vincentbernat** [comment]
Check with the team managing the switch chipset. There should be a register available to correctly pass LLDP frames to the CPU port.

**Comment by goutaiping** [comment]
Is there a reason why the LLDP protocol does not support bridge devices?

**Comment by alfredomantilla** [comment]
Hi, could be your linux version? Do you have this patch included? https://lore.kernel.org/patchwork/patch/707428/

**Comment by vincentbernat** [comment]
It uses a link-local MAC address. Bridges are not supposed to forward them.

**Comment by goutaiping** [comment]
> Hi, could be your linux version? Do you have this patch included? https://lore.kernel.org/patchwork/patch/707428/

Thank you for your reply. I don't know whether the system of the device contains this patch. I will suggest to the system engineer to add this patch

**Comment by goutaiping** [comment]
Hi Vincent:
    Thank you for your reply. It is true that LLDP does not support bridge equipment. Could you give me some Suggestions?Two bridge devices are connected. How do I get information about the other device?

**Comment by vincentbernat** [comment]
Switch chipsets can usually be configured to pass LLDP packets to the CPU port. Check the documentation.

**Comment by goutaiping** [comment]
Thank you very much
