### ISSUE TITLE
Question: 802.1AB version

### ISSUE THREAD

**Issue by chiekaze** [vincentbernat/lldpd#316]
Hi, 
standard 802.1AB has multiple (older) versions:

- 802.1AB-2005
- 802.1AB-2009
- 802.1AB-2009/Cor 1-2013
- 802.1AB-2009/Cor 2-2015
- 802.1AB-2016

According to Github lldpd version 0.9.6 is released on Jan 21, 2017. Is version 0.9.6 compatible with the newest standard version (802.1AB-2016)? If not, what is the right standard version for this lldpd version?

What about lldpd version 0.7.17, it is released on Sep 9, 2015, so is lldpd version 0.7.17 compatible with the standard version 802.1AB-2009/Cor 2-2015? If not, what is the right standard version for this lldpd version?

Thanks.

**Comment by vincentbernat** [comment]
Only 802.1AB-2005 is implemented.

**Comment by chiekaze** [comment]
Hi, thanks for the quick response.
