### ISSUE TITLE
Question: Code Doubt!

### ISSUE THREAD

**Issue by welltoon** [vincentbernat/lldpd#317]
Hi Vincent:
     I want to clean LLDP statistics. What shall I do?
Now I make "hardware->h_tx_cnt" to be 0, But it doesn't work.
I print the value of "hardware->h_tx_cnt", it always is 4000.

Thank you !

**Comment by vincentbernat** [comment]
I don't see how the value could stay the same after you assigned 0 to it. How do you set it to 0?

**Comment by welltoon** [comment]
I run LLDP on  Qualcomm IPQ4019.

static long int
_lldpctl_atom_get_int_port(lldpctl_atom_t *atom, lldpctl_key_t key)
{
	struct _lldpctl_atom_port_t *p =
	    (struct _lldpctl_atom_port_t *)atom;
	struct lldpd_port     *port     = p->port;
	struct lldpd_hardware *hardware = p->hardware;

	/* Local port only */
	if (hardware != NULL) {
		switch (key) {
		case lldpctl_k_port_index:
			return hardware->h_ifindex;
		case lldpctl_k_tx_cnt:
			printf("h_tx_cnt %d\n", hardware->h_tx_cnt);  ### //I print the value here, the values is always 0, but run "lldpcli show st"  get right value. 
			return hardware->h_tx_cnt;
		case lldpctl_k_rx_cnt:
			return hardware->h_rx_cnt;
		case lldpctl_k_rx_discarded_cnt:

**Comment by welltoon** [comment]
Hi Vincent:
     
void 
display_interfaces_stats(lldpctl_conn_t *conn, struct writer *w,
    struct cmd_env *env)
{
	lldpctl_atom_t *iface;
	int summary = 0;
	u_int64_t h_tx_cnt = 0;
	u_int64_t h_rx_cnt = 0;
	u_int64_t h_rx_discarded_cnt = 0;
	u_int64_t h_rx_unrecognized_cnt = 0;
	u_int64_t h_ageout_cnt = 0;
	u_int64_t h_insert_cnt = 0;
	u_int64_t h_delete_cnt = 0;

	if (cmdenv_get(env, "summary"))
		summary = 1;

	tag_start(w, "lldp", (summary ? "LLDP Global statistics" :
		"LLDP statistics"));
	while ((iface = cmd_iterate_on_interfaces(conn, env))) {
		lldpctl_atom_t *port;
		port      = lldpctl_get_port(iface);
		if (!summary)
			display_interface_stats(conn, w, port);
		else {
             printf("*** %d ****\n", lldpctl_atom_get_int(port,lldpctl_k_tx_cnt));  //Print here, the value is always 0.  
			h_tx_cnt += lldpctl_atom_get_int(port,
					lldpctl_k_tx_cnt);
			h_rx_cnt += lldpctl_atom_get_int(port,
					lldpctl_k_rx_cnt);
			h_rx_discarded_cnt += lldpctl_atom_get_int(port,
					lldpctl_k_rx_discarded_cnt);
			h_rx_unrecognized_cnt += lldpctl_atom_get_int(port,
					lldpctl_k_rx_unrecognized_cnt);
			h_ageout_cnt += lldpctl_atom_get_int(port,
						lldpctl_k_ageout_cnt);
			h_insert_cnt += lldpctl_atom_get_int(port,
						lldpctl_k_insert_cnt);
			h_delete_cnt += lldpctl_atom_get_int(port,
						lldpctl_k_delete_cnt);
		}
		lldpctl_atom_dec_ref(port);
	}

**Comment by welltoon** [comment]
I add a function in src/lib/atoms/port.c , to set "h_tx_cnt" to be 0, but can't change it.


static int
_lldpctl_atom_clean_port_stat(lldpctl_atom_t *atom, lldpctl_key_t key)
{
    struct _lldpctl_atom_port_t *p =
        (struct _lldpctl_atom_port_t *)atom;
    //struct lldpd_port     *port     = p->port;
    struct lldpd_hardware *hardware = p->hardware;
    //struct lldpd_chassis  *chassis  = port->p_chassis;

    printf("%s %d %d\n", __FUNCTION__, __LINE__,  hardware->h_tx_cnt);
    hardware->h_rx_cnt=0;
    hardware->h_tx_cnt=0;
    hardware->h_rx_discarded_cnt=0;
    hardware->h_rx_unrecognized_cnt=0;
    hardware->h_ageout_cnt=0;
    hardware->h_insert_cnt=0;
    hardware->h_delete_cnt=0;
    printf("%s %d %d\n", __FUNCTION__, __LINE__,  hardware->h_tx_cnt);
    return 0;
}

**Comment by vincentbernat** [comment]
The `hardware` structure in the client is just a copy of the real structure. You cannot just modify it. You should reset stats in the daemon. Look in `client.c`, in `_client_handle_set_port`. You could add a `reset_stats` field to the `struct lldpd_port_set` structure.

**Comment by welltoon** [comment]
Follow your advice，I reset statistical data success.
Thanks for your help！ I will try to add command line. ^_^

**Comment by vincentbernat** [comment]
Not really an issue. I am closing this. Feel free to continue to comment here if needed.
