### ISSUE TITLE
cross-compiled the lldpd-1.0.3. #make error

### ISSUE THREAD

**Issue by luciazi** [vincentbernat/lldpd#318]
Hi vincent,
when I cross-compiled the lldpd-1.0.3, with ./configure --host=arm-linux CC=/opt/broadcom/iproc/usr/bin/arm-linux-gcc  --prefix=/home/testProject/apps/lldpd-1.0.3 ; then make, error happed. 

Here is the output info:

```
------------------ Summary ------------------
 lldpd version 1.0.3
  OS.............: Linux
  Prefix.........: /home/testProject/apps/lldpd-1.0.3
  C Compiler.....: /opt/broadcom/iproc/usr/bin/arm-linux-gcc -std=gnu99  -fdiagnostics-show-option -fdiagnostics-color=auto -pipe -Wall -W -Wextra -Wformat -Wformat-security -Wfatal-errors -Wcast-align -Winline -Wpointer-arith -fno-omit-frame-pointer -Wno-unused-parameter -Wno-missing-field-initializers -Wno-sign-compare -fstack-protector -fstack-protector-all -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -g -O2 
  Linker.........: /opt/broadcom/iproc/usr/arm-broadcom-linux-uclibcgnueabi/bin/ld  -Wl,-z,relro -Wl,-z,now   
  Libevent.......: embedded
  Readline.......: -lreadline -lncurses

 Optional features:
  SNMP support...: no
  CDP............: yes
  FDP............: yes
  EDP............: yes
  SONMP..........: yes
  LLDPMED........: yes
  DOT1...........: yes
  DOT3...........: yes
  CUSTOM.........: yes
  XML output.....: no
  Oldies support.: no
  seccomp........: no
  libbsd.........: no

 Privilege separation:
  Enabled........: yes
  User/group.....: _lldpd/_lldpd
  Chroot.........: /home/testProject/apps/lldpd-1.0.3/var/run/lldpd

 Instrumentation (for devs only):
  Sanitizers.....: none
  Coverage.......: no
------------- Compiler version --------------
arm-linux-gcc.br_real (Buildroot 2015.11.1) 4.9.3
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
-------------- Linker version ---------------
GNU ld (GNU Binutils) 2.24
Copyright 2013 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
---------------------------------------------

Check the above options and compile with:
 make

-bash-4.2$ make

when entering directory src/daemon, 

make[3]: Entering directory `/home/testProject/apps/lldpd-1.0.3/src/daemon'
  CC       main.o
  CC       liblldpd_la-frame.lo
  CC       liblldpd_la-client.lo
  CC       liblldpd_la-priv.lo
  CC       liblldpd_la-privsep.lo
  CC       liblldpd_la-privsep_io.lo
  CC       liblldpd_la-privsep_fd.lo
  CC       liblldpd_la-interfaces.lo
(cd ../../libevent && make)
make[4]: Entering directory `/home/testProject/apps/lldpd-1.0.3/libevent'
test -d include/event2 || /usr/bin/mkdir -p include/event2
/usr/bin/sed -f ./make-event-config.sed < config.h > include/event2/event-config.hT
mv -f include/event2/event-config.hT include/event2/event-config.h
make  all-recursive
make[5]: Entering directory `/home/testProject/apps/lldpd-1.0.3/libevent'
Making all in .
make[6]: Entering directory `/home/testProject/apps/lldpd-1.0.3/libevent'
  CC       event.lo
  CC       evthread.lo
  CC       buffer.lo
  CC       bufferevent.lo
  CC       bufferevent_sock.lo
  CC       bufferevent_filter.lo
  CC       bufferevent_pair.lo
  CC       listener.lo
  CC       bufferevent_ratelim.lo
  CC       evmap.lo
  CC       log.lo
  CC       evutil.lo
  CC       evutil_rand.lo
  CC       strlcpy.lo
  CC       select.lo
  CC       poll.lo
  CC       epoll.lo
  CC       signal.lo
  CC       event_tagging.lo
  CC       http.lo
  CC       evdns.lo
  CC       evrpc.lo
  CCLD     libevent.la
  CCLD     libevent_core.la
  CCLD     libevent_extra.la
make[6]: Leaving directory `/home/testProject/apps/lldpd-1.0.3/libevent'
Making all in include
make[6]: Entering directory `/home/testProject/apps/lldpd-1.0.3/libevent/include'
make[6]: Nothing to be done for `all'.
make[6]: Leaving directory `/home/testProject/apps/lldpd-1.0.3/libevent/include'
Making all in sample
make[6]: Entering directory `/home/testProject/apps/lldpd-1.0.3/libevent/sample'
  CC       event-test.o
  CCLD     event-test
  CC       time-test.o
  CCLD     time-test
  CC       signal-test.o
  CCLD     signal-test
  CC       dns-example.o
  CCLD     dns-example
  CC       hello-world.o
  CCLD     hello-world
  CC       http-server.o
  CCLD     http-server
make[6]: Leaving directory `/home/testProject/apps/lldpd-1.0.3/libevent/sample'
Making all in test
make[6]: Entering directory `/home/testProject/apps/lldpd-1.0.3/libevent/test'
make  all-am
make[7]: Entering directory `/home/testProject/apps/lldpd-1.0.3/libevent/test'
  CC       test-init.o
  CCLD     test-init
  CC       test-eof.o
  CCLD     test-eof
  CC       test-weof.o
  CCLD     test-weof
  CC       test-time.o
  CCLD     test-time
  CC       bench.o
  CCLD     bench
  CC       bench_cascade.o
  CCLD     bench_cascade
  CC       bench_http.o
  CCLD     bench_http
  CC       bench_httpclient.o
  CCLD     bench_httpclient
  CC       test-ratelim.o
  CCLD     test-ratelim
  CC       test-changelist.o
  CCLD     test-changelist
make[7]: Leaving directory `/home/testProject/apps/lldpd-1.0.3/libevent/test'
make[6]: Leaving directory `/home/testProject/apps/lldpd-1.0.3/libevent/test'
make[5]: Leaving directory `/home/testProject/apps/lldpd-1.0.3/libevent'
make[4]: Leaving directory `/home/testProject/apps/lldpd-1.0.3/libevent'
  CC       liblldpd_la-event.lo
  CC       liblldpd_la-lldpd.lo
  CC       liblldpd_la-pattern.lo
  CC       protocols/liblldpd_la-lldp.lo
  CC       protocols/liblldpd_la-cdp.lo
  CC       protocols/liblldpd_la-sonmp.lo
  CC       protocols/liblldpd_la-edp.lo
  CC       liblldpd_la-forward-linux.lo
  CC       liblldpd_la-interfaces-linux.lo
  CC       liblldpd_la-netlink.lo
  CC       liblldpd_la-dmi-linux.lo
  CC       liblldpd_la-priv-linux.lo
  CCLD     liblldpd.la
copying selected object files to avoid basename conflicts...
  CCLD     lldpd
/opt/broadcom/iproc/usr/lib/gcc/arm-broadcom-linux-uclibcgnueabi/4.9.3/../../../../arm-broadcom-linux-uclibcgnueabi/bin/ld: cannot find -lssp_nonshared
/opt/broadcom/iproc/usr/lib/gcc/arm-broadcom-linux-uclibcgnueabi/4.9.3/../../../../arm-broadcom-linux-uclibcgnueabi/bin/ld: cannot find -lssp
collect2: error: ld returned 1 exit status
make[3]: *** [lldpd] Error 1
make[3]: Leaving directory `/home/testProject/apps/lldpd-1.0.3/src/daemon'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/home/testProject/apps/lldpd-1.0.3/src/daemon'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/testProject/apps/lldpd-1.0.3'
```

looking forward to you reply. thanks so much!

**Comment by vincentbernat** [comment]
Look in config.log why `-lssp` is added to ld command-line.

**Comment by luciazi** [comment]
in config.log , the "libssp" only appears here

configure:13136: $? = 0
configure:13125: /opt/broadcom/iproc/usr/bin/arm-linux-gcc -v >&5
Using built-in specs.
COLLECT_GCC=/opt/broadcom/iproc/usr/bin/arm-linux-gcc.br_real
COLLECT_LTO_WRAPPER=/opt/broadcom/iproc/usr/libexec/gcc/arm-broadcom-linux-uclibcgnueabi/4.9.3/lto-wrapper
Target: arm-broadcom-linux-uclibcgnueabi
Configured with: ./configure --prefix=/opt/broadcom/iproc/usr --sysconfdir=/opt/broadcom/iproc/etc --enable-static --target=arm-broadcom-linux-uclibcgnueabi --with-sysroot=/opt/broadcom/iproc/usr/arm-broadcom-linux-uclibcgnueabi/sysroot --disable-__cxa_atexit --with-gnu-ld _--disable-libssp_ --disable-multilib --with-gmp=/opt/broadcom/iproc/usr --with-mpfr=/opt/broadcom/iproc/usr --with-pkgversion='Buildroot 2015.11.1' --with-bugurl=http://bugs.buildroot.net/ --disable-libsanitizer --enable-tls --enable-plugins --enable-lto --disable-libmudflap --enable-threads --with-mpc=/opt/broadcom/iproc/usr --with-isl=/opt/broadcom/iproc/usr --with-cloog=/opt/broadcom/iproc/usr --with-float=soft --disable-decimal-float --with-abi=aapcs-linux --with-cpu=cortex-a9 --with-float=soft --with-mode=arm --enable-languages=c,c++ --with-build-time-tools=/opt/broadcom/iproc/usr/arm-broadcom-linux-uclibcgnueabi/bin --enable-shared --enable-libgomp
Thread model: posix

**Comment by luciazi** [comment]
hi vincent, 
if i want to porting it to arm-linux, can you help to provide a configuration example of ./configure？ 

./configure --host=arm-linux CC=/opt/broadcom/iproc/usr/bin/arm-linux-gcc --prefix=/home/testProject/apps/lldpd-1.0.3

Do i need add other arguments ？

**Comment by luciazi** [comment]
hi vincent, 
reference to other similar issues, the "ld -lssp" not happened now.
my configuration "./configure --host=arm-linux --with-sysroot=/opt/broadcom/iproc/usr/bin/arm-broadcom-linux-uclibcgnueabi-cc --with-privsep-user=root --disable-hardening CC=/opt/broadcom/iproc/usr/bin/arm-linux-gcc --prefix=/home/apps/lldpd-1.0.3/"

then make; make install  DESTDIR=/home/apps/lldpd-1.0.3;

and then I copied the lldpd and lldpctl to the device,  run with ./lldpd -ddd
output info as below:

/tmp # ./lldpd -ddd
1969-12-31T20:06:31 [CRIT/main] no _lldpd group for privilege separation, please create it

**Comment by vincentbernat** [comment]
Add `--with-privsep-group=root`.

**Comment by luciazi** [comment]
./configure --host=arm-linux --with-sysroot=/opt/broadcom/iproc/usr/bin/arm-broadcom-linux-uclibcgnueabi-cc --with-privsep-user=root --disable-hardening CC=/opt/broadcom/iproc/usr/bin/arm-linux-gcc --prefix=/home/apps/lldpd-1.0.3/ --with-privsep-group=root

but it seems do not work?
when i execute ./lldpd -ddd , it also prompt " [CRIT/main] no _lldpd group for privilege separation, please create it"

**Comment by luciazi** [comment]
./configure --host=arm-linux --with-sysroot=/opt/broadcom/iproc/usr/bin/arm-broadcom-linux-uclibcgnueabi-cc --with-privsep-user=root --disable-hardening CC=/opt/broadcom/iproc/usr/bin/arm-linux-gcc --prefix=/home/apps/lldpd-1.0.3/ --with-privsep-group=root

 _Privilege separation:
  Enabled........: yes
  User/group.....: root/root

but it seems do not work?
when i execute ./lldpd -ddd , it also prompt " [CRIT/main] no _lldpd group for privilege separation, please create it"

**Comment by luciazi** [comment]
hi vincent, 

after add --with-privsep-group=root, and then run ./lldpd -ddd, it show as below

1969-12-31T22:17:30 [INFO/privsep] no libcap support, running monitor as root
1969-12-31T22:17:30 [WARN/main] unable to execute /home/sbin/lldpcli: No such file or directory
1969-12-31T22:17:30 [WARN/main] configuration is incomplete, lldpd needs to be unpaused
1970-01-01T02:17:30 [INFO/main] protocol LLDP enabled
1970-01-01T02:17:30 [INFO/main] protocol CDPv1 disabled
1970-01-01T02:17:30 [INFO/main] protocol CDPv2 disabled
1970-01-01T02:17:30 [INFO/main] protocol SONMP disabled
1970-01-01T02:17:30 [INFO/main] protocol EDP disabled
1970-01-01T02:17:30 [INFO/main] protocol FDP disabled
1970-01-01T02:17:30 [INFO/event] libevent 2.0.22-stable initialized with poll method
1969-12-31T22:17:30 [INFO/privsep] unable to get system name
1969-12-31T22:17:30 [INFO/privsep] unable to get system name

**Comment by vincentbernat** [comment]
Give the path to lldpcli with `-L`.

**Comment by luciazi** [comment]
hi vincent, 
thanks for your help:)

./lldpd -ddd -L ./lldpcli , then it say:
1970-01-01T18:12:10 [WARN/lldp] some mandatory tlv are missing for frame received on eth0
1970-01-01T14:12:10 [INFO/lldpctl] lldpd should resume operations
