### ISSUE TITLE
After receiving the lldp packet with vlan, vlan will be automatically stripped?

### ISSUE THREAD

**Issue by achudejiejie** [vincentbernat/lldpd#319]
Hi, Vincent
I use lldpd to receive lldp message parsing normal, I want to receive lldp message with vlan and parse out vlan, but I found that the received message vlan is automatically stripped, I found this in lldpd_decode() Code:
/* Decapsulate VLAN frames */
     /*
Struct ether_header eheader;
Memcpy(&eheader, frame, sizeof(struct ether_header));
If (eheader.ether_type == htons(ETHERTYPE_VLAN)) {
// VLAN decapsulation means to shift 4 bytes left the frame from
// offset 2*ETHER_ADDR_LEN
Memmove(frame + 2*ETHER_ADDR_LEN, frame + 2*ETHER_ADDR_LEN + 4, s - 2*ETHER_ADDR_LEN);
s -= 4;
}*/
But even if I commented on this code, I received the message with vlan, and vlan was automatically stripped. Do you know what is going on?
I look forward to your answer, thank you very much!

**Comment by vincentbernat** [comment]
There is no other place where the VLAN is stripped. Do you see the VLAN when using tcpdump (`tcpdump -epni eth0 ether host 01:80:c2:00:00:0e` for example)?

**Comment by achudejiejie** [comment]
![image](https://user-images.githubusercontent.com/42258601/53937936-97cf1780-40e9-11e9-8f9c-d6ce1c9daf62.png)
captured by tcpdump -epni eth0 ether host 01:80:c2:00:00:0e

![image](https://user-images.githubusercontent.com/42258601/53937950-a1f11600-40e9-11e9-9a82-8d3f263c055f.png)
captured by tcpdump -eni eth0 ether host 01:80:c2:00:00:0e

**Comment by vincentbernat** [comment]
Then, lldpd should receive the VLAN tag as well. Add some `printf()` call around the part which tries to remove it to see what happens.

**Comment by achudejiejie** [comment]
I added a lot of prints before, and I can see that vlan has been stripped when recvfrom().
However, I have already adopted another solution to replace this problem.
Thank you for your reply! Thanks very much!
