### ISSUE TITLE
How to use LLDP and SNMP together?

### ISSUE THREAD

**Issue by goutaiping** [vincentbernat/lldpd#321]
Hi Vincent:
       I have successfully compiled net-snmp on linux, but I do not know how to compile LLDP with snmp ? it always fail!
      ./configure \
        CC=/opt/toolchain/arm_cortex-a8+vfpv3_gcc-4.8-linaro_eglibc-2.19_eabi/bin/arm-openwrt-linux-gnueabi-gcc \
        --host=arm-openwrt-linux-gnueabi \
        --sysconfdir=/etc \
        --localstatedir=/var \
        --prefix=/usr  \
        --with-gnu-ld \
        --enable-oldies \
        --enable-pie \
        --with-netlink-receive-bufsize=512 \
        --with-netlink-send-bufsize=512 \
        --enable-sanitizers \
        --enable-gcov \
        --with-snmp

Do you know why? Looking forward to your reply, Thank you

**Comment by vincentbernat** [comment]
How does it fail?

**Comment by goutaiping** [comment]
arm-openwrt-linux-gnueabi-gcc.bin: error: unrecognized command line option '-fsanitize=address,undefined'

**Comment by vincentbernat** [comment]
Try without enabling sanitizers.

**Comment by goutaiping** [comment]
I tried. I still made a mistake

**Comment by goutaiping** [comment]
Thank you very much. I have solved it，it need to specify a C++ compiler；
./configure 
CC=/opt/toolchain/arm_cortex-a8+vfpv3_gcc-4.8-linaro_eglibc-2.19_eabi/bin/arm-openwrt-linux-gnueabi-gcc 
CXX=/opt/toolchain/arm_cortex-a8+vfpv3_gcc-4.8-linaro_eglibc-2.19_eabi/bin/arm-openwrt-linux-gnueabi-g++
--host=arm-openwrt-linux-gnueabi 
--sysconfdir=/etc 
--localstatedir=/var 
--prefix=/usr 
--with-gnu-ld 
--enable-oldies 
--enable-pie 
--with-netlink-receive-bufsize=512 
--with-netlink-send-bufsize=512 
--enable-sanitizers 
--enable-gcov 
--with-snmp
