### ISSUE TITLE
statsTLVsUnrecognizedTotal is not incremented when unrecognized TLV is received

### ISSUE THREAD

**Issue by berkyakup** [vincentbernat/lldpd#323]
According to **IEEE Std 802.1 AB-2005** section **10.3.2 LLDPDU validation** page 37 statsTLVsUnrecognizedTotal should be incremented when a reserved TLV type is received. lldpd 0.9.8 fails to do this. Unfortunately I am not able to test the latest version but I believe that the latest version also have the same issue.

> If TLV_type_value is in the range of reserved TLV types in Table 9-1, the TLV is unrecognized and
may be a basic TLV from a later LLDP version. The statsTLVsUnrecognizedTotal counter shall be
incremented, and the TLV shall be assumed to be validated.

**Comment by vincentbernat** [comment]
Thanks for reporting this issue! This should be fixed by the latest commit.

**Comment by faslan88** [comment]
I want to ask something on top of this issue. When I checked with the latest version (1.0.4) by sending unrecognized LLDP TLV, unrecognizedTotal counter is increased as expected. 

However, I could not see other TLVs in the lldp package in that situation (such as lldpRemChassisID). The specification does not say similar to that the other TLVs could not be reachable. Therefore, I would expect to see other TLVs properly. What do you think about that ?

**Comment by vincentbernat** [comment]
What kind of TLV it is? If it is org/Dot1/Dot3, the TLV is just ignored. If it is neither of these 3, the whole LLDPU is dropped. Isn't what is expected by the standard (you know it better than me)?

**Comment by faslan88** [comment]
Thanks for the quick reply. I mean, think about the LLDPDU as below:

---------- Chassis Id TLV ----------
TLV Type                           = 0x01
0000 001. .... ....                = Chassis Id (1)
TLV Information String Length      = 0x9
.... ...0 0000 1001                = 9
Chassis Id Subtype                 = Locally Assigned (7)
Chassis Id                         = MyChassis
---------- Port Id TLV ----------
TLV Type                           = 0x02
0000 010. .... ....                = Port Id (2)
TLV Information String Length      = 0x7
.... ...0 0000 0111                = 7
Port Id Subtype                    = MAC Address (3)
Port Id                            = AB:CD:EF:AB:CD:EF
---------- Time To Live TLV ----------
TLV Type                           = 0x03
0000 011. .... ....                = Time To Live (3)
TLV Information String Length      = 0x2
.... ...0 0000 0010                = 2
Time To Live                       = 80
---------- Reserved TLV ----------
TLV Type                           = 0x09
0001 001. .... ....                = **Reserved (9)**
TLV Information String Length      = 0x4
.... ...0 0000 0100                = 4
Reserved                           = ABCD
---------- End Of LLDP TLV ----------
TLV Type                           = 0x00
0000 000. .... ....                = End Of LLDP (0)
TLV Information String Length      = 0x0
.... ...0 0000 0000                = 0

In this case, from my point of view, Chassis ID should be available but it returns null when I queried the lldpRemChassisID (1.0.8802.1.1.2.1.4.1.1.5) with getnext request.

**Comment by vincentbernat** [comment]
Doc says:

> If TLV_type_value is in the range of reserved TLV types in Table 9-1, the TLV is unrecognized and may be a basic TLV from a later LLDP version. The statsTLVsUnrecognizedTotal counter shall be
incremented, and the TLV shall be assumed to be validated.

So, I'll update lldpd to not discard the whole LLDPDU.
