### ISSUE TITLE
lldpStatsRxPortAgeoutsTotal is incremented when shutdown frame is received

### ISSUE THREAD

**Issue by berkyakup** [vincentbernat/lldpd#325]
According to _IEEE Std 802.1 AB-2005_ section _10.5.2.2 Reception counters_ **statsAgeoutsTotal** counter should be incremented only when **rxInfoTTL** is expired.

**lldpd** increments this counter when a shutdown frame is received, too. Since it is not upon expiration of **rxInfoTTL**, this counter should not be incremented in case of shutdown.

**Comment by vincentbernat** [comment]
I have pushed a commit to handle this case correctly. Thanks for reporting!
