### ISSUE TITLE
lldpcli colors not visible with Solarized dark

### ISSUE THREAD

**Issue by andrewimeson** [vincentbernat/lldpd#326]
# Bug description

The color scheme used by lldpcli to highlight commands for tab completion is not visible when using the Solarized dark color scheme unless I have to highlight the text (see screenshot) to be able to see the command completion

## Steps to reproduce the problem

 1. Change your terminal emulator color scheme to [Solarized](https://ethanschoonover.com/solarized/) dark

 2. Launch lldpcli and hit `?`to get possible commands

3. Be sad when you can't see them
 
## Expected outcome

Being able to see the text without highlighting, or at least being able to disable colorization.

## Current outcome

Top `?` shows what it looks like, and then below that is my workaround of highlighting the text

![image](https://user-images.githubusercontent.com/6353225/57115914-b0416400-6d1f-11e9-90c3-31fa139118b7.png)

# Additional information

 - iTerm2 running on macOS Mojave 10.14.4
 - Output of `lldpd -vv`:
 
```
lldpd 1.0.3
  Built on 2019-03-22T15:15:46Z

Additional LLDP features:    LLDP-MED, Dot1, Dot3, Custom TLV
Additional protocols:        CDP, FDP, EDP, SONMP
SNMP support:                no
Privilege separation:        enabled
Privilege separation user:   nobody
Privilege separation group:  nogroup
Privilege separation chroot: /var/empty
Configuration directory:     /usr/local/etc

C compiler command: clang  -Wunknown-warning-option -fdiagnostics-show-option -fdiagnostics-color=auto -pipe -Wall -W -Wextra -Wformat -Wformat-security -Wfatal-errors -Wcast-align -Wheader-guard -Wdocumentation -Winline -Wpointer-arith -fno-omit-frame-pointer -Wno-unused-parameter -Wno-missing-field-initializers -Wno-sign-compare -fstack-protector -fstack-protector-all -fstack-protector-strong  -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -g -O2 -I/usr/local/opt/readline/include -DRONLY=1
Linker command:     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld   -L/usr/local/opt/readline/lib -lresolv 

```

**Comment by vincentbernat** [comment]
I have pushed a commit to just use bold instead of some color. Thanks for reporting!
