### ISSUE TITLE
Missing End of LLDPDU TLV

### ISSUE THREAD

**Issue by chrischti** [vincentbernat/lldpd#328]
Hey guys,

I'm currently trying out lldpd and I'm experimenting with the custom-tlv feature. Everything seems to work fine. However, when there is one or more custom-tlv added, it seems like there is no End of LLDPDU TLV in the packet as specified by the standard and on the cisco page: https://learningnetwork.cisco.com/docs/DOC-26851. If there is no custom-tlv, the End ot LLDPDU TLV is available. 

I attached three screenshot of Wireshark showing packages with no, one or two custom-tlvs. The latter two show the error _Malformed Packet: LLDP_. Regardless of that, lldpd works fine in both cases, but it's probably not guaranteed that there won't occur any errors in interaction with other LLDP software.

![wireshark_no](https://user-images.githubusercontent.com/20052188/58155654-96d36e00-7c74-11e9-962e-290c7c1cb016.png)
![Wireshark_one](https://user-images.githubusercontent.com/20052188/58155655-96d36e00-7c74-11e9-8aeb-7c60b79041b9.png)
![Wireshark_two](https://user-images.githubusercontent.com/20052188/58155656-96d36e00-7c74-11e9-88ff-2464fb5040c7.png)

**Comment by vincentbernat** [comment]
Looking at the capture, the End of LLDPU TLV is here (it's `00 00` at the end). It seems Wireshark is confused by the custom TLV and doesn't parse further it which explains why it sees only one custom TLV and doesn't see the End of LLDPU TLV. I think Wireshark is just not expecting to have an empty custom TLV (just OUI and subtype, no payload). If you add one additional byte to your custom TLV, does it work?

**Comment by chrischti** [comment]
Yes, you're right. Adding an additional byte removes the Exception in Wireshark. In this case it looks more like a Wireshark issue than a lldpd issue, because the standard explicitly allows empty TLV information strings (see page 24 in https://benstdynet.files.wordpress.com/2015/04/lldp-tlv.pdf).

Thanks for your help! I'll write a new bug report at the Wireshark project.

**Comment by tanstafel** [comment]
> Yes, you're right. Adding an additional byte removes the Exception in Wireshark. In this case it looks more like a Wireshark issue than a lldpd issue, because the standard explicitly allows empty TLV information strings (see figure 8-12 on page 35 in https://benstdynet.files.wordpress.com/2015/04/lldp-tlv.pdf).
> 
> Thanks for your help! I'll write a new bug report at the Wireshark project.

Can you provide the Wireshark issue number, please? It seems to be not yet fixed yet...

Thanks!

**Comment by mister-mojo** [comment]
> > Yes, you're right. Adding an additional byte removes the Exception in Wireshark. In this case it looks more like a Wireshark issue than a lldpd issue, because the standard explicitly allows empty TLV information strings (see figure 8-12 on page 35 in https://benstdynet.files.wordpress.com/2015/04/lldp-tlv.pdf).
> > Thanks for your help! I'll write a new bug report at the Wireshark project.
> 
> Can you provide the Wireshark issue number, please? It seems to be not yet fixed yet...
> 
> Thanks!

Hi tanstafel, 

I'm really sorry but I'm not sure anymore if I really opened a new Wireshark issue. As I remember, the project team I was working on at this time changed their mind and decided to go another way and forgot about this problem. If you're currently struggling with this issue and are keen on opening a new issue in the Wireshark bug tracker, feel free to use my description and images there for illustration.

**Comment by tanstafel** [comment]
Ok, thank's for the information.  Maybe I'll do.

**Comment by tanstafel** [comment]
Just for reference: I debugged and fixed this yesterday in Wireshark:

https://gitlab.com/wireshark/wireshark/-/merge_requests/2344
