### ISSUE TITLE
What Dot & Dot3 means

### ISSUE THREAD

**Issue by zhr2130** [vincentbernat/lldpd#336]
Hi Vincent,

I have a question what's Dot and Dot3 means (definition), is it a protocol or something like that?

I googled Dot & Dot3 but not find any suitable answer.

Would you please give some explaination.

Thanks

**Comment by vincentbernat** [comment]
They are part of the 802.1AB standard. Dot1 TLVs include information about VLAN. Dot3 TLVs include information about speed, power and link aggregates.
