### ISSUE TITLE
New Feature: Use of ifname instead of IP address for management interface?

### ISSUE THREAD

**Issue by stannous** [vincentbernat/lldpd#349]
Hello,

We have some users that would prefer to have the eth0 IP address 
(a dhcp obtained address) always preferred as the management IP address
instead of the first IPv4 or IPv6 address.

I would prefer that users just use a wildcard for this and specify what they
know to be in the dhcp pool for their eth0 interfaces (192.*).

And since the dhcp addresses for eth0 can change, I'm wondering how much 
work it would be to restructure lldpd "re-learn" the new eth0 IP address and use that
as the management IP.  

Thanks,
Sam Tannous
Cumulus Networks

**Comment by vincentbernat** [comment]
OK, that shouldn't be difficult to add.

**Comment by stannous** [comment]
Thanks, Vincent.  I'll be happy to test this.
