### ISSUE TITLE
LLDPDU Order of Frame Validation

### ISSUE THREAD

**Issue by yunusemreayhan** [vincentbernat/lldpd#351]
Description : 
According to 802.1AB-2005 in 10.3.2 the order of mandatory TLVs is important, as far as what i can see, this library does not care about the order of mandatory TLVs. When our test case send an LLDPDU which does not have the order specified in the mentioned specification, statsFramesDiscardedTotal counter is not incremented as expected.

For example: when we send PortId as first TLV and chassisID as second TLV then statsFramesDiscardedTotal  counter shall be incremented according to specification. However, it is not incremented.

I am not telling about the details, because it is quite general.

**Comment by vincentbernat** [comment]
I'll fix that later this month. Thanks for the report.
