### ISSUE TITLE
Missing lldpRemManAddrTable MIBs

### ISSUE THREAD

**Issue by singirti** [vincentbernat/lldpd#352]
Hi

It seems that some MIBs are missing like lldpRemManAddrTable. When we run the snmpwalk command it does not return anything

BR

**Comment by vincentbernat** [comment]
Which version are you using? It works fine for me:

```
$ snmpwalk -v 2c -c public -M +. localhost LLDP-MIB::lldpRemManAddrTable
LLDP-MIB::lldpRemManAddrIfSubtype.6100.2.1.ipV4."..w'" = INTEGER: ifIndex(2)
LLDP-MIB::lldpRemManAddrIfId.6100.2.1.ipV4."..w'" = INTEGER: 13
LLDP-MIB::lldpRemManAddrOID.6100.2.1.ipV4."..w'" = OID: SNMPv2-SMI::zeroDotZero
```

**Comment by singirti** [comment]
We use 1.0.4. When I run snmpwalk command for LLDP-MIB::lldpRemManAddrTable, I got the following error:

LLDP-MIB::lldpRemManAddrTable: Unknown Object Identifier

**Comment by vincentbernat** [comment]
❦ 30 septembre 2019 10:48 -07, singirti <notifications@github.com>:

> We use 1.0.4. When I run snmpwalk command for LLDP-MIB::lldpRemManAddrTable, I got the following error:
>
> LLDP-MIB::lldpRemManAddrTable: Unknown Object Identifier

That's an error meaning the MIB is not known. If you have it in the
current directory, add "-M +." to snmpwalk command line.

**Comment by singirti** [comment]
I added LLDP-MIB ( and needed libs  RMON2-MIB and TOKEN-RING-RMON-MIB) to current directory. Besides I added  following lines to snmpd.conf and restarted lldpd and snmpd;
rocommunity private 127.0.0.1 .1

I started to get following error:
#snmpwalk -v 2c -c private -M +. localhost LLDP-MIB::lldpRemManAddrTable
LLDP-MIB::lldpRemManAddrTable = No Such Object available on this agent at this OID

Do you have any idea?

**Comment by vincentbernat** [comment]
You need to ensure AgentX communication is enabled. Starts lldpd with `-x`, add `master agentx` to your `snmpd.conf`.

**Comment by singirti** [comment]
yes AgentX is enabled and started with -x but same result. It seems that there is a problem on my side. Thanks for your support.
