### ISSUE TITLE
New to compiling here.. Anyone want to give me the binary for android please?

### ISSUE THREAD

**Issue by medicohilleroed** [vincentbernat/lldpd#360]

**Comment by medicohilleroed** [comment]
Spent days of my life trying to install compiling tools in linux for android platform now.
Just please someone compile this for Android platform.
When I'm done I'll give everything I've done so far back to the community.
I'm working on a project to create a network analyser using an android with a USBc to enthernet.

**Comment by medicohilleroed** [comment]
Finally after weeks of reading learning https://drive.google.com/drive/folders/1Q7Vzmaaw42yI8FCar0Z-rHFUCqeWI9dV?usp=sharing binaries for Android.
All but *.so need to go into /system/bin & *.so needs to be put in /system/bin/lib64

Awesome now I have the equivalent to a Netscout but for the 10th of the cost.

medicohih@medicohih-ThinkPad-T520 ~/llpd/lldpd/build/install/system/lib $ adb -s hih-medico-netcub:5555 shell
hih-medico-netcub:/ # lldpctl
-------------------------------------------------------------------------------
LLDP neighbors:
-------------------------------------------------------------------------------
Interface:    eth0, via: LLDP, RID: 4, Time: 0 day, 00:00:52
  Chassis:     
    ChassisID:    mac 78:48:59:5c:e1:5e
    SysName:      HIH_UX68_ST_01
    SysDescr:     HP Comware Platform Software, Software Version 5.20.99 Release 2221P08
                  HP A5120-48G-PoE+ EI Switch with 2 Interface Slots
                  Copyright (c) 2010-2015 Hewlett-Packard Development Company, L.P.
    Capability:   Bridge, on
    Capability:   Router, on
  Port:        
    PortID:       ifname GigabitEthernet1/0/18
    PortDescr:    Data port
    TTL:          120
    MFS:          9216
    PMD autoneg:  supported: yes, enabled: yes
      Adv:          10Base-T, HD: yes, FD: yes
      Adv:          100Base-TX, HD: yes, FD: yes
      Adv:          1000Base-T, HD: no, FD: yes
      MAU oper type: 1000BaseTFD - Four-pair Category 5 UTP, full duplex mode
    MDI Power:    supported: yes, enabled: yes, pair control: no
      Device type:  PSE
      Power pairs:  signal
      Class:        class 0
      Power type:   2
      Power Source: PSE
      Power Priority: low
      PD requested power Value: 0
      PSE allocated power Value: 0
  VLAN:         680, pvid: yes ADM
  PPVID:        supported: yes, enabled: no
-------------------------------------------------------------------------------
hih-medico-netcub:/ # 
[lldpAndroid.tar.gz](https://github.com/vincentbernat/lldpd/files/3855779/lldpAndroid.tar.gz)

**Comment by Mailstorm-ctrl** [comment]
I'd like to say that this is one of the only results that comes up when searching for LLDPD on Android. The google doc link no longer contains anything so if someone could maybe help me out, that would be rad. Thanks
