### ISSUE TITLE
problem: sent lldp and cdp messages simultaneously

### ISSUE THREAD

**Issue by superscari** [vincentbernat/lldpd#361]
excellent work ,Vincent!
i use this for sending lldp and cdp simutaneously in my own pc with Centos7.7, but `lldpd -ccc` just send cdp, `lldpd -l` just send lldp, two type message cannot be sent simutaneously.   Otherwise, the same installation and `lldpd -ccc` can send lldp and cdp meanwhile on three centos7.3 computers and another centOS 7.7 pc.    
so, how can i send lldp and cdp simutaneously,when `lldpd -ccc` cannot work with `lldpd -l`?
thanks, in advance

**Comment by vincentbernat** [comment]
Did you try `lldpd -l -ccc`?

**Comment by superscari** [comment]
Great,thank u!
