### ISSUE TITLE
General validation rules for all TLVs

### ISSUE THREAD

**Issue by aslanfatih** [vincentbernat/lldpd#363]
According to IEEE Std 802.1AB-2016 Section 9.2.7.7.2 Page 52 'General validation rules for all TLVs' and 10.3.2.1 General validation rules for all TLVs'  If the LLDPDU contains more than one Chassis ID TLV, Port ID TLV, or Time To Live TLV:
1) The LLDPDU shall be discarded.
2) The statsFramesDiscardedTotal and statsFramesInErrorsTotal counters shall both be
incremented. 
When I tested with v1.0.4, it does not work for all types of mandatory TLVs. Since the validation rule is clear enough, I will not go into details.

Thanks for the help

**Comment by vincentbernat** [comment]
This should already be fixed in #356. The fix should be in 1.0.5 which will be released later this month.
