### ISSUE TITLE
TLV includes extra octets when TLV length value is greater than its value length

### ISSUE THREAD

**Issue by eateibr** [vincentbernat/lldpd#368]
We set `Chassis Id` TLV's length as 27 and it's value with 7 length string (ex:  00:00:00:00:00:10). However, when we check its value with snmpwalk we see extra octets on the response. According to spec, these extra octets shall be ignored.

> IEEE Std 802.1AB-2005 Section 10.3.2.1 Page 37 'General validation rules for all TLVs'
> If the TLV information string length value is greater than the sum of  the lengths of all fields contained in the TLV information string:
> 1) The extra octets shall be ignored.
> 2) The location of the next TLV shall be based on the TLV information  string length value of the current TLV.

**Request:**
LLDP: TLV Type                           = 0x01
LLDP: 0000 001. .... ....                = Chassis Id (1)
LLDP: TLV Information String Length      = 0x1B
LLDP: .... ...0 0001 1011                = 27
LLDP: Chassis Id Subtype                 = MAC Address (4)
LLDP: Chassis Id                         = 00:00:00:00:00:10

**Snmpwalk Response:**
 ip netns exec fib_2 snmpwalk -v1 -c public localhost 1.0.8802.1.1.2
...
iso.0.8802.1.1.2.1.4.1.1.5.1400.6.1 = Hex-STRING: 00 00 00 00 00 10 **_00 00 98 E1 58 72 39 00 00 00 21 00 00 00 00 00 00 00 01 00_**

**Comment by vincentbernat** [comment]
There is no length associated to the chassis ID "string". It's the length of the TLV which is used to know how long it is. The standard doesn't say how long a MAC address is expected to be. In your case, the TLV length is 27, hence the chassis ID is 26 bytes long.

**Comment by eateibr** [comment]
Chassis Id is just an example here. Specs says that:

> If the TLV information string length value is greater than the sum of the lengths of all fields contained in the TLV information string:
> 
> The extra octets shall be ignored.

So in this case, I am expecting to see only what I set ( for example 00:00:00:00:00:10). But I see extra octets in snmpwalk response. Am I missing some point here?

**Comment by vincentbernat** [comment]
Is lldpd crafting the TLV or do you use another software for that? The problem is that the TLV is too long for its content. TLV length should be 7.

**Comment by eateibr** [comment]
Yes you are right, but here we are testing a special scenario.  In this scenario TLV information string length is greater than it's content. When this kind of packets arrived to lldp deamon we expect that extra octets shall be discarded according to spec.

**Comment by vincentbernat** [comment]
The Chassis ID TLV is defined by the subtype (1 byte) and the chassis ID itself (the remaining bytes). There is no length encoded for this last piece of information. There is no way to know there are extra bytes.
