### ISSUE TITLE
show protocols lldpd is using now

### ISSUE THREAD

**Issue by denisgubin** [vincentbernat/lldpd#369]
Hi, Vincent

1. How can I see what protocols(lldp or cdp, edp) is lldpd using now?
For example: via lldpcli show ...

2. Can I setup main daemon lldpd for transmit only but allow transmit?

There
https://vincentbernat.github.io/lldpd/usage.html

I can see only flag -r (Receive-only mode)
 -r      Receive-only mode. With this switch, lldpd will not send any
             frame. It will only listen to neighbors.

lldpd -v
1.0.3

**Comment by vincentbernat** [comment]
1. The information about the currently selected protocol for a given interface is not available through lldpcli. Several protocols can be active for a given port. If you mean which protocols are enabled, this is not exposed either, but you choose this through the command-line.

2. `configure lldp status tx-only` should work.

**Comment by denisgubin** [comment]
Thanks for your answer.

About my questions 1.
Now I can see selected protocols in 2 ways:
1) in default config file /etc/default/lldpd
```
cat /etc/default/lldpd 
DAEMON_ARGS="-c -s -e -f"
```

2)  through shell command
```
sudo systemctl status lldpd.service 
● lldpd.service - LLDP daemon
   Loaded: loaded (/lib/systemd/system/lldpd.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2019-11-26 09:48:03 MSK; 6min ago
     Docs: man:lldpd(8)
  Process: 1120 ExecStartPre=/bin/mkdir -p /var/run/lldpd (code=exited, status=0/SUCCESS)
 Main PID: 1123 (lldpd)
    Tasks: 2 (limit: 4915)
   CGroup: /system.slice/lldpd.service
           ├─1123 lldpd: monitor. 
           └─1165 lldpd: connected to KX-UT113RU.

nov 26 09:48:03 dgubin-pc systemd[1]: Started LLDP daemon.
nov 26 09:48:03 dgubin-pc lldpd[1165]: protocol CDPv1 enabled
nov 26 09:48:03 dgubin-pc lldpd[1165]: protocol CDPv2 enabled
nov 26 09:48:03 dgubin-pc lldpd[1165]: protocol SONMP enabled
nov 26 09:48:03 dgubin-pc lldpd[1165]: protocol EDP enabled
nov 26 09:48:03 dgubin-pc lldpd[1165]: protocol FDP enabled
```
May be if I could see them (protocols) through lldpcli It would be nice.

 About my questions 2:
Command `configure lldp status tx-only` still work until reboot.
Sure I can put this command in file and then put it in config folder `/etc/lldpd.d/` and then if I reboot the command still work.
But if I could do it trough configuration file` /etc/default/lldpd `it would be comfortable...may be.

**Comment by vincentbernat** [comment]
About 2, the idea is to have most settings go through lldpcli. Command-line flags are considered as legacy. This is to avoid to reimplement twice the same configuratio mechanism.

About 1, I don't have much time to implement this feature, but if you want to propose a patch to add it under `show configuration`, I will accept it.

**Comment by denisgubin** [comment]
Thanks for your answer.

About my questions 1.
Now I can see selected protocols in 2 ways:
1) in default config file /etc/default/lldpd
```
cat /etc/default/lldpd 
DAEMON_ARGS="-c -s -e -f"
```

2)  through shell command
```
sudo systemctl status lldpd.service 
● lldpd.service - LLDP daemon
   Loaded: loaded (/lib/systemd/system/lldpd.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2019-11-26 09:48:03 MSK; 6min ago
     Docs: man:lldpd(8)
  Process: 1120 ExecStartPre=/bin/mkdir -p /var/run/lldpd (code=exited, status=0/SUCCESS)
 Main PID: 1123 (lldpd)
    Tasks: 2 (limit: 4915)
   CGroup: /system.slice/lldpd.service
           ├─1123 lldpd: monitor. 
           └─1165 lldpd: connected to KX-UT113RU.

nov 26 09:48:03 dgubin-pc systemd[1]: Started LLDP daemon.
nov 26 09:48:03 dgubin-pc lldpd[1165]: protocol CDPv1 enabled
nov 26 09:48:03 dgubin-pc lldpd[1165]: protocol CDPv2 enabled
nov 26 09:48:03 dgubin-pc lldpd[1165]: protocol SONMP enabled
nov 26 09:48:03 dgubin-pc lldpd[1165]: protocol EDP enabled
nov 26 09:48:03 dgubin-pc lldpd[1165]: protocol FDP enabled
```
May be if I could see them (protocols) through lldpcli It would be nice.

 About my questions 2:
Command `configure lldp status tx-only` still work until reboot.
Sure I can put this command in file and then put it in config folder `/etc/lldpd.d/` and then if I reboot the command still work.
But if I could do it trough configuration file` /etc/default/lldpd `it would be comfortable...may be.

**Comment by denisgubin** [comment]
You mean want to tell configuration lldpd through command-line there `/etc/default/lldpd` is legacy method?  
How can I setup lldpd without flags (example: -c  -e -ll) at all?

**Comment by vincentbernat** [comment]
For these particular options, there is no other way than the command-line. I was saying command-line arguments are considered as a legacy in the sense I don't want to add more of them as I have to implement and maintain two different methods (through the command-line argument and through lldpcli).

**Comment by denisgubin** [comment]
I see. Thanks!

And I have another one question.

In documentation `https://vincentbernat.github.io/lldpd/usage.html` I see article about setup up `cdp` protocol:
```

     -c      Enable the support of CDP protocol to deal with Cisco routers
             that do not speak LLDP. If repeated, CDPv1 packets will be sent
             even when there is no CDP peer detected.
```
What does sentence `CDPv1 packets will be sent even when there is no CDP peer detected.` mean?

This mean lldpd with config `DAEMON_ARGS="-c -ll"` doesn't send CDP packets while receive cdp packets from neighbor.

I mean can lldpd detect CDPv1 packect?  

Another hand:
If lldpd have `force mode`(example:  `DAEMON_ARGS="-cc -ll"`) 
It will be send cdp packets v1 in any case `even when there is no CDP peer detected`.

Am I right?

**Comment by vincentbernat** [comment]
Yes, you are right. lldpd is initially an LLDP implementation. But if it detects the peer is using another protocol, it will switch to this other protocol, instead of LLDP. The idea is that for old equipments, if you send LLDP packets, they don't understand it and will send them to all their peers. The heuristic is explained later in the manual page.

**Comment by denisgubin** [comment]
I see. 
Many Thanks, Vincent !

**Comment by denisgubin** [comment]
Hi, Vincent

I have another problem.

I tried to setup lldpd through config file which was putted in to` /etc/lldpd.d` folder 
For example:
I created file system_descr.conf with command inside.
```
cat system_descr.conf 
lldpcli configure system description Test
```
After that I restarted daemon lldpd
```
systemctl restart lldpd.service
```

But I saw error in syslog's journal

` lldpcli[28980]: unknown command from argument 1: `lldpcli``

But If I tried to execute the command trough lldpcli I got result.
What did  I do incorrect in `system_descr.conf` file?

**Comment by vincentbernat** [comment]
Remove the `lldpcli` at the beginning of the line. These files contain commands to be executed by lldpcli.

**Comment by denisgubin** [comment]
Thanks for answer, Vincent !

**Comment by denisgubin** [comment]
Hi, Vincent!

Could you advice me, I change come configurations such as through `/etc/default/lldpd` file or `/etc/conf.d/somename.conf` file I should restart daemon `systemctl restart lldpd.service` or better do` lldpcli update `
?  
I ask you since if I try  restart daemon daemon after that will send lldpdu packet with TTL=0 or not ?

**Comment by vincentbernat** [comment]
For `/etc/default/lldpd`, you need an update. When modifying `/etc/lldpd/somename.conf`, you can also update with `cat /etc/lldpd/somename.conf | lldpcli`. But maybe it's easier to just restart. The LLDPU with TTL=0 is mandated by the standard when there is a shutdown of the agent (which happens on restart).

**Comment by denisgubin** [comment]
I wonder How it is made in cisco or other vendors?
For example: if changed paramer "chassis id" lldpd packet with ttl=0 will be sent?

**Comment by vincentbernat** [comment]
Yes, change to MSAP should trigger sending an LLDPU with TTL 0 for the old MSAP.

**Comment by denisgubin** [comment]
I wonder wil ttl=0 is sent if changed mandatory fields or any fields such as system description and others?

**Comment by denisgubin** [comment]
Hi, Vincent!

Could you give me some advice?

Can I add to config_file `/etc/lldpd.d/cfg.conf` strings format below ?:
```
configure system hostname "something name of my workstation"
configure system ip management pattern "1.2.3.4"
```

Can I add configure value inside `""` symbols ?

**Comment by vincentbernat** [comment]
Yes, it should work.

**Comment by denisgubin** [comment]
For example, I had added string like this
`configure lldp portdescription ""`
Then, I restarted service lldpd I saw several strings such as:
```
lldpcli[13742]: unable to set LLDP Port Description for eth0. No error
lldpcli[13742]: unable to set LLDP Port Description for eth1. No error
lldpcli[13742]: unable to set LLDP Port Description for eth2. No error
```

What does it mean?
It mean to unable to set up blank value to port description and it no error just notification for me?

**Comment by denisgubin** [comment]
Good day, Vincent!

Could you answer for my question?
When lldpd service is started with default value:
```
 cat /etc/default/lldpd 
# Uncomment to start SNMP subagent and enable CDP, SONMP and EDP protocol
#DAEMON_ARGS="-x -c -s -e"
```
Have 4 LLDPDU been sent or not through up inteface?

**Comment by vincentbernat** [comment]
For port description, I would expect this to work. If it's okay with you, try to use `" "` (with a space).

I don't understand your second question. Why not try yourself?

**Comment by denisgubin** [comment]
Sure I can to try but may be it is in lldpd's instruction or 802.1ab standard?
In instruction `https://vincentbernat.github.io/lldpd/usage.html` I can see information in section `configure med fast-start enable | tx-interval interval`
Text `Once 4 LLDPDU have been sent` mean it would be happen if configure med fast-start enable or just start service lldpd ?

**Comment by vincentbernat** [comment]
I don't know for sure. It would be easier for you to try. I think that just enabling the option would not send the LLDPDU.

**Comment by denisgubin** [comment]
Good day, Vincent!

1. About lldpd service is started with default value.

My scheme: 
Virtual Machine with OS Debian <----- > My host with Ubuntu (physical PC)

Before install lldpd service on VM OS (Debian) I stopped lldpd service on My host with Ubuntu.

I've installed lldpd service on VM OS (Debian). 

>  lldpd -v
> 1.0.3

with default value
>  cat /etc/default/lldpd 
> #DAEMON_ARGS="-x -c -s -e"


> systemctl status lldpd.service 
> ● lldpd.service - LLDP daemon
>    Loaded: loaded (/lib/systemd/system/lldpd.service; enabled; vendor preset: en
>    Active: active (running) since Fri 2020-01-10 10:22:59 MSK; 1h 11min ago
>      Docs: man:lldpd(8)
>  Main PID: 690 (lldpd)
>     Tasks: 2 (limit: 4692)
>    Memory: 1.8M
>    CGroup: /system.slice/lldpd.service
>            ├─690 lldpd: monitor. 
>            └─775 lldpd: connected to My host with Ubuntu.
> 
> [systemd[1]Started LLDP daemon.
>   [775]/etc/localtime copied to chroot
>  [775] protocol LLDP enabled
>  [775]protocol CDPv1 disabled
>   [775]protocol CDPv2 disabled
>   [775]protocol SONMP disabled
>  [775]protocol EDP disabled
>  [775]protocol FDP disabled
>  [775]libevent 2.1.8-stable initialized wi
>  [690]lldpd should resume operations

 
Result: 
I can see lldp frame from VM OS (Debian) and every 30 seconds.
But why?
I shouldn't have seen them with default settings I thought ?

By article in instruction:

> https://vincentbernat.github.io/lldpd/usage.html

> 
>      -l      Force to send LLDP packets even when there is no LLDP peer de-
>              tected but there is a peer speaking another protocol detected.
>              By default, LLDP packets are sent when there is a peer speaking
>              LLDP detected or when there is no peer at all. If repeated,
>              LLDP is disabled.

I confuse with this:

> By default, LLDP packets are sent when there is a peer speaking
 >              LLDP detected or when there is no peer at all

What does when there is no peer at all mean ?


And many thanks for your answers, Vincent!

**Comment by vincentbernat** [comment]
By default, lldpd will send LLDPU on an interface unless it detects there is someone speaking another protocol like CDP/FDP/NDP.

**Comment by denisgubin** [comment]
I see, thanks!
Peer - mean someone of neighbors who speaks on same protocols?

**Comment by vincentbernat** [comment]
Yes.

**Comment by denisgubin** [comment]
I've disabled lldp protocol on My host with Ubuntu (physical PC) and enabled CDPv2 forced but LLDPU is sent by VM OS (Debian).
And VM OS (Debian) doesn't stop to send LLDPU towards My host with Ubuntu (physical PC)

Now the settings is :
My scheme is same:
Virtual Machine with OS Debian <----- > My host with Ubuntu (physical PC)

 My host with Ubuntu (physical PC)
> cat /etc/default/lldpd 
> DAEMON_ARGS="-cccc -ll"

VM OS (Debian) (by default)

>  cat /etc/default/lldpd 
> # Uncomment to start SNMP subagent and enable CDP, SONMP and EDP protocol
> #DAEMON_ARGS="-x -c -s -e"

Why  doesn't Virtual Machine with OS Debian stop to send LLDPU towards My host with Ubuntu (physical PC)?

**Comment by vincentbernat** [comment]
You need to specifically enable CDP (with one `-c`). By default, only LLDP is enabled.

**Comment by denisgubin** [comment]
My scheme is same:
Virtual Machine with OS Debian <----- > My host with Ubuntu (physical PC)

My host with Ubuntu (physical PC)

    cat /etc/default/lldpd
    DAEMON_ARGS="-cccc -ll"

VM OS (Debian) (by default)

    cat /etc/default/lldpd
    #DAEMON_ARGS="-x -c -s -e"

VM OS (Debian) continues to send LLDP frames since there is no peer on VM OS (Debian) at all.
Another words VM OS (Debian) doesn't understand CDPv2 protocols and that is why VM OS (Debian) continues to send LLDP frames.

Am I right?

**Comment by vincentbernat** [comment]
You need to uncomment the `DAEMON_ARGS` in the second case.

**Comment by denisgubin** [comment]
Thanks for answer!

**Comment by denisgubin** [comment]
Good evening,  Vincent!

Could you explain me about options (not forced)?
I've been confused.
Why doesn't simple use forced options: -l, -cc, -ccc, -ee, and etc ?

**Comment by denisgubin** [comment]
Hello, Vincent!

I wonder can I select different protocol for different interfaces?
Example:
eth1 - "-c -l"
eth2 - "-e -s"

and etc

**Comment by vincentbernat** [comment]
It's not possible.

**Comment by denisgubin** [comment]
Many thanks for your answer.
Could you answer another one my quiestion?

As I understood correct I can configure from lldplci parametrs related to only lldp protocol, am I right?

> lldpcli configure ports [ports ethX [,…]] lldp status rx-and-tx | rx-only |
       tx-only | disabled

And How about the same paramets for other protocols?

**Comment by vincentbernat** [comment]
All protocols are affected by this setting. lldpd is mostly a LLDP daemon which is able to translate to other protocols.

**Comment by denisgubin** [comment]
Vincent, thanks, I see.

Could you please tell me about difference of this config lines?

> configure ports eth1 lldp status disabled
 and
> configure system interface pattern "*,!eth1"

Does the config-lines do the same operation: disable all protocols on interface eth1?

**Comment by vincentbernat** [comment]
Yes.

**Comment by denisgubin** [comment]
Is there a commands to revert default value?

port_description on "eth1" is eth1 (by default)
I've changed it to "something_text".
Example:
lldpcli configure ports ens1 lldp portdescription "something_text"

And can I revert back value to the default value "eth1"
Does so command exist?

**Comment by vincentbernat** [comment]
For some commands, there is `unconfigure`. Otherwise, not, there is not.

**Comment by denisgubin** [comment]
Thanks for your answers!

I have another one question.
I've changed interface port status 
`lldpcli configure ports ens1 lldp status rx-only `

But I can't see changes by show command in string `Receive` mode: no`

> lldpcli show configuration 
> -------------------------------------------------------------------------------
> Global configuration:
> -------------------------------------------------------------------------------
> Configuration:
>   Transmit delay: 30
>   Transmit hold: 4
>   Receive mode: no
>   Pattern for management addresses: 192.168.1.1
>   Interface pattern: (none)
>   Permanent interface pattern: (none)
>   Interface pattern for chassis ID: (none)
>   Override chassis ID with: /srv
>   Override description with: srv-1
>   Override platform with: Linux
>   Override system name with: some-text
>   Advertise version: yes
>   Update interface descriptions: no
>   Promiscuous mode on managed interfaces: no
>   Disable LLDP-MED inventory: yes
>   LLDP-MED fast start mechanism: yes
>   LLDP-MED fast start interval: 1
>   Source MAC for LLDP frames on bond slaves: local
>   Port ID TLV subtype for LLDP frames: unknown
>   Agent type:   unknown
>

**Comment by vincentbernat** [comment]
Receive mode is only when lldpd is started with `-r`. I don't think this information is exposed.

**Comment by denisgubin** [comment]
Vincent, could you tell me does LLDP daemon has own DB to order to store information about neighbors(peers) and update it if something chages?

**Comment by vincentbernat** [comment]
It keeps the data in memory.

**Comment by denisgubin** [comment]
Good day, Vincent!

Could yo tell me what does 'my-pc' mean in output below?
Is it system name?

```
{'lldp': {'interface': {'ens1': {'via': 'LLDP',
    'rid': '1',
    'age': '0 day, 02:57:28',
    'chassis': {'my-pc': {'id': {'type': 'mac',
       'value': '1a:10:0d:22:d0:f6'},
      'descr': 'Ubuntu 18.04.3 LTS Linux 5.3.0-26-generic',
      'mgmt-ip': ['192.168.1.1'],
      'capability': [{'type': 'Bridge', 'enabled': True},
       {'type': 'Router', 'enabled': True},
       {'type': 'Wlan', 'enabled': False},
       {'type': 'Station', 'enabled': False}]}},
    'port': {'id': {'type': 'mac', 'value': 'fe:34:45:00:21:01'},
     'descr': 'eth10',
     'ttl': '120'}}}}}
```

**Comment by denisgubin** [comment]
Hi, Vincent!

I've again got problem.

If I use EDP protocol and set params chassis ID as "something text" LLDP doesn't send LLDP PDU and I see error in syslog

>  "local chassis does not use MAC address as chassis ID!?"
 
Could you tell me please Why doens't I can use own Chassis ID text?

**Comment by vincentbernat** [comment]
With EDP, it's not possible to have anything else than a MAC address for the chassis ID.

**Comment by denisgubin** [comment]
Well can I unconfigure Chassis ID as MAC address by myself from lldpcli configure?
May be this command will be helped me?

> unconfigure system chassisid

Can I set up own from lldpcli any MAC address for Chassis ID? (for EDP)

**Comment by denisgubin** [comment]
Good day, Vincent!

Coulld you answer to my quiestion above?

Many thanks!

**Comment by vincentbernat** [comment]
It is not possible to override the MAC address.

**Comment by denisgubin** [comment]
Thanks for answer, Vincent.

Could you please tell me about `rid` in output below.
What does it mean?

```
{'lldp': {'interface': {'ens1': {'via': 'LLDP',
    'rid': '1',
    'age': '0 day, 02:57:28',
    'chassis': {'my-pc': {'id': {'type': 'mac',
       'value': '1a:10:0d:22:d0:f6'},
      'descr': 'Ubuntu 18.04.3 LTS Linux 5.3.0-26-generic',
      'mgmt-ip': ['192.168.1.1'],
      'capability': [{'type': 'Bridge', 'enabled': True},
       {'type': 'Router', 'enabled': True},
       {'type': 'Wlan', 'enabled': False},
       {'type': 'Station', 'enabled': False}]}},
    'port': {'id': {'type': 'mac', 'value': 'fe:34:45:00:21:01'},
     'descr': 'eth10',
     'ttl': '120'}}}}}
```

**Comment by vincentbernat** [comment]
It's the internal ID assigned to the remote device.

**Comment by denisgubin** [comment]
Good day, Vincent!

Could you tell me where is lldpd daemon get information about system capabilities from?

And I am glad you are answer my questions.
Thanks you for that!

**Comment by denisgubin** [comment]
Hello, Vincent!

Could you tell me please why doesn't lldpd daemon run at loopback's interfaces?
It's correct daemon behavior?

**Comment by denisgubin** [comment]
Hello, Vincent!

Could you answer for my questions above?

I have another questions:

What does "Port is aggregated" mean in lldpcli show neighbors details comand?
Is it mean neighbors' port is LACP member?

What does "MFS" mean in lldpcli show neighbors details comand?
It is mean Maximum Frame Size (MFS) and it is not same MTU?

**Comment by vincentbernat** [comment]
Hello Denis,

Sorry, but I don't have time to answer questions on every aspects of lldpd. Your new questions are part of the 802.1AB standard.

**Comment by emrahtavsan** [comment]
Hi Vincent,

I added lldp 1.0.4 to Petalinux. but I want to use it with snmp. When I add "DAEMON_ARGS =" - x "" to lldpd.conf, I get the following error. Can you help me?

2020-10-08T18:33:51.384866+00:00 plnx-aodv lldpd[2534]: no libcap support, running monitor as root
2020-10-08T18:33:51.385273+00:00 plnx-aodv lldpd[2536]: protocol LLDP enabled
2020-10-08T18:33:51.385451+00:00 plnx-aodv lldpd[2536]: protocol CDPv1 disabled
2020-10-08T18:33:51.385550+00:00 plnx-aodv lldpd[2536]: protocol CDPv2 disabled
2020-10-08T18:33:51.385644+00:00 plnx-aodv lldpd[2536]: protocol SONMP disabled
2020-10-08T18:33:51.385767+00:00 plnx-aodv lldpd[2536]: protocol EDP disabled
2020-10-08T18:33:51.385862+00:00 plnx-aodv lldpd[2536]: protocol FDP disabled
2020-10-08T18:33:51.386215+00:00 plnx-aodv lldpd[2536]: libevent 2.1.8-stable initialized with epoll method
2020-10-08T18:33:51.387556+00:00 plnx-aodv lldpcli[2535]: unknown command from argument 1: `DAEMON_ARGS=-x`
2020-10-08T18:33:51.387644+00:00 plnx-aodv lldpcli[2535]: an error occurred while executing last command
2020-10-08T18:33:51.411063+00:00 plnx-aodv lldpd[2534]: unable to get system name
2020-10-08T18:33:51.415649+00:00 plnx-aodv lldpd[2534]: unable to get system name
2020-10-08T18:33:51.416807+00:00 plnx-aodv lldpcli[2535]: system name set to new value ETAVSAN
2020-10-08T18:33:51.417360+00:00 plnx-aodv lldpcli[2535]: management pattaren set to new value 192.168.88.44
2020-10-08T18:33:51.417506+00:00 plnx-aodv lldpcli[2535]: unknown command from argument 1: `DAEMON_ARGS=-x`
2020-10-08T18:33:51.417634+00:00 plnx-aodv lldpcli[2535]: an error occurred while executing last command
2020-10-08T18:33:51.417943+00:00 plnx-aodv lldpcli[2535]: lldpd should resume operations
