### ISSUE TITLE
Changing the logging level

### ISSUE THREAD

**Issue by nandujayakumar** [vincentbernat/lldpd#374]
# Bug description
Info level logging is spamming my log

Fri Dec  6 04:36:47 2019 daemon.info lldpd[3431]: protocol LLDP enabled
Fri Dec  6 04:36:47 2019 daemon.info lldpd[3431]: libevent 2.0.22-stable initialized with epoll method
Fri Dec  6 04:36:53 2019 daemon.info lldpd[3390]: unable to get system name
Fri Dec  6 04:36:58 2019 daemon.info lldpd[3390]: unable to get system name
Fri Dec  6 04:37:03 2019 daemon.info lldpd[3390]: unable to get system name
Fri Dec  6 04:37:08 2019 daemon.info lldpd[3390]: unable to get system name
Fri Dec  6 04:37:13 2019 daemon.info lldpd[3390]: unable to get system name
Fri Dec  6 04:37:13 2019 daemon.info lldpcli[3430]: lldpd should resume operations
Fri Dec  6 04:37:18 2019 daemon.info lldpd[3390]: unable to get system name
Fri Dec  6 04:37:23 2019 daemon.info lldpd[3390]: unable to get system name
Fri Dec  6 04:37:23 2019 daemon.warn lldpd[3390]: unable to unlink /var/run/lldpd.socket: No such file or directory
Fri Dec  6 04:37:24 2019 daemon.info procd: Instance lldpd::instance1 pid 3390 not stopped on SIGTERM, sending SIGKILL instead
Fri Dec  6 04:37:24 2019 daemon.info lldpd[5025]: protocol LLDP enabled
Fri Dec  6 04:37:24 2019 daemon.info lldpd[5025]: libevent 2.0.22-stable initialized with epoll method
Fri Dec  6 04:37:29 2019 daemon.info lldpd[5023]: unable to get system name
Fri Dec  6 04:37:34 2019 daemon.info lldpd[5023]: unable to get system name
Fri Dec  6 04:37:34 2019 daemon.warn lldpcli[5024]: unable to get configuration from lldpd. End of file reached
Fri Dec  6 04:37:34 2019 daemon.warn lldpd[5023]: unable to unlink /var/run/lldpd.socket: No such file or directory
Fri Dec  6 04:37:34 2019 daemon.warn lldpcli[5024]: unable to get configuration from lldpd. End of file reached
Fri Dec  6 04:37:35 2019 daemon.info procd: Instance lldpd::instance1 pid 5023 not stopped on SIGTERM, sending SIGKILL instead
Fri Dec  6 04:37:35 2019 daemon.info lldpd[5383]: protocol LLDP enabled
Fri Dec  6 04:37:35 2019 daemon.info lldpd[5383]: libevent 2.0.22-stable initialized with epoll method
**Fri Dec  6 04:37:40 2019 daemon.info lldpd[5381]: unable to get system name
Fri Dec  6 04:37:45 2019 daemon.info lldpd[5381]: unable to get system name
Fri Dec  6 04:37:50 2019 daemon.info lldpd[5381]: unable to get system name
Fri Dec  6 04:37:55 2019 daemon.info lldpd[5381]: unable to get system name**
Fri Dec  6 04:37:55 2019 daemon.info lldpcli[5382]: lldpd should resume operations

Is there a way i can disable the info level logging ????

**Comment by vincentbernat** [comment]
You can run with `-dd` and it will stop logging at info level. Alternatively, you can fix the problem by ensuring `getent hosts $(uname -n)` work on your system.

**Comment by nandujayakumar** [comment]
Do we really have to restart the LLDP demon after modifying the /sys/class/net/*/bridge/group_fwd_mask to allow the LLDP pdu frames to pass through the bridge or will it pickup without the restart ??

**Comment by vincentbernat** [comment]
Not much I can do here.
