### ISSUE TITLE
lldpd issue  for arm64

### ISSUE THREAD

**Issue by gaoxu-college** [vincentbernat/lldpd#381]
Hi Mr vincentbernat，
    we want to use lldpad in ARM64，but we find you have a commit : "remove ARM64 for unreliable.” 
Can you send me the details of the unreliable in ARM64?
what is the issue if the lldpd run in  the ARM64?  

Thanks.

**Comment by vincentbernat** [comment]
It was just removed from Travis testing. https://travis-ci.org/github/vincentbernat/lldpd/jobs/644822681. I remember the network setup was quite peculiar. For some reasons, I was getting extra interfaces in all namespaces, this made all tests fail. lldpd shouldn't have any issue on ARM64.

**Comment by Mike-rdl** [comment]
Could you please explain what would be the right procedure to add lldp project to an ARM64  build.

**Comment by Mike-rdl** [comment]
> Hi Mr vincentbernat，
> we want to use lldpad in ARM64，but we find you have a commit : "remove ARM64 for unreliable.”
> Can you send me the details of the unreliable in ARM64?
> what is the issue if the lldpd run in the ARM64?
> 
> Thanks.

Hi there,
Could you please share your experience on building lldp for ARM64 ?

**Comment by vincentbernat** [comment]
It's `./configure && make && make install`.

**Comment by Mike-rdl** [comment]
Thank you for your quick response,  My question is how to build using the host machine with Ubuntu x86  for ARM64. I want to add it together with my other projects to the image and deploy the image on the ARM machine.

**Comment by vincentbernat** [comment]
It's like any other autotools project. If you have a crosscompiler, `./configure --host=aarch64-linux-gnu`.

**Comment by Mike-rdl** [comment]
It looks like my problem is one extra arg g++    ./configure --host=aarch64-linux-gnu-g++

**Comment by gaoxu-college** [comment]
Thank you for your answer.
