### ISSUE TITLE
The current version has support of all the features of 802.1AB-2016.

### ISSUE THREAD

**Issue by topuri** [vincentbernat/lldpd#383]
The current version has support of all the features of 802.1AB-2016.
if not please let me know which version of 802.1AB have support. 
Readme file refers to 802.1AB-2005.   So can we assume it has support of only 802.1AB-2005 not 802.1AB-2016.

**Comment by vincentbernat** [comment]
I don't have time to check that myself and I am not familiar with more recent standards. So, I prefer to stick to 2005.

**Comment by topuri** [comment]
Thanks.
