### ISSUE TITLE
Same mgmt ip sent on all interfaces

### ISSUE THREAD

**Issue by AlbertVeli** [vincentbernat/lldpd#387]
## Description
If I have three devices and the device in the middle is connected to both through eth1 and eth2, with two different ip-addresses for eth1 and eth2, the same management ip address is filled in sent packets to both sides.

It would make more sense to fill in ip address for eth1 on the lldp packet sent on that interface and the ip address for eth2 on the lldp packet sent on that interface.

## Steps to reproduce
Set different ip addresses on eth1 and eth2. Start lldpd (no management pattern set). Check outgoing lldp packets. All packets have the same management ip address filled in, regardless of which interface it is going out on.

**Comment by vincentbernat** [comment]
LLDP mandates to have one management address per family for the whole device. They are attached to the chassis, not the interface. The expectation would be the canonical address you use for SSH and SNMP.
