### ISSUE TITLE
Is it a possible to use libev to monitor "Monitor neighbors change" or "VLAN id change" via liblldpctl.so?

### ISSUE THREAD

**Issue by qqzhong** [vincentbernat/lldpd#390]
My question:
Is it a possible to use libev to monitor "Monitor neighbors change" or "VLAN id change" via liblldpctl.so?

I compiled lldpd, and get liblldpctl.so.
I can use API "lldpctl_atom_get_XXX(lldpctl_atom_t *atom, lldpctl_key_t key)" to get VLAN ID via liblldpctl.so.
It's polling method and I want to improve it, want to use ev_io_init(&io_w,io_w_action,fd,EV_READ) method in libev-4.24.

if LLDPD got VLAN from switch, then I can read it from the fd socket after received EV_READ event in libev.
Thank you very much!
Look forward to you reply!
BR,
Church

**Comment by vincentbernat** [comment]
Yes, have a look at `lldpctl_watch()` function and it use inside `lldpctl`.

**Comment by qqzhong** [comment]
Hi, Vincent,

I'm sorry to interrupt you again.
I made a VLAN-manager, but use polling to get Voice VLAN ID from lldpd daemon via liblldpctl.so.
Is it a possible that my VLAN-manager can be notified when lldpd daemon discovery VLAN by LLDP/CDP protocols from Cisco switch at once?
I just my polling is not better.
I want to make my VLAN-manager is a observer, and the lldpd is a notifier.
My VLAN-manager can receive new Voice VLAN id, if someone change the Voice VLAN on remote Cisco switch.
Thank you very much!

BR,
Church

**Comment by vincentbernat** [comment]
I have already answered. Use either `lldpcli watch` (from the command line) or `lldpctl_watch()` if you use the API.

**Comment by qqzhong** [comment]
I see.  closed. Thank you!
