### ISSUE TITLE
unable to get lldp over point to point (pppd) interface.

### ISSUE THREAD

**Issue by devOramaMan** [vincentbernat/lldpd#395]
Hi,

Thanks for creating this version of lldp. 

I had issues using lldp over pppd and  after growing a deeper understanding  of the lldp source i see it require some adjustments. 

 1. If your system does not use standard Linux interface, you can
    support additional interfaces by implementing the appropriate
    `struct lldpd_ops`. You can look at
    `src/daemon/interfaces-linux.c` for examples. Also, have a look at
    `interfaces_update()` which is responsible for discovering and
    registering interfaces.

**Comment by vincentbernat** [comment]
LLDP packets are transmitted over Ethernet, so this doesn't work over PPP. Maybe there is a way to transmit them over PPP, but then we need to find some documentation for this.

**Comment by devOramaMan** [comment]
Yes, I belive you are correct that there are ways to transmit the LLDP over an PPP interface. However, doing it proper is maby to be defined. Similar to dhcp client, dhcp fwd and other std, lldp require the HW MAC of the interface to be defined. In our case we can identify the board with the HW MAC of eth0 or eth1.

**Comment by vincentbernat** [comment]
LLDP is using multicast ethernet frames with type 0x88CC. It seems PPP doesn't support encapsulation of Ethernet frames, nor LLDP frames. Which equipment supports LLDP over a PPP link? Can you get a capture of the frames to check what it looks like?

**Comment by vincentbernat** [comment]
Not much to do. LLDP is tied to 802.3.
