### ISSUE TITLE
packet source mac address is invalid.

### ISSUE THREAD

**Issue by odking** [vincentbernat/lldpd#396]
### Description
I install the lldpd package  "lldpd 1.0.5-16-gb877664"  with 'zypper install lldpd" on suse and start the lldpd service with custom configuration /etc/lldpd.conf  as below:

        configure system chassisid H5CRS22
        configure system hostname compute4
        configure lldp tx-interval 30
        configure lldp tx-hold 4
        configure lldp portidsubtype macaddress
       
        configure system interface pattern control0,storage0
        configure system interface permanent control0,storage0
        configure ports control0 lldp status tx-only
        configure ports storage0 lldp status tx-only_

 It hopes that lldpd can sends lldp packets on control0 and storag0 interfaces.  The function on 'storage0' interface works fine, but abnormally on 'control0' interface.   The 'source mac address is not the real one that works on 'control0' interface and not same as portid subtype mac address.

### Outcome

1. ip link 

        ip -d link show control0
        2: **control0**: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond_lcm_ctrl state UP mode DEFAULT group default qlen 1000
            link/ether ec:f4:bb:c3:2b:ac brd ff:ff:ff:ff:ff:ff promiscuity 2 minmtu 68 maxmtu 9216
            bond_slave state ACTIVE mii_status UP link_failure_count 0 **perm_hwaddr ec:f4:bb:c3:2b:ac** queue_id 0 addrgenmode eui64 numtxqueues 8 numrxqueues 8 gso_max_size 65536 gso_max_segs 65535_

2. tcpdump

      _sudo tcpdump -pni control0 -e -vvv -X ether proto 0x88cc
      tcpdump: listening on control0, link-type EN10MB (Ethernet), capture size 262144 bytes
08:34:33.164987 **ee:f4:bb:c3:2b:ac** > 01:80:c2:00:00:0e, ethertype LLDP (0x88cc), length 346: LLDP, length 332
        Chassis ID TLV (1), length 8
          Subtype Local (7): H5CRS22
          0x0000:  0748 3543 5253 3232
        Port ID TLV (2), length 7
          Subtype MAC address (3): **ec:f4:bb:c3:2b:ac**
          0x0000:  03ec f4bb c32b ac
        Time to Live TLV (3), length 2: TTL 20s
          0x0000:  0014
        System Name TLV (5), length 8: compute4
          0x0000:  636f 6d70 7574 6534
        System Description TLV (6), length 112
          SUSE Linux Enterprise Server 15 SP2 Linux 5.3.18-14-default #1 SMP Wed Apr 15 11:58:40 UTC 2020 (6fe700b) x86_64
          0x0000:  5355 5345 204c 696e 7578 2045 6e74 6572
          0x0010:  7072 6973 6520 5365 7276 6572 2031 3520
          0x0020:  5350 3220 4c69 6e75 7820 352e 332e 3138
          0x0030:  2d31 342d 6465 6661 756c 7420 2331 2053
          0x0040:  4d50 2057 6564 2041 7072 2031 3520 3131
          0x0050:  3a35 383a 3430 2055 5443 2032 3032 3020
          0x0060:  2836 6665 3730 3062 2920 7838 365f 3634
        System Capabilities TLV (7), length 4
          System  Capabilities [Bridge, WLAN AP, Router, Station Only] (0x009c)
          Enabled Capabilities [Bridge, Router] (0x0014)
          0x0000:  009c 0014
          .....
           End TLV (0), length 0
        0x0000:  0208 0748 3543 5253 3232 0407 03ec f4bb  ...H5CRS22......
        0x0010:  c32b ac06 0200 140a 0863 6f6d 7075 7465  .+.......compute
        0x0020:  340c 7053 5553 4520 4c69 6e75 7820 456e  4.pSUSE.Linux.En
        0x0030:  7465 7270 7269 7365 2053 6572 7665 7220  terprise.Server.
        0x0040:  3135 2053 5032 204c 696e 7578 2035 2e33  15.SP2.Linux.5.3
        0x0050:  2e31 382d 3134 2d64 6566 6175 6c74 2023  .18-14-default.#
        0x0060:  3120 534d 5020 5765 6420 4170 7220 3135  1.SMP.Wed.Apr.15
        0x0070:  2031 313a 3538 3a34 3020 5554 4320 3230  .11:58:40.UTC.20
        0x0080:  3230 2028 3666 6537 3030 6229 2078 3836  20.(6fe700b).x86
        0x0090:  5f36 340e 0400 9c00 1410 0c05 01c0 a860  _64............`
        0x00a0:  1702 0000 000c 0010 1811 02fe 8000 0000  ................
        0x00b0:  0000 00a2 369f fffe 4553 de02 0000 0007  ....6...ES......
        0x00c0:  0008 0863 6f6e 7472 6f6c 30fe 0c00 80c2  ...control0.....
        0x00d0:  0300 0205 766c 616e 32fe 0900 120f 0303  ....vlan2.......
        0x00e0:  0000 000d fe09 0012 0f01 03ec 8100 1efe  ................
        0x00f0:  0700 12bb 0100 3f01 fe09 0012 bb06 322e  ......?.......2.
        0x0100:  382e 30fe 1500 12bb 0735 2e33 2e31 382d  8.0......5.3.18-
        0x0110:  3134 2d64 6566 6175 6c74 fe0b 0012 bb08  14-default......
        0x0120:  4835 4352 5332 32fe 0d00 12bb 0944 656c  H5CRS22......Del
        0x0130:  6c20 496e 632e fe12 0012 bb0a 506f 7765  l.Inc.......Powe
        0x0140:  7245 6467 6520 5236 3230 0000            rEdge.R620..__

3. SW Version 

Linux Kernel version:

        _compute4:~> uname -sro
        Linux 5.3.18-14-default GNU/Linux_

Suse System version:

        _NAME="SLES"
        VERSION="15-SP2"
        VERSION_ID="15.2"
        PRETTY_NAME="SUSE Linux Enterprise Server 15 SP2"_

 LLDP version:

    _Version: lldpd 1.0.5-16-gb877664_

**Comment by vincentbernat** [comment]
This is a feature due to the use of bonding. This is because a bond will use of one of the permanent addresses to emit packets. When in active/slave mode, if you the real MAC address was used when sending LLDP frames on the inactive port and the MAC address is used for the bond itself, the switch at the other side would believe the inactive port is active and move the MAC address of the bond from the active port to the inactive port.

If you are sure of what you do, you can use the real MAC address with:

```
configure system bond-slave-src-mac-type value real
```

But it shouldn't matter much which MAC address is used as a source.

**Comment by odking** [comment]
Thanks for your reply. i am not sure if a wrong MAC address , not same as the portid mac address,  would result into peer discard such lldp packet, since i use the portid subtype "macaddress".

the thing is the source mac address is neither bond interface mac nor real permanent address.
the link info of 'control' is :

ip -d link show control0
 2: **control0**: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond_lcm_ctrl state UP mode DEFAULT group default qlen 1000
     link/ether ec:f4:bb:c3:2b:ac brd ff:ff:ff:ff:ff:ff promiscuity 2 minmtu 68 maxmtu 9216
     bond_slave state ACTIVE mii_status UP link_failure_count 0 **perm_hwaddr ec:f4:bb:c3:2b:ac** queue_id 0 addrgenmode e

we can see the bond address is same as permanent address "**ec**:f4:bb:c3:2b:ac". 
But the outgoing lldp packet uses source MAC address "**ee**:f4:bb:c3:2b:ac", which sits nowhere. 
No idea why the first byte is changed from "ec" to "ee".

the issue only appears on 'control0' interface,

**Comment by vincentbernat** [comment]
As explained, lldpd cannot use the permanent MAC address nor the MAC address of the bond, so it builds another MAC address from the permanent MAC address. Otherwise, the remote equipment may learn the source MAC address while the local port should be inactive and it will steer traffic to this port and the traffic will be discarded.

I have never got report this was a problem to use a non existent MAC address.

**Comment by odking** [comment]
that makes big sense. Thanks very much.  Another quesiton is if  a switch using 'port security' policy may discard this packet ?

**Comment by vincentbernat** [comment]
I don't know, but I didn't get a report complaining about that (and this behaviour is quite old).
