### ISSUE TITLE
support to exclude tlv

### ISSUE THREAD

**Issue by manthan-lunagariya** [vincentbernat/lldpd#397]
Hi Vincent, 
Do we have any support like to select tlv which we can exclude from the lldp frame which we are sending?

**Comment by vincentbernat** [comment]
No, currently this is not implemented.

**Comment by manthan-lunagariya** [comment]
Have Any plan to have this feature in future?

**Comment by vincentbernat** [comment]
Nothing in the short term.

**Comment by manthan-lunagariya** [comment]
Ok Thank You.
