### ISSUE TITLE
repeated logging (...not have a name or an address, skip) for an excluded interface

### ISSUE THREAD

**Issue by Pack3tL0ss** [vincentbernat/lldpd#398]
# Bug description

Log file being spammed with messages for an interface I've tried to exclude
```
lldpd[13101]: interface 3 does not have a name or an address, skip
```

## Steps to reproduce the problem

**Contents of /etc/default/lldpd**
```
DAEMON_ARGS="-I eth* -C eth* -m eth*"
```

**Contents of config in /etc/lldpd.d**
```
configure system description ConsolePi
configure system interface pattern eth*
```

interface 3 is wlan0 so it should be excluded if I understand the options specified above correctly

## Expected outcome

Initially DAEMON_ARGS were not set, and I was relying on `configure system interface pattern eth*` being sent to lldpcli during startup.  I added DAEMON_ARGS to see if it would squelch the logs for the interface that should be excluded anyway.  Given the interface is excluded, my expectation is not to see logs for that interface.

## Current outcome

Lot's of logs for an interface that should be excluded:

```
interface 3 does not have a name or an address, skip
```

# Additional information

 - Output of `lldpd -vv`:
 
```
lldpd 1.0.3
  Built on 2018-12-10T15:16:57Z

Additional LLDP features:    LLDP-MED, Dot1, Dot3, Custom TLV
Additional protocols:        CDP, FDP, EDP, SONMP
SNMP support:                yes
Old kernel support:          no (Linux 2.6.39+)
Privilege separation:        enabled
Privilege separation user:   _lldpd
Privilege separation group:  _lldpd
Privilege separation chroot: /var/run/lldpd
Configuration directory:     /etc

C compiler command: gcc  -fdiagnostics-show-option -fdiagnostics-color=auto -pipe -Wall -W -Wextra -Wformat -Wformat-security -Wfatal-errors -Wcast-align -Winline -Wpointer-arith -fno-omit-frame-pointer -Wno-unused-parameter -Wno-missing-field-initializers -Wno-sign-compare -fstack-protector -fstack-protector-all -fstack-protector-strong -fPIE -isystem /usr/include/bsd -DLIBBSD_OVERLAY  -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -g -O2 -fdebug-prefix-map=/build/lldpd-yxFLOk/lldpd-1.0.3=. -fstack-protector-strong -Wformat -Werror=format-security -isystem /usr/include/bsd -DLIBBSD_OVERLAY -Wdate-time -D_FORTIFY_SOURCE=2
Linker command:     /usr/bin/ld  -Wl,-z,relro -Wl,-z,now -lbsd  -fPIE -pie -Wl,-z,relro  -lbsd
```

 - Output of `uname -sro`:
 
```
Linux 4.19.118-v7+ GNU/Linux
```

 - OS Release Details:
 
```
Raspbian GNU/Linux 10 (buster)
debian_version: 10.4
```

## Also...
The man page / documentation has a contradiction in the instructions vs. the examples, and I assumed the examples are correct.

You can view the contradiction/error with `man lldpd | grep suffixing -A 5` (same contradiction in lldpcli, appears in a few places) 

```
an interface by *suffixing* it with an exclamation mark ...  eth*,!eth1,!eth2 ... *,!eth*,!!eth1"
The word *suffixing* should be *prefixing* based on the examples.
```

**Comment by vincentbernat** [comment]
Could you provide the output of `ip -d l l`? If interface 3 is `wlan0`, it has a name and I suppose an (L2) address.

**Comment by Pack3tL0ss** [comment]
Thanks for taking a look (and fixing the doc)

This is what it looks like now.... but the it doesn't log in this state

'''
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00 promiscuity 0 minmtu 0 maxmtu 0 addrgenmode eui64 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535 
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether b8:27:eb:fe:bf:b8 brd ff:ff:ff:ff:ff:ff promiscuity 0 minmtu 68 maxmtu 9000 addrgenmode none numtxqueues 1 numrxqueues 1 gso_max_size 8824 gso_max_segs 65535 
3: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DORMANT group default qlen 1000
    link/ether b8:27:eb:ab:ea:ed brd ff:ff:ff:ff:ff:ff promiscuity 0 minmtu 68 maxmtu 1500 addrgenmode none numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535
'''

I was doing some work on the AAA server that authenticates WLAN clients, at that point it was coming in all the time (Auth would fail to complete, IP would be flushed).  WLAN was associating, but never able to authenticate.  Under normal circumstances it won't come in as often, but ideally I'd prefer to not get a log at all given the interface is excluded from lldpd.

It would make diagnosing the real issue more cumbersome if wlan was flapping.

I can try to pull `ip -d l l` with AAA down if you need to see it in that state, but I expect AAA TimedOut, so it flushed the IP.

**Comment by vincentbernat** [comment]
OK, I am demoting the verbosity of this message. I was leaving it here because it seemed like something that would never happen.
