### ISSUE TITLE
Unable to get test code binary

### ISSUE THREAD

**Issue by kinjal491** [vincentbernat/lldpd#399]
Hi Vincent, 

I'm using lldp V1.0.5 and try to compile test code. However I'm not able to get binary. 
Could you provide steps to generate test code binary? Do we need to install driver while running test code?

**Comment by manthan-lunagariya** [comment]
Hi Vincent, 

I also get problem while installing tests... LOGS are given below.

root@localhost:~/tests# automake 
automake: error: 'configure.ac' is required
root@localhost:~/tests# make 
cd .. && make  am--refresh
make[1]: Entering directory '/home/root'
make[1]: *** No rule to make target 'am--refresh'.  Stop.
make[1]: Leaving directory '/home/root'
make: *** [Makefile:763: ../configure] Error 2

**Comment by vincentbernat** [comment]
Do not run `automake` inside the `tests/` directory. Just compile `lldpd` as usual and use `make check`.

**Comment by manthan-lunagariya** [comment]
so here, we dont have any executable for test by which I can cross compile and run test on board??

**Comment by manthan-lunagariya** [comment]
and also didnt get any count on test, while do "make check" in tests folder on my system which had running lldpd daemon.

Here is the logs

make  
make[1]: Entering directory '/home/manthan/lldpd/tests'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/manthan/lldpd/tests'
make  check-TESTS
make[1]: Entering directory '/home/manthan/lldpd/tests'
make[2]: Entering directory '/home/manthan/lldpd/tests'
============================================================================
Testsuite summary for lldpd 1.0.5-31-gd21599d
============================================================================
# TOTAL: 0
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
make[2]: Leaving directory '/home/manthan/lldpd/tests'
make[1]: Leaving directory '/home/manthan/lldpd/tests'

**Comment by vincentbernat** [comment]
`make check` will create executables `check_something`. You can run them manually on the target. They don't need `lldpd` running.

**Comment by manthan-lunagariya** [comment]
make check is working, but i didnot find any "check_something" executables, is there any seperate configuration for it?

**Comment by vincentbernat** [comment]
You need to have libcheck installed. Check in the output of `./configure` what's the result for `CHECK` is.

**Comment by manthan-lunagariya** [comment]
Yes, got the binaries and its working.....

**Comment by kinjal491** [comment]
Thanks Vincent!!
