### ISSUE TITLE
issue to fill output buffer in lldpctl_conn_t

### ISSUE THREAD

**Issue by manthan-lunagariya** [vincentbernat/lldpd#400]
Hi Vincent, 
I want to send lldp frame directly from lldpctl_send() function, so i made an application which code is given below, but facing issue while compiling....

 lldpctl_conn_t *m_lldpConnection;
    const char *m_ctlname;
 
    m_ctlname = lldpctl_get_default_transport();

    /* Make a connection */
    m_lldpConnection = lldpctl_new_name(m_ctlname, NULL, NULL, NULL);

    m_lldpConnection->output_buffer=pkt1; //pkt1 is a raw lldp frame
    m_lldpConnection->output_buffer_len=sizeof(pkt1);
    
    lldpctl_send(m_lldpConnection);

    lldpctl_release(m_lldpConnection);

and getting error like below:

**_error: dereferencing pointer to incomplete type ‘lldpctl_conn_t {aka struct lldpctl_conn_t}’
     m_lldpConnection->output_buffer=pkt1;_**

Please help.

**Comment by vincentbernat** [comment]
`lldpctl_send()` is to talk to the lldpd daemon, not to send raw packets. There is no way to specify a packet to be sent by lldpd. Just send it directly using a raw socket. lldpd does not need to be put in the loop for that.

**Comment by manthan-lunagariya** [comment]
OK... Thank You..
