### ISSUE TITLE
Apt repo GPG key has expired

### ISSUE THREAD

**Issue by amuckart** [vincentbernat/lldpd#402]
apt update is reporting that the GPG key used to sign the packages on http://download.opensuse.org/repositories/home:/vbernat has expired, which is preventing installation.

Output of apt-key list:
```
pub   rsa2048 2018-04-17 [SC] [expired: 2020-06-25]
      EF79 5E4D 26E4 8F1D 7661  267B 431C 37A9 7C3E 114B
uid           [ expired] home:vbernat OBS Project <home:vbernat@build.opensuse.org>
```

**Comment by vincentbernat** [comment]
Thanks for the notice. I don't remember this issue happened in the past, but it seems quite common. For reference, I did extend the validity of the key with:

```console
$ osc signkey --extend home:vbernat
```

Then, I have triggered a rebuild by doing a meaningless change in `lldpd.dsc`.
