### ISSUE TITLE
send LLDP frames inside VLAN

### ISSUE THREAD

**Issue by awujek** [vincentbernat/lldpd#403]
Hi all, 

I would like to ask if it is possible to send LLDP frames tagged with VLAN. I managed to achieve the expected behaviour by creating a VLAN interface in linux by:
`ip link add link eth0 name eth0.14 type vlan id 14`
then running lldpd:
`lldpd -I eth0.14`

However, I prefer not to create interface for VLAN. I expect that lldpd adds a VLAN tag directly at the send of a frame.
I would like to see an option like:
`configure ports eth0 lldp vlan 14 prio 1`

I have understood that the configuration of med does not cause the tagging of lldp frames. Is that correct?
I see that lldpd processes lldp frames no matter if they have VLAN tag or not.

**Comment by vincentbernat** [comment]
Processing LLDP frames inside VLAN is done to workaround historical bugs where some equipments (old Cisco Catalyst) were encapsulating LLDP frames into the native VLAN.

Technically, your request is possible and not too difficult if you only specify one VLAN per port. I don't have myself much time to implement that.

**Comment by awujek** [comment]
Implemented
