### ISSUE TITLE
Discovery through multiple switches or multi-hop discovery 

### ISSUE THREAD

**Issue by Sameer-Chouksey** [vincentbernat/lldpd#406]
Hello, 

It's a question rather than an issue. 

Does the LLDP support multi-hop discovery? I mean if I run discovery on switch1 which is connected to switch2. And there is one end device (ED1) is connected to switch2. Can I discover ED1 from switch1?

If yes can some please help me with the configuration or steps to do this?

Thanks,
Sameer

**Comment by vincentbernat** [comment]
Look at `configure lldp agent-type`. But the generic answer is "no". Regular switches are not expected to forward LLDP frames.

**Comment by tzeng015** [comment]
Can I ask a question ?  I find the latest version "lldpd-1.0.5.tar.gz ". Can you tell me the change list of this latest version ?

**Comment by vincentbernat** [comment]
Change are here: https://github.com/vincentbernat/lldpd/blob/master/NEWS
