### ISSUE TITLE
Key used to sign packages on download.opensuse.org has expired

### ISSUE THREAD

**Issue by amuckart** [vincentbernat/lldpd#407]
The key used to sign the package on download.opensuse.org has expired, leaving apt unable to update the package repo and resulting in an error every time apt update is run. 

Get:9 http://download.opensuse.org/repositories/home:/vbernat/xUbuntu_18.04  InRelease [1,525 B]
Err:9 http://download.opensuse.org/repositories/home:/vbernat/xUbuntu_18.04  InRelease
  The following signatures were invalid: EXPKEYSIG 431C37A97C3E114B home:vbernat OBS Project <home:vbernat@build.opensuse.org>
Fetched 1,525 B in 2s (894 B/s)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
117 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://download.opensuse.org/repositories/home:/vbernat/xUbuntu_18.04  InRelease: The following signatures were invalid: EXPKEYSIG 431C37A97C3E114B home:vbernat OBS Project <home:vbernat@build.opensuse.org>
W: Failed to fetch http://download.opensuse.org/repositories/home:/vbernat/xUbuntu_18.04/InRelease  The following signatures were invalid: EXPKEYSIG 431C37A97C3E114B home:vbernat OBS Project <home:vbernat@build.opensuse.org>
W: Some index files failed to download. They have been ignored, or old ones used instead

**Comment by vincentbernat** [comment]
It should have been fixed. Can you execute again the instructions to update the fetch the key?

**Comment by amuckart** [comment]
Works now, thank you.
