### ISSUE TITLE
Lenght limit of chassis description

### ISSUE THREAD

**Issue by awujek** [vincentbernat/lldpd#408]
Hi Vincent,

Is there a length limit of a chassis description?
The version 1.0.5 introduces the limit of a system description to 79 characters.
(To be precise the commit "9c49cedf lib: fix memory leak when handling I/O" which suppose to fix #362 is causing the problem)
After the problematic configuration change is triggered, other configuration changes are failing.

An example of triggering the error:
```
[lldpcli] # configure system description  '12345678901234567890123456789012345678901234567890123456789012345678901234567890'
2020-07-14T01:02:53 [WARN/lldpctl] unable to set description. Other input/output operation already in progress

```
And no other actions from the same instance of a client are possible:
```
[lldpcli] # show neighbors 
-------------------------------------------------------------------------------
LLDP neighbors:
2020-07-14T01:04:43 [WARN/lldpctl] not able to get the list of interfaces. Other input/output operation already in progress
-------------------------------------------------------------------------------

```
After the restart of a lldpcli, the next command is executed successfully.

The same problem applies to other configuration items like platform description
```
[lldpcli] # configure system platform    '12345678901234567890123456789012345678901234567890123456789012345678901234567890'
2020-07-14T01:08:43 [WARN/lldpctl] unable to get configuration from lldpd. Other input/output operation already in progress


```

**Comment by vincentbernat** [comment]
Thanks. I have fixed this arbitrary limit as the goal is just to have a safeguard against some programming errors. The value was turned into a "canary" and the truncation of this canary was not handled correctly.
