### ISSUE TITLE
make[3]: *** No rule to make target '../../libevent/*.c', needed by '../../libevent/libevent.la'.  Stop.

### ISSUE THREAD

**Issue by deepcoder** [vincentbernat/lldpd#416]
Trying to compile on Ubuntu 20 and I am receiving the following failure during make step. Thanks for your help! and work on this project.

```
make[3]: Entering directory '/home/user/lldp-discovery/lldpd-master/src/daemon'
  CC       main.o
  CC       liblldpd_la-frame.lo
  CC       liblldpd_la-client.lo
  CC       liblldpd_la-priv.lo
  CC       liblldpd_la-privsep.lo
  CC       liblldpd_la-privsep_io.lo
  CC       liblldpd_la-privsep_fd.lo
  CC       liblldpd_la-interfaces.lo
make[3]: *** No rule to make target '../../libevent/*.c', needed by '../../libevent/libevent.la'.  Stop.
make[3]: Leaving directory '/home/user/lldp-discovery/lldpd-master/src/daemon'
make[2]: *** [Makefile:659: all] Error 2
make[2]: Leaving directory '/home/user/lldp-discovery/lldpd-master/src/daemon'
make[1]: *** [Makefile:619: all-recursive] Error 1
make[1]: Leaving directory '/home/user/lldp-discovery/lldpd-master'
make: *** [Makefile:508: all] Error 2

```

**Comment by vincentbernat** [comment]
If you are compiling from git, please use a proper checkout, then `./autogen.sh`. If you want to compile from tarball, use the ones released officially. I do not upload them to GitHub (maybe I should), they are on https://vincentbernat.github.io/lldpd (click on the upper left badge).

**Comment by deepcoder** [comment]
That was the problem, when I correctly cloned the repository all steps completed correctly. I should have found your website first, very well documented, thank you! -- Dave
