### ISSUE TITLE
Trying to find Mikrotik devices......

### ISSUE THREAD

**Issue by deepcoder** [vincentbernat/lldpd#417]
I went down the LLDP rabbit hole out of an interest hoping to find a way in python to discover my Mikrotik devices on my home network. Wanted to do this so I could query the Mikrotik API to monitor devices on my network. As is described in URL below, they seem to support CDP, LLDP as well as their own protocol MNDP. I can see my Mikrotik units advertising on the network by using Wireshark. Your tool, after I turned on CDP -cc and restarted daemon found several of my devices once. However after that, lldpcli, seems to only display one unit. This is not the nearest unit to the computer running lldp. lldp seems to shift back to only seeing LLDP if I read this correctly.

I am way above my pay grade here, but if I look in Wireshark and filter on LLDP protocol, Wireshark only shows one device and a different one then the one lldp shows on the device which is on the same Mikrotik switch as Wireshark (but different port), the Mikrotik switch to the Wireshark capture device port. However, if I filter on MNDP in Wireshark, I see all of my devices. If I filter on CDP, I see all the Mikrotik devices....

https://help.mikrotik.com/docs/display/ROS/Neighbor+discovery

This old c program running on same machine as lldp, finds all the Mikrotik devices consistently:
https://github.com/geocar/cdp-tools/blob/master/cdp-listen.c

```
user@ubuntu-macmini2014:~$ cat /etc/default/lldpd
# Uncomment to start SNMP subagent and enable CDP, SONMP and EDP protocol
#DAEMON_ARGS="-x -c -s -e"
DAEMON_ARGS="-cc -r"

[lldpcli] $ show neighbors
-------------------------------------------------------------------------------
LLDP neighbors:
-------------------------------------------------------------------------------
Interface:    enp3s0f0, via: CDPv1, RID: 1, Time: 0 day, 00:00:23
  Chassis:
    ChassisID:    local SB-HAPAC2-TWO
    SysName:      SB-HAPAC2-TWO
    SysDescr:     MikroTik running on
                  6.47.7 (stable)
    MgmtIP:       192.168.2.7
    Capability:   Router, on
  Port:
    PortID:       ifname bridge/wds4
    PortDescr:    bridge/wds4
    TTL:          120
-------------------------------------------------------------------------------
Interface:    enp3s0f0, via: CDPv1, RID: 2, Time: 0 day, 00:00:01
  Chassis:
    ChassisID:    local SB-CRS326-ONE
    SysName:      SB-CRS326-ONE
    SysDescr:     MikroTik running on
                  6.47.7 (stable)
    MgmtIP:       192.168.2.3
    Capability:   Router, on
  Port:
    PortID:       ifname bridge/ether1
    PortDescr:    bridge/ether1
    TTL:          120
-------------------------------------------------------------------------------


[lldpcli] $ show neighbors
-------------------------------------------------------------------------------
LLDP neighbors:
-------------------------------------------------------------------------------
Interface:    enp3s0f0, via: LLDP, RID: 4, Time: 0 day, 00:00:23
  Chassis:
    ChassisID:    mac 48:8f:5a:aa:e8:89
    SysName:      SB-RB4011-ONE
    SysDescr:     MikroTik RouterOS 6.47.7 (stable) RB4011iGS+5HacQ2HnD
    MgmtIP:       192.168.2.2
    Capability:   Bridge, on
    Capability:   Router, on
    Capability:   Wlan, on
  Port:
    PortID:       ifname bridge/ether2
    TTL:          120
-------------------------------------------------------------------------------

```

**Comment by vincentbernat** [comment]
LLDP is a link-local protocol. You should only see the device at the other side of the cable. The idea should be the same for CDP, but some devices are not restricting CDP to the local link. lldpd tries to be smart to detect which device is on the other side: if it sees two CDP devices and only one LLDP device, it hides the CDP devices as the device on the other side is likely to be the ones with LLDP (because it's unique). See FILTERING NEIGHBORS in lldpd manual page, you can change that.

**Comment by deepcoder** [comment]
Thank you for your explainer! I will explore some more.
