### ISSUE TITLE
Support of shutdown LLDPDU

### ISSUE THREAD

**Issue by vincentbernat** [vincentbernat/lldpd#5]
Currently, shutdown LLDPDU is flagged as invalid because there is no TTL TLV. It should be accepted and the corresponding entry should be removed.

**Comment by yunusemreayhan** [comment]
Do you support below condition in Lldp 2005 RFC :

10.2.1.2 Shutdown LLDPDU construction:

A special procedure exists for the case in which a LLDP agent knows an associated port is about to become
non-operational (for example, the adminStatus for the port is transitioning to ‘disabled’). In the event a port,
currently configured with LLDP frame transmission enabled, either becomes disabled for LLDP activity, or
the interface is administratively disabled, a final LLDP shutdown LLDPDU may be sent with:
1) The Chassis ID and Port ID TLVs.
2) The Time To Live TLV with the TTL field set to zero.
3) An End Of LLDPDU TLV.
The LLDPDU shall not include any optional TLVs and should be transmitted before the interface is
disabled.

**Comment by vincentbernat** [comment]
Yes, it is supported, but only when `lldpd` is stopping: Linux doesn't provide a way to send packets before an interface is put down.

**Comment by yunusemreayhan** [comment]
So you do not send a shutdown TLV in MSAP change scenario also, right?

**Comment by vincentbernat** [comment]
Oh, you are right, there is also one sent when the MSAP changes!

**Comment by yunusemreayhan** [comment]
Then I have 3 questions:
1-So in which case MSAP change happens, which command in lldpcli i mean?
2-In which scenarios lldpd stops?
3-For example when we deactivate lldp tx by template, should not lldpd send a shutdown TLV you think?

Thanks in advance..

**Comment by vincentbernat** [comment]
❦ 13 mai 2019 09:15 -07, Yunus Emre AYHAN <notifications@github.com>:

> 1-So in which case MSAP change happens, which command in lldpcli i
> mean?

"configure system chassisid"
"configure lldp portid subtype"

> 2-In which scenarios lldpd stops?

When requested by the user.

> 3-For example when we deactivate lldp tx by template, should not lldpd
> send a shutdown TLV you think?

We could, but this is not currently the case.
