### ISSUE TITLE
lldpd left socket unremoved when SIGHUP received

### ISSUE THREAD

**Issue by makoto-fujiwara** [vincentbernat/lldpd#67]
(1) Start as 'lldbd -d';  hit Control-C to kill; /var/run/lldpd.socket is left unremoved. The other run 'lldbd -d' will receive 

2014-06-13T10:54:25 [WARN/control] unable to connect to socket /var/run/lldpd.socket: Connection refused

removing socket file will resolve this problem.

Thanks a lot.  (0.7.9)  testing on NetBSD  using pkgsrc/wip/lldpd

**Comment by vincentbernat** [comment]
There was indeed some issues with how signals were handled. They were fixed in some recent commits. I think this should fix your issue. Feel free to reopen if not.
