### ISSUE TITLE
Porting to arm-linux 32-bit

### ISSUE THREAD

**Issue by bradomyn** [vincentbernat/lldpd#76]
Hi,

I'd like to port the code to an arm-linux embedded system, actually is an open source switch, [White Rabbit Project](http://www.ohwr.org/projects/white-rabbit/wiki/Switch). It could be interesting to port it to our platform.

I was able to cross-compile the code once that I have removed the flags:
-fstack-protector
-fstack-protector-strong

from the configure.ac.

The configuration is:
------------------ Summary ------------------
 lldpd version 0.7.10-46-gc66fd1a-dirty
  OS.............: Linux
  Prefix.........: /usr/local
  C Compiler.....: /opt/arm-linux/bin/arm-linux-gcc -std=gnu99 -g -O2 -fdiagnostics-show-option -pipe -Wall -W -Wextra -Wformat -Wformat-security -Wfatal-errors -Wcast-align -Winline -fno-omit-frame-pointer -D_FORTIFY_SOURCE=2 -Wno-unused-parameter -Wno-missing-field-initializers -Wno-sign-compare -D_GNU_SOURCE 
  Linker.........: /opt/arm-linux/arm-unknown-linux-uclibcgnueabi/bin/ld  -Wl,-z,relro -Wl,-z,now 
  Libevent.......: embedded
  Readline.......: no
 Optional features:
  SNMP support...: no
  CDP............: yes
  FDP............: yes
  EDP............: yes
  SONMP..........: yes
  LLDPMED........: yes
  DOT1...........: yes
  DOT3...........: yes
  XML output.....: no
  JSON output....: no
  Oldies support.: no
  seccomp........: no
  Privilege separation:
  Enabled........: yes
  User/group.....: root/root
  Chroot.........: root

When I run it:
 
`[WARN/control] unable to connect to socket /usr/local/var/run/lldpd.socket: Connection refused`
`[WARN/main] unable to execute /usr/local/sbin/lldpcli: No such file or directory`
`[WARN/main] configuration is incomplete, lldpd needs to be unpaused`
`Segmentation fault`

If I disable the "Privilege separation" in the configure.ac 

`[WARN/control] unable to connect to socket /usr/local/var/run/lldpd.socket: Connection refused`
`[WARN/priv] no privilege separation available`
`[WARN/main] configuration is incomplete, lldpd needs to be unpaused`

The first warning, no idea why.
About the second warning, probably is because I don't have group/user management in the embedded OS, it is a light custom linux kernel. 
How could I compile the lldpd without "privilege separation"? I mean, 

And the third one I think it is a consequence of the two first...

Any idea how I could successfully port the code? if the code needs a patch, I could do it myself, but I'd need a guideline about where/how to modify it. 

Cheers

**Comment by otavio** [comment]
We have added support for lldpd to Yocto Project and been using it in a ARM Cortex A9 processor.

This is likely a misconfiguration of your toolchain.

**Comment by vincentbernat** [comment]
Confirmed to work.
