### ISSUE TITLE
Unable to create control socket

### ISSUE THREAD

**Issue by akulkarn** [vincentbernat/lldpd#82]
Hello,

I am getting following error 

```
root@localhost:~# lldpd -v
0.7.11

root@localhost:~# lldpd -d -d -d
2014-11-13T21:02:01 [ DBG/main] lldpd starting...
2014-11-13T21:02:01 [ DBG/main] creating control socket
2014-11-13T21:02:01 [ DBG/control] create control socket /usr/local/var/run/lldpd.socket
2014-11-13T21:02:01 [WARN/main] unable to create control socket: No such file or directory
2014-11-13T21:02:01 [CRIT/fatal] giving up
root@localhost:~# lldpcli
[lldpcli] $ show neighbor
-------------------------------------------------------------------------------
LLDP neighbors:
2014-11-13T21:24:06 [WARN/control] unable to connect to socket /usr/local/var/run/lldpd.socket: No such file or directory
2014-11-13T21:24:06 [WARN/lldpctl] not able to get the list of interfaces. Unable to connect to lldpd daemon
-------------------------------------------------------------------------------
root@localhost:~# uname -a
Linux localhost 3.5.0-23-generic #35~precise1 SMP Tue Sep 9 11:06:09 EDT 2014 i686 athlon i386 GNU/Linux
```

I installed using the latest code on the website and also did  apt-get install lldpd

Any help you can provide would be highly appreciated.

**Comment by vincentbernat** [comment]
No update and unlikely to be a bug.

**Comment by pavanposa** [comment]
Hi
I am trying to install lldp on T1040rdb. After bitbaking I got some executables in /image/usr/sbin folder. If i run those executables on the switch I am also getting the same error. The board uses powerpc-fsl-linux-gcc compiler. Please get me resolve this error as soon as possible

**Comment by vincentbernat** [comment]
Does the directory where the control socket should be exists? If not, you have to create it.

**Comment by pavanposa** [comment]
I have created the directory but control socket is not getting created.

**Comment by vincentbernat** [comment]
What's the output of `lldpd -dddd`?

**Comment by pavanposa** [comment]
It shows no lldpd user for privilege separation.

**Comment by vincentbernat** [comment]
You have to create the `_lldpd` user and group.

**Comment by pavanposa** [comment]
I have created them but still problem exists. Can you describe detailed procedure on adding user, group and chrooting(commands).

**Comment by vincentbernat** [comment]
Please, copy/paste the error messages you get. I can't spend my time second-guessing what is happening.

**Comment by pavanposa** [comment]
root@t1040rdb:/0.9.2-r0/image/usr/sbin# ./lldpd 
root@t1040rdb:/0.9.2-r0/image/usr/sbin# ./lldpcli 
[lldpcli] $ show neighbors
-------------------------------------------------------------------------------
LLDP neighbors:
2015-10-13T11:50:39 [WARN/control] unable to connect to socket /var/run/lldpd.socket: No such file or directory
2015-10-13T11:50:39 [WARN/lldpctl] not able to get the list of interfaces. Unable to connect to lldpd daemon

**Comment by pavanposa** [comment]
root@t1040rdb:/0.9.2-r0/image/usr/sbin# lldpd -d -d -d -d
2015-10-13T11:53:06 [ DBG/main] lldpd 0.9.2 starting...
2015-10-13T11:53:06 [CRIT/main] no lldpd user for privilege separation

**Comment by vincentbernat** [comment]
The user to create is therefore `lldpd`. If you created it, what's the output of `getent passwd lldpd`?

**Comment by pavanposa** [comment]
getent is not there in yocto package. Is there any other way to resolve this.

**Comment by vincentbernat** [comment]
`id lldpd` maybe.

What libc are you using?

**Comment by pavanposa** [comment]
root@t1040rdb:/0.9.2-r0/image/usr/sbin# id _lldpd
uid=700(_lldpd) gid=1000(_lldpd) groups=1000(_lldpd)

**Comment by vincentbernat** [comment]
You seem to have configured lldpd to use `lldpd`, not `_lldpd` (the error message says `lldpd`, not `_lldpd`), through `./configure`. Either create `lldpd` user or don't provide `--with-privsep-user` to `./configure`.

**Comment by pavanposa** [comment]
I have not used ./configure. I just bitbaked the lldpd folder then I got the executables. If i try to run ./cofigure on the board it does not configure at all it shows following error

root@t1040rdb:/0.9.2-r0/lldpd-0.9.2# ./configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... no
checking whether make supports nested variables... no
checking whether UID '0' is supported by ustar format... yes
checking whether GID '0' is supported by ustar format... yes
checking how to create a ustar tar archive... plaintar
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether make supports nested variables... (cached) no
checking for style of include used by make... none
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/0.9.2-r0/lldpd-0.9.2':
configure: error: C compiler cannot create executables
See `config.log' for more details

**Comment by vincentbernat** [comment]
Create `lldpd` user instead.

**Comment by pavanposa** [comment]
It is working now. But when I enter show neighbors it not showing any neighbors. One end is connected to switch and other end to computer. LLDP is installed on both

[lldpcli] # show neighbors
-------------------------------------------------------------------------------
LLDP neighbors:
----------------------

show chassis is working fine

[lldpcli] # show chassis
-------------------------------------------------------------------------------
Local chassis:
-------------------------------------------------------------------------------
Chassis:     
  ChassisID:    mac 00:04:9f:03:43:a7
  SysName:      t1040rdb
  SysDescr:      Linux 3.12.19-rt30-QorIQ-SDK-V1.7+g6619b8b #1 SMP Wed Apr 20 17:21:25 IST 2016 ppc
  MgmtIP:       10.116.65.143
  MgmtIP:       fe80::204:9fff:fe03:43aa
  Capability:   Bridge, off
  Capability:   Router, off
  Capability:   Wlan, off
  Capability:   Station, on

**Comment by pavanposa** [comment]
Using wireshark on computer i can capture lldp frames that are coming that system only but not from switch.

**Comment by vincentbernat** [comment]
What's the output of "ip link ls"?

**Comment by pavanposa** [comment]
root@t1040rdb:/0.9.2-r0/image/usr/sbin# ip link ls
1: lo: <LOOPBACK> mtu 65536 qdisc noop state DOWN mode DEFAULT group default 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: fm1-gb0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:04:9f:03:42:c6 brd ff:ff:ff:ff:ff:ff
3: fm1-gb1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:04:9f:03:42:c7 brd ff:ff:ff:ff:ff:ff
4: fm1-gb2: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:04:9f:03:42:c8 brd ff:ff:ff:ff:ff:ff
5: fm1-gb3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 00:04:9f:03:42:c9 brd ff:ff:ff:ff:ff:ff
6: fm1-gb4: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 00:04:9f:03:42:ca brd ff:ff:ff:ff:ff:ff
7: tunl0: <NOARP> mtu 0 qdisc noop state DOWN mode DEFAULT group default 
    link/ipip 0.0.0.0 brd 0.0.0.0
8: sit0: <NOARP> mtu 1480 qdisc noop state DOWN mode DEFAULT group default 
    link/sit 0.0.0.0 brd 0.0.0.0

**Comment by pavanposa** [comment]
fm1-gb3 is UP

**Comment by vincentbernat** [comment]
If you tcpdump on fm1-gb3, do you see LLDP frames coming out? If not, run `lldpd -dddd -D interfaces` to see what could be wrong.

**Comment by elaron** [comment]
--- lldpd/sbin » ./lldpcli                                                         127 ↵
[lldpcli] $ show neibour
2017-02-24T15:04:21 [WARN/lldpctl] unknown command from argument 2: `neibour`

[lldpcli] $ show neighbors
-------------------------------------------------------------------------------
LLDP neighbors:
2017-02-24T15:04:26 [WARN/control] unable to connect to socket /usr/local/var/run/lldpd.socket: Permission denied
2017-02-24T15:04:26 [WARN/lldpctl] not able to get the list of interfaces. Unable to connect to lldpd daemon
-------------------------------------------------------------------------------
[lldpcli] $ quit
2017-02-24T15:05:17 [WARN/lldpctl] unknown command from argument 1: `quit`

[lldpcli] $ exit

--- lldpd/sbin » ps -ef|grep lldp
    0 24877     1   0  1:48下午 ??         0:00.02 /usr/local/opt/lldpd/sbin/lldpd
  206 24884 24877   0  1:48下午 ??         0:00.07 /usr/local/opt/lldpd/sbin/lldpd
  501 29384  1399   0  3:05下午 ttys001    0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn lldp
--- lldpd/sbin » id lldp
id: lldp: no such user
--- lldpd/sbin » id lldpd                                                            1 ↵
uid=207(lldpd) gid=207(_detachedsig) groups=207(_detachedsig),12(everyone),61(localaccounts),100(_lpoperator),701(com.apple.sharepoint.group.1)
--- lldpd/sbin » id _lldpd
uid=206(_lldpd) gid=206(_lldpd) groups=206(_lldpd),12(everyone),61(localaccounts),100(_lpoperator),701(com.apple.sharepoint.group.1)
--- lldpd/sbin »


I create lldpd and _lldpd user, but still cannot show neighbors.
By the way ,I was install lldpd using the followed cmd:

brew install https://raw.github.com/vincentbernat/lldpd/master/osx/lldpd.rb

Thanks

**Comment by elaron** [comment]
I use the follow cmds install lldpd on Mac:
brew install https://raw.github.com/vincentbernat/lldpd/master/osx/lldpd.rb

and create _lldpd user and group , see :
lldpd/sbin » id _lldpd
uid=206(_lldpd) gid=206(_lldpd) groups=206(_lldpd),12(everyone),61(localaccounts),100(_lpoperator),701(com.apple.sharepoint.group.1)

and lldpd daemon working normally:
lldpd/sbin » ps -ef|grep lldp
    0 24877     1   0  1:48       0:00.02 /usr/local/opt/lldpd/sbin/lldpd
  206 24884 24877   0  1:48         0:00.07 /usr/local/opt/lldpd/sbin/lldpd
  501 29384  1399   0  3:05  ttys001    0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn lldp

but, when I try  show neighbors under lldpcli, it shows errors:

lldpd/sbin » ./lldpcli                                                        
[lldpcli] $ show neighbors
-------------------------------------------------------------------------------
LLDP neighbors:
2017-02-24T15:04:26 [WARN/control] unable to connect to socket /usr/local/var/run/lldpd.socket: Permission denied
2017-02-24T15:04:26 [WARN/lldpctl] not able to get the list of interfaces. Unable to connect to lldpd daemon
-------------------------------------------------------------------------------

Also, I try to create a new lldp user like suggestions above, but it didn't help neither.

lldpd/sbin » id lldpd                                                          
uid=207(lldpd) gid=207(_detachedsig) groups=207(_detachedsig),12(everyone),61(localaccounts),100(_lpoperator),701(com.apple.sharepoint.group.1)

Is there any help I can get to resolve this problem?
Thanks

**Comment by vincentbernat** [comment]
You don't need to create `lldpd` user. Try to use `sudo lldpcli show neighbors`.

**Comment by elaron** [comment]
Thanks so much, cmd "sudo ./lldpcli show neighbors" works!
