### ISSUE TITLE
Network Policy TLV for VLAN always contains "Tagged: No"

### ISSUE THREAD

**Issue by khbrendel** [vincentbernat/lldpd#88]
When configuring a MED policy with VLAN id there is no way to make the TLV show "Tagged: Yes", instead this bit is always set to zero. At least the command "configure med policy application x vlan y..." does not have any option to influence this bit.

**Comment by vincentbernat** [comment]
I just pushed a fix for that.

**Comment by khbrendel** [comment]
Great, did a rebuild with this fix based on 0.7.7-1 under openwrt and I can confirm it works. And it solves the problem I had, because the Cisco 7906 phone ignored the VLAN ID as long as the tagged flag was not set.
