### ISSUE TITLE
Decode of LLDP_TLV_MGMT_ADDR TLV

### ISSUE THREAD

**Issue by drflynn** [vincentbernat/lldpd#89]
When processing the LLDP_TLV_MGMT_ADDR TLV within lldp_decode() the CHECK_TLV_SIZE macro is invoked three times as the logic decodes the various sub-fields within the TLV. The second and third CHECK_TLV_SIZE macro invocations do not take into account the size of the previously processed sub-fields.

**Comment by vincentbernat** [comment]
You are right. There was another occurrence in protocol identity decoding. I have fixed them both. I will also modify the `PEEK_*` macros to do boundary checking to avoid similar problems in the future.
