### ISSUE TITLE
is it require to create  _lldpd user and a _lldpd group ?

### ISSUE THREAD

**Issue by iicsanjeev** [vincentbernat/lldpd#90]
Hello,
I am trying to build source code on one of the linux system, in which I don't have permissions to create create user and group. So, I want to know is it mandatory to create _lldpd user and a _lldpd group for using this utility.

**Comment by vincentbernat** [comment]
You can use `./configure --with-privsep-user=root --with-privsep-group=root`, or `./configure --with-privsep-user=nobody --with-privsep-group=nogroup` if they exist on your system.

**Comment by iicsanjeev** [comment]
Thanks vincent for your quick response. Yesterday, I have installed ubuntu12 in virtual box
sanjeev@sanjeev-VirtualBox:~$ uname -a
Linux sanjeev-VirtualBox 3.2.0-29-generic-pae #46-Ubuntu SMP Fri Jul 27 17:25:43 UTC 2012 i686 i686 i386 GNU/Linux
I have followed following steps
step 1
sanjeev@sanjeev-VirtualBox:~$ sudo apt-get install lldpd
[sudo] password for sanjeev: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done

step2:

sanjeev@sanjeev-VirtualBox:~$ sudo lldpd -d
[sudo] password for sanjeev: 
lldpd_get_os_release: could not open /etc/os-release: No such file or directory
lldpd_main: protocol LLDP enabled
lldpd_main: protocol CDPv1 disabled
lldpd_main: protocol CDPv2 disabled
lldpd_main: protocol SONMP disabled
lldpd_main: protocol EDP disabled
lldpd_main: protocol FDP disabled
asroot_ctl_create: [priv]: unable to create control socket: Address already in use
fatal: unable to create control socket /var/run/lldpd.socket

So, please suggest.

**Comment by iicsanjeev** [comment]
it seems that lldpd is already running and no more control socket can be created.

sanjeev@sanjeev-VirtualBox:~$ ps -aux

sanjeev   1821  0.0  0.2   7192  3648 pts/2    Ss   09:08   0:00 bash
root      2387  0.0  0.0   8944  1312 ?        Ss   09:10   0:00 /usr/sbin/lldpd
_lldpd    2389  0.0  0.0   8944   564 ?        S    09:10   0:00 /usr/sbin/lldpd
sanjeev   2464  4.2  7.2 479184 112000 ?       Sl   09:12   4:01 /usr/lib/firefox/firefox

please correct me I am wrong.

**Comment by vincentbernat** [comment]
Yes, that's right.
