### ISSUE TITLE
Configuration of lldpd service and usage of .conf file.

### ISSUE THREAD

**Issue by Phalen** [vincentbernat/lldpd#91]
I have a centos7 system I am trying to get the service to start "lldld -ccc"  If I read the varous posts right lldpd.conf /cli conf  will never be able to enalbe cdp. 

Where does one go to put options in to the service so that it will start with cdp enabled? preferrably v2

The man page and such say put configurations in a conf file but no examples are given.  this is a little frustrating for some one who hasent followed this project for a while

**Comment by vincentbernat** [comment]
On CentOS, you can put the `-ccc` argument in `/etc/sysconfig/lldpd`. They will be picked up by the init script.

**Comment by vincentbernat** [comment]
Not really a bug, closing.
