### ISSUE TITLE
is it possible to run two lldpd daemon process on same linux machine ?

### ISSUE THREAD

**Issue by iicsanjeev** [vincentbernat/lldpd#92]
Hello,
I have installed latest lldpd open source code in virtual box (having ubuntu as guest OS).
I don't have two linux computer, 
Question 1: so can I run/configure lldpd daemon on same machine ?

Question 2: Or can I use two virtual box (having ubuntu as guest OS) on two different machine, and the run 
./lldpd -d -d -d 
in both virtual box.
And then test the lldpd protocol buy running 
./lldpdcli -d -d -d 
in one of the virtual box. 

Actually, I want to test/simulate lldpd and lldpdcli protocol and then i will port that in Tizen OS.

So, please suggest.

**Comment by vincentbernat** [comment]
You can run two lldpd daemon on the same machine by using `-L` option to make one of them use a different unix socket. However, it is unlikely they will see each other.

For the virtualbox solution, this could work if you use bridge networking. But you need to run one daemon on the host system and one daemon on the guest system. Two guest systems won't see each other as they are separated by a bridge.

You can also run only one instance and create a pair of veth interfaces to make it see itself:

```
ip link add name peer1 type veth peer name peer2
ip link set up dev peer1
ip link set up dev peer2
```

**Comment by iicsanjeev** [comment]
"But you need to run one daemon on the host system and one daemon on the guest system. "

Since I have installed virtualbox in windows 7 (Host system) and installed ubuntu in virtual box (guest system).
So, just want to clarify my doubt, you mean to say I need to run one daemon on window 7 (host system) and another daemon on ubuntu (guest system) ?

if yes, then my next question is how can I install lldpd on windows7 system ?

**Comment by vincentbernat** [comment]
lldpd is not compatible with Windows. Maybe two guests system will see each other on a Windows host. It really depends on the bridge letting LLDP frames through.

**Comment by iicsanjeev** [comment]
I have installed latest lldpd open source code on two different linux system. And done following steps
Linux system 1:
./lldpd -d -d -d

Linux system 2:
./lldpd -d -d -d

And then run
Linux system 1:
./lldpdcli -d -d -d 

and typed following command "show neighbors ports eth0 summary"

output:
-------------------------------------------------------------------------------
LLDP neighbors:
-------------------------------------------------------------------------------

I don't know what configuration setting I am missing. So, please do I making any mistake because of which I am not able to see neighbors ?

**Comment by vincentbernat** [comment]
If the two guests are not seeing each other, there is little you can do. Instead, use only one guest and setup a veth pair like described in my first answer.

**Comment by iicsanjeev** [comment]
Just want to share logs

[lldpcli] # show configuration
2015-01-23T15:17:45 [ DBG/lldpctl] tokenize command line
2015-01-23T15:17:45 [ DBG/lldpctl] argument 00: `show`
2015-01-23T15:17:45 [ DBG/lldpctl] argument 01: `configuration`
2015-01-23T15:17:45 [ DBG/lldpctl] process argument 00: `show`
2015-01-23T15:17:45 [ DBG/lldpctl] process argument 01: `configuration`
2015-01-23T15:17:45 [ DBG/lldpctl] process argument 02: `<CR>`
2015-01-23T15:17:45 [ DBG/lldpctl] show running configuration
-------------------------------------------------------------------------------
Global configuration:
-------------------------------------------------------------------------------
Configuration:
  Transmit delay: 30
  Transmit hold: 4
  Receive mode: no
  Pattern for management addresses: (none)
  Interface pattern: (none)
  Interface pattern for chassis ID: (none)
  Override description with: (none)
  Override platform with: (none)
  Override system name with: (none)
  Advertise version: yes
  Update interface descriptions: no
  Promiscuous mode on managed interfaces: no
  Disable LLDP-MED inventory: yes
  LLDP-MED fast start mechanism: yes
  LLDP-MED fast start interval: 1
  Source MAC for LLDP frames on bond slaves: local
  Portid TLV Subtype for lldp frames: unknown
-------------------------------------------------------------------------------
[lldpcli] # 

 "Receive mode: no"
It seems that receive mode is off.
If this is the case then how can I enable both receive and transmit mode of lldpd?

**Comment by vincentbernat** [comment]
`Receive mode: no` means that `lldpd` is not in receive-mode only. So, it is transmitting LLDP frames.

**Comment by vincentbernat** [comment]
Nothing more to solve here, closing.
