### ISSUE TITLE
Compilation error when compiling out Dot3 with MED enabled

### ISSUE THREAD

**Issue by ILartey** [vincentbernat/lldpd#94]
Hi Vincent,
Thanks for the work on lldpd.

In 0.7.13 when I compile out Dot3 support "--enable-dot3=no" I get the following compilation error:

../../../src/lib/atom-private.c:260: error: 'port_dot3_power_priority_map' undeclared here (not in a function)
compilation terminated due to -Wfatal-errors.

It is trying to define port_med_pow_priority_map as a pointer to the fixed array port_dot3_power_priority_map.
Where the definition of port_dot3_power_priority_map is protected by #ifdef ENABLE_DOT3 but 
the array elements do contain LLDP_MED_xxx defines, so I suppose that it was intended for double duty in both MED and Dot3. I guess it should leave the ENABLE_DOT3 protection and be covered by #if defined ENABLE_DOT3 || defined ENABLE_LLDPMED.

That change compiles OK but I've not tested it much further than that.

Regards,

Ian

**Comment by vincentbernat** [comment]
Thanks, I just fixed that like you said.

**Comment by ILartey** [comment]
Thanks again.
