### ISSUE TITLE
Improve automatic choice of management address?

### ISSUE THREAD

**Issue by goadwharry** [vincentbernat/lldpd#96]
Hello Vincent,

I have a device which usually has 2 IP addresses on the same ethernet device (eth0):

ip address show eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP8200> mtu 1500 qdisc pfifo_fast qlen 1000
    link/ether 00:0c:8d:00:0c:0f brd ff:ff:ff:ff:ff:ff
    inet 169.254.124.111/16 brd 169.254.255.255 scope link eth0:avahi
       valid_lft forever preferred_lft forever
    inet 192.168.65.133/24 brd 192.168.65.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::20c:8dff:fe00:c0f/64 scope link 
       valid_lft forever preferred_lft forever

One address is always present and is a linked local (scope link) address like 169.254.124.111 and the other should be a regular address (scope global) like 192.168.65.133. This second address is usually available but it is possible that it has not been set up. 

Starting lldpd without parameters always results in the 1st address being used as the management address but this is always the linked local address on my system. Of course, I could use the "-m " parameter to set the management address but, in my case, both addresses are dynamically allocated and I cannot use fixed addresses in start up scripts (I guess I could use some bash-magic to extract the address I want...)

I would suggest that it makes more sense for lldpd to choose the address that has a global scope as long as it exists to advertise as a management address and to fall back to the linked local address only if no global address is found. i.e. the management address should be the first global address found or, failing that, the first linked local address found.

I must admit that I do not know if the above mentioned change makes any sense to anyone else's environment but it seems to me to be a better default than always choosing the first address.

What do you think?

Thanks for your help and the great software!

--
Howard

**Comment by vincentbernat** [comment]
You can use `-m 192.168.*` to ensure that the right address is selected. However, it may makes sense to not use a scope link address.

**Comment by goadwharry** [comment]
Thanks for the very fast response Vincent.
I suspect your patch makes sense in most circumstances. However, for me it's probably still not quite what I was looking for because if I do not have a scope global address at all (e.g. because no DHCP server has responded to give me one) I will only have scope link addresses available and I would like my device to advertise these in this case. 

However, now that you've shown me the correct place in your code I can always fork the project and build in the strange logic that suits my situation without having to affect anybody else.

Regards,

--
Howard

**Comment by vincentbernat** [comment]
I did the change for IPv4 only because this was already the case for IPv6. This could be enhanced to prefer global addresses to local addresses.

**Comment by vincentbernat** [comment]
I did push another commit that should do exactly what you want out of the box.

**Comment by goadwharry** [comment]
Thanks. It looks good. I will try it on Monday when I get access to the hardware again.

**Comment by goadwharry** [comment]
Yes! It works exactly as I hoped. Thanks again for your help.
